### ISSUE TITLE
Feature request - plugins

### ISSUE THREAD

**Issue by alkan** [moquette-io/moquette#1]
Dear Andrea,

We need to extend Moquette for customizing authentication and autherization functionalities.  The code includes two authentication scheme but it does not allow to plug ours in by configuration.  Additionaly, we'd like to catch 'subscribe' events, and on an authorization check the server should let the subscription request would be accepted or npt.

Thank you

**Comment by andsel** [comment]
Hi Alkan,
I expect to introduce some concept of plugins into Moquette in the near future. So you need an authorization verification on "subscribe event" from a client, the structure of moquette is based on non blocking io, so such a verification should be done in asych mode (else it blocks the processing of all other MQTT messages). To get things done in this way in an extenstion point, I've to restructure a little bit the protocol processing. To push new developmetn on the project 'm waiting the project is moved under the Eclpise repository (but at the moment I'm swaped with legal stuff in my employer side).

 Regards
   Andrea

**Comment by francisdb** [comment]
+1 for this

**Comment by andsel** [comment]
Introduced with the interceptors in pull request https://github.com/andsel/moquette/pull/76
