### ISSUE TITLE
use same clientID to connect , the new subscription can't receive message

### ISSUE THREAD

**Issue by tixo** [moquette-io/moquette#108]
hi @andsel ,  in processConnect method , the code

```
if (m_clientIDs.containsKey(msg.getClientID())) {
           ...
            oldSession.close(false); // trigger channel inactive
          ...
}
m_clientIDs.put(msg.getClientID(), newConnDescr);
```

will put the same clientID and new connection to m_clientIDs,  then the channel inactive will be triggered and the processConnectionLost logic will remove the clientID and newConnDescr  form m_clientIDs ,

```
m_clientIDs.remove(clientID) != null  //remove the connection
```

 so when publish to the new subscription ,  broker can't found the connection from m_clientIDs .

**Comment by andsel** [comment]
Hi @tixo nice catch, I've fixed it with a7aba651b8b966216c13149970f00e470c8cdadb
