### ISSUE TITLE
Best way to embed to be able to send/receive messages by embedding application

### ISSUE THREAD

**Issue by johnsirach** [moquette-io/moquette#110]
First of, good work on your project!

I'm using your moquette implementation in a project of mine and are embedding it. But, I'm not able to find a method so that i'm able to embed it in such a way my server application is receiving the messages and my server application can inject messages to be send out.

Currently i'm putting code of mine inside your code (custom listener implementations) to be able to receive the messages and inject qos0 message to be send out.

Is there an object living somewhere where i can register a listener to receive messages from clients and post my messages to to be broadcasted?

Next to this, authentication (if possible) should be handled by my app as also the certificate handling.

If not, can this then be handled as a feature request?

Cheers,
John.

**Comment by andsel** [comment]
Hi John
at the moment Moquette provides a mechanism (interceptor) to intercept
certain king of events,but you can't inject.
The interceptors are registered by configuration providing the class name,
this pat of Moquette is not completely developed, so any suggestions could
help.
You should open a feature request, providing more details possibles on the
request.
Thanks a lot

  Andrea

**Comment by johnsirach** [comment]
Currently i have quite a dirty method with a custom listener inside ProtocolProcessor which 

called with (quick write) 
`SimpleMessaging.getInstance().getProcessor().addExternalListener(this);`
and is handled with a 
`handleFromBroker(String clientId, String topic, ByteBuffer message);`

And injecting messages is done with (replaced the vars):

```
                PublishMessage message = new PublishMessage();
                message.setTopicName(new StringBuilder("/hooks/devices/")
                                        .append(device.getId())
                                        .append("/")
                                        .append("groupname")
                                        .append("/")
                                        .append("controlname").toString());
                message.setRetainFlag(false);
                message.setQos(AbstractMessage.QOSType.MOST_ONE);
                message.setPayload(ByteBuffer.wrap(somebytes));
                SimpleMessaging.getInstance().getProcessor().processInternalPublish(message);
```

processInternalPublish hands it over to the publisher.

It's a quick and dirty, but it works, it is running for months now, and it's time for updating, so was hoping there was a mechanism in place.

P.S. not seeing an enhancement option, am i blind or..... 

It would then be multiple enhancements by the way. To correctly embed moquette I should be able to pass certs from the server's key store (which my users create to run ssl connections already running on the server) where moquette is being embedded in and take over/implement auth mechanisms

P.P.S. IT is for my PiDome project where moquette is now being used as a plugin.

**Comment by andsel** [comment]
Hi John
I've just a question, if I well understood you need some "signalling
mechanism" of a publish received, you apply some logic. Then there other
cases where you need to publish a message, but for publish you could use a
local client connected to the broker that actually do the publishing stuff.
 Instead, if you need a mechanism to "host" code executed inside the
broker, then it's a more complex scenario, because the broker is an
autonomous system that is run on top of Netty's event loops. If we need
such a plug system, problably (this is planned) the broker need to use some
observer/observable concept that don't break the threading (the rule is
don't stop the event loop with long synchronous operations), I mean that I
would use RxJava or Reactor for this job, because the broker can't trust
the client code to starve in JDBC connections or such long running tasks.
What do you think?

 Andrea

**Comment by johnsirach** [comment]
Yes, you are correct, having Reactor for this would be a nice solution for handling messages received, currently data is being "copied" and passed to the server receiving thread to stay out of the broker's way as much as possible and without references. If this can be replaced by a more proven and more robust way everyone profits from, why not.

For me personally, and maybe also for others embedding moquette it would be very nice to have a mechanism to inject messages, certificates and handle the authentication.

Moquette is now serving messages from my system almost immediately from the internal event bus  with only translation to a /hook/#/# topic and a semantic topic like /home/floor/room/#/# standing in between.

My eventually feature requests would then be: 
1: Possibility to supply certificates for ssl (from my code)
2: Possibility to listen for published and possibility to inject messages (from my code)
3: Handle the authorization. (also from my code)

What is the best way, do three feature requests, or just one as "Enhancing moquette embedding" ?

[edit]
Regarding to have a client connected to the broker for the messaging. My system can not permit missing any messages while running, even with QOS 2 and a reconnect any missed message is too late as i need to work with current state events.[/edit]

**Comment by andsel** [comment]
Hi John,
the best is to create 3 feature request.
I don't understand very well what you mean "supply certificates for ssl"?
Do you mean that at runtime you need to add certificates, or just to set
your certificate at broker bootstrap (as it does loading from filesystem)
but provided by you in some fashion (perchaph byte[] I suppose)

Thanks
 Andrea

**Comment by johnsirach** [comment]
I will do three requests then.

With supplying the certificate it would be nice to have the possibility to supply a loader like (very abstract) moquette->setCertificateLoader(MyLoader);

**Comment by andsel** [comment]
I close the issue because splitted in 3 feature request (#133, #114 , #115)
