### ISSUE TITLE
Cannot use moquette-broker via maven

### ISSUE THREAD

**Issue by wagnerluis1982** [moquette-io/moquette#112]
I can't embed moquette in my project as a maven dependency. I did the two steps below:
1. From _moquette root directory_ I executed `mvn clean install` (after that I can see the jars in my local maven repository).
2. Inside my project, I configured my POM as following and I ran `mvn compile` (maven error: _Could not find artifact org.eclipse.moquette:moquette-parent:pom:${moquette.version}_).

``` xml
    <dependency>
      <groupId>org.eclipse.moquette</groupId>
      <artifactId>moquette-broker</artifactId>
      <version>0.8-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
```

I investigated and found out that by changing `${moquette.version}` placeholder of moquette POMs to the version `0.8-SNAPSHOT` the things worked well. I also checked out to version moquette 0.7, when this _moquette.version_ property was not used and it worked well too.

Related link: https://groups.google.com/d/msg/moquette-mqtt/yAiK_RLOtqE/OYEthXKpCgAJ

**Comment by andsel** [comment]
Fixed by PR #117

**Comment by andsel** [comment]
I'll change a little bit to use the ${project.version} whenever possible

**Comment by wagnerluis1982** [comment]
It's a good decision. A different build tool like _gradle_ might improve
too.

## 

Wagner Macedo
