### ISSUE TITLE
[FtrRequest] Handle Auth/ACL by embedding application

### ISSUE THREAD

**Issue by johnsirach** [moquette-io/moquette#114]
As requested from #110 

To enhance embedding moquette possibilities it would be nice to have an interface available in the broker which makes it possible to supply an ACL and authorization mechanism.

I personally think is to have the both combined would be the way to go
`moquette->setACLHandler(myHandler);`

The interface could have the following defined (abstract)

```
handleAuthorization(String clientId, String username, String password); ///possibility to restrict users to clients
isAllowed(Enum[READ,WRITE,READWRITE] method, String path);
```

I understand the possible implications especially when isAllowed is executed that it may not take too long to clutter the messaging queue. In my case it would be cached as long the user is connected.

**Comment by andsel** [comment]
Fixed with commit #446c8465728fffe7a9278accb41c5af14a5fad34 exposed 2 existing interfaces (IAuthenticator and IAuthorizator) in the bootstrap of an embedded server instance
