### ISSUE TITLE
[FtrRequest] Add a possibility to supply certificates from embedding application

### ISSUE THREAD

**Issue by johnsirach** [moquette-io/moquette#115]
As requested in #110 

With supplying the certificate it would be nice to have the possibility to supply a loader like (very abstract) moquette->setCertificateLoader(MyLoader);

Use case:
Embedding application is already handling SSL connections (plain tcp,http,etc..). When moquette is started it uses a different keystore then the embedding application does. With the above possibility the embedding application is able to supply the already used certificate to moquette.

Maybe it is possible to merge this request with #114 ?

**Comment by andsel** [comment]
Defined a new interface ISslContextCreator witha method to instantiate an SSLContext
