### ISSUE TITLE
hello andsel   my  use moquette 0.7   Strange bug

### ISSUE THREAD

**Issue by zhoudianyou** [moquette-io/moquette#12]
test  case     moquette  0.7  update for 2015-1-26 
client  eclipse.paht.javaclient   version :1.0.1   

aclient (clear session false)
bclient (clear session false)

a  ->  connection Server 
b  ->  connection Server 
b  -> subscriptions "abc/topic"  (qos =0)
b  ->  distconnection  or lostconnection

a ->publish ("abc/topic","test1",qos=2,false);  
...
a ->publish ("abc/topic","test10",qos=2,false);  

b -> connection Server 
received message    test1
...
received message   test10

b-> distconnection Server or loast connection 
b->connnection Server 
received message    test1
...
received message   test10

why repeat received  message

**Comment by andsel** [comment]
Hi @zhoudianyou thanks for your bug report, i've fixed on the master
