### ISSUE TITLE
[FR] Make the broker as libray OSGI bundle

### ISSUE THREAD

**Issue by andsel** [moquette-io/moquette#122]
The broker and it's dependency (parser_commons and netty_parser) has to be valid OSGi bundles. They should be intended as libraries, so no service should be launches on bundle start up.

**Comment by LiangCan** [comment]
"Mqtt discussion group" inside said moquette0.8 test results "bottleneck moquette in the database file", I used the original ecology of the following test result :
[app]2016-02-24 14:55:56,589 INFO  mqtt-client - 7625 connection succeeded！
[app]2016-02-24 14:55:59,620 INFO  mqtt-client - 7626 connection succeeded！
[app]2016-02-24 14:56:02,684 INFO  mqtt-client - 7627 connection succeeded！
[app]2016-02-24 14:56:05,742 INFO  mqtt-client - 7628 connection succeeded！
[app]2016-02-24 14:56:08,793 INFO  mqtt-client - 7629 connection succeeded！
[app]2016-02-24 14:56:11,860 INFO  mqtt-client - 7630 connection succeeded！
[app]2016-02-24 14:56:14,934 INFO  mqtt-client - 7631 connection succeeded！
[app]2016-02-24 14:56:17,991 INFO  mqtt-client - 7632 connection succeeded！
[app]2016-02-24 14:56:21,075 INFO  mqtt-client - 7633 connection succeeded！
[app]2016-02-24 14:56:24,144 INFO  mqtt-client - 7634 connection succeeded！
[app]2016-02-24 14:56:27,225 INFO  mqtt-client - 7635 connection succeeded！
The average three seconds to establish a connection。

**Comment by LiangCan** [comment]
I would like to ask how to replace mapdb, because "mqtt discussion group," which some say modify this openfile single test client number can reach 30k.

**Comment by andsel** [comment]
What are you talking about? Sorry man but what you are asking is not
related to the issue, so if you have to ask question use the google group
for Moquette., and try to be more clear in request, because I can't
understand what you are asking, in the phrase "modify this openfile single
test client number can reach 30k." what test client you  are talking? the
number can reach 30K, what 30 K you are meaning.

 Regards
Andrea

**Comment by LiangCan** [comment]
I'm sorry, my English is poor, I want to say is, it was suggested and do not use "MapDB", moquette can run on a single machine, he did the number of clients connected to reach 30k, he said moquette It does not support clustering, but I see here so confused about OSGI

**Comment by andsel** [comment]
OSGi has been reintegrated by PR #240
