### ISSUE TITLE
Rapsberry Pi - doesn't work => very slow

### ISSUE THREAD

**Issue by robertgregor** [moquette-io/moquette#123]
Hello, I have tried to embed the moquette to another java application running on the Raspberry Pi. But in fact it doesn't work at all - or it is very slow. Seems, there is some issue with threads maybe???

**Comment by robertgregor** [comment]
I am missing completely the javadoc, so I am just running is as Server.main(new String[]{});
How can I provide the parameters or expose the logging i.e.???

**Comment by andsel** [comment]
- For integration you could look for https://github.com/andsel/moquette/blob/master/embedding_moquette/src/main/java/org/eclipse/moquette/testembedded/EmbeddedLauncher.java.
- To expose logging you just to configure log4j.properties and set the property system `log4j.configuration`
- About the performance could you provide a log at DEBUG level?

**Comment by andsel** [comment]
Hi @robertgregor  no news about this from you, so I close it.
