### ISSUE TITLE
netty session lost when two client connected with the same clientid

### ISSUE THREAD

**Issue by fjcyue** [moquette-io/moquette#124]
Hi guys,
There is something wrong when two client mistakenly connected with the same id.

broker attempt to force close the previous session if a newcomer has the same client id.
but, the later session maybe inconrrectly removed by processConnectionLost()  event of previous session, for this may be happened after the newcomer's processConnect() event.

In this case, the previous mqtt client is fully disconnected, but the broker lost the handler of newcomer's  netty session

**Comment by andsel** [comment]
Have you give a look at issue #108?
Have tried with latest sources? If yes could you provide the logs at DEBUG level?
 Andrea

**Comment by fjcyue** [comment]
Yes，it's the same problem，but the fix doesn‘t work。
Sorry i lost the log，the event sequence is processConnect() of client Y finished in thread A，and then processConnectionLost() of client X happened in thread B。
In this situation，evt.sessionStolen of client X is true, and m_clientIDs.remove(clientID) != null remove the session of client Y.

I fix this bug by:
1. moving subscriptions.deactivate(msg.getClientID()) from processConnectionLost() into processConnect() 
2. delete m_clientIDs.remove(clientID) != null in processConnectionLost() for it's already replaced by m_clientIDs.put(msg.getClientID(), connDescr) in processConnect()

BTW: i am a freshman of github, when i try to submit my changes of this issue, i got an error of "git-receive-pack not permitted"，is this because of i doesn't have permission to submit to this project，or something wrong with my git？

**Comment by andsel** [comment]
This is identical case of issue #116
