### ISSUE TITLE
ProtocolProcessor RuntimeException when many clients subscribe the same topic, that client disconnected.

### ISSUE THREAD

**Issue by combineads** [moquette-io/moquette#126]
Dear @andsel 
Thank you for create the moquette.
We run a product service using the moquette very well.

When many clients subscribe the same topic and a client sends a message, the moquette broker sometimes occurs RuntimeException. After some clients can't receive a messages.

In my opinion, you have the following code changes to debug message and return.
Thank you.

/moquette-broker/src/main/java/org/eclipse/moquette/spi/impl/ProtocolProcessor.java 417

```
    if (m_clientIDs.get(clientId) == null) {
        //TODO while we were publishing to the target client, that client disconnected,
        // could happen is not an error HANDLE IT
        throw new RuntimeException(String.format("Can't find a ConnectionDescriptor for client <%s> in cache <%s>", clientId, m_clientIDs));
    }
```

**Comment by combineads** [comment]
I think the code above should be like:

```
    if (m_clientIDs.get(clientId) == null) {
        LOG.debug("Can't find a ConnectionDescriptor for client <%s> in cache <%s>", clientId, m_clientIDs);
        return;
    }
```

**Comment by andsel** [comment]
You cite many clients and probably it's the same bug ad in issue #119, I fixed that so I close also this
