### ISSUE TITLE
New Release 0.7.1 or 0.8?

### ISSUE THREAD

**Issue by pabloa** [moquette-io/moquette#127]
Hello

I am using moquette server 0.7 and it is working fine for me except for one thing: from time to time I got an error like:

```
java.lang.RuntimeException: Can't find a ConnectionDescriptor for client <paho346225969102440> in cache <{paho347664825952824=ConnectionDescriptor{m_clientID=paho347664825952824, m_cleanSession=true}, TY - 38fa76e767ce3073=ConnectionDescriptor{m_clientID=TY - 38fa76e767ce3073, m_cleanSession=true}}>
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.sendPublish(ProtocolProcessor.java:439)
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.forward2Subscribers(ProtocolProcessor.java:388)
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.executePublish(ProtocolProcessor.java:317)
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.processPublish(ProtocolProcessor.java:301)
    ... 11 more
```

I understand this issue was solved in master branch.

Is it possible to relate a new version of the code? I could use a branch directly but the last version was from july. Perhaps it is time to publish version 0.8

Pablo

**Comment by andsel** [comment]
Hi Pable,
before the release I would terminate the refactoring of persistence
classes, solve some bugs and perhaps introducing RxJava as a mechanism to
execute the Interceptors.
The release should be 0.8 and probably by the end of the year.

 Andrea

**Comment by jkandasa** [comment]
@andsel It would be nice to release 0.8-SNAPSHOT(nightly build) until we will get 0.8 release.

**Comment by pabloa** [comment]
Hello Andsel.
Thanks for the update. My problem is this: I am using moquette for a product that will go online in december and I am getting those exceptions. They disconnect some servers (connected using java paho). Is it possible to have a 0.7.1 release with the needed patchs applied? 
I could help preparing such release. It would be a release with only those fixes. 
The reason I am insisting with a release is that there is no way my company uses an arbitrary git revision.
Perhaps other people ( @jkandasa ? :) ) could help to prepare a release branch with the patches we need.

**Comment by andsel** [comment]
Hi @pabloa,
we could remove some part from 0.8 and make the 0.8-SNAPSHOT the official
0.8 release, moving some feature to a next 0.9.
Could you do some test with the current master and check if it fixes your
bug? If so we could think about it.

 Andrea

**Comment by jkandasa** [comment]
@andsel Could you please give some rough estimate when we can get 0.8-SNAPSHOT version?

**Comment by pabloa** [comment]
Hello @andsel 
After 3 days of testing, revision fdf5b03 solved the issues I had. It looks solid enough too.
I vote +10 for a 0.8 release.

Pablo

**Comment by andsel** [comment]
Hi @pabloa 
I've just terminated an important refactoring on the storage part, separating the session store and the message store, could you retry your check please.
If it works well I'm going to move the namespace (from org.eclipse.moquette to io.moquette, it's an Eclipse Foundation explicit request) and bump the 0.8 release.
 Thanks, I wait for news from you
   Andrea

**Comment by andsel** [comment]
Hi @pabloa 
I've just terminated an important refactoring on the storage part, separating the session store and the message store, could you retry your check please.
If it works well I'm going to move the namespace (from org.eclipse.moquette to io.moquette, it's an Eclipse Foundation explicit request) and bump the 0.8 release.
 Thanks, I wait for news from you
   Andrea

**Comment by pabloa** [comment]
ok. Testing it.
Pablo

**Comment by pabloa** [comment]
It works! :+1:
