### ISSUE TITLE
benchmark

### ISSUE THREAD

**Issue by Kracexu** [moquette-io/moquette#128]
hi,@andsel, thank you for your excellent moquette,it works very well.Recently,I want to benchmark the throughput for publishing and subscribing with 100000 clients.is there  any benchmark tools for MQTT Broker?thank you

**Comment by andsel** [comment]
Hi @Kracexu
at moment  I don't have a local test with such numbers, but there are
problems on reaching 10K clients as described in one issue. I'm still
investigating how to solve it.
But if you give it a spin, you'are wellcome.

 Andrea

**Comment by diegovisentin** [comment]
Hi @Kracexu , you can take a look at #79 issue and modify my scripts

**Comment by andsel** [comment]
Hi @Kracexu  I've used the scripts issue79_stress_multi[sub|pub].groovy and with 10000 client threads connecting subscribing and publishing and it works.

**Comment by Kracexu** [comment]
Hi,@andsel. I have used node.js to make the pressure test.after the testsing .I find that there is two bugs which will cause OutOfMemoryException.but I noticed you have fixed the two in 0.8-SNAPSHOT.
