### ISSUE TITLE
0.8-SNAPSHOT version is not available for public

### ISSUE THREAD

**Issue by jkandasa** [moquette-io/moquette#129]
@andsel 

```
<dependency>
      <groupId>io.moquette</groupId>
      <artifactId>moquette-broker</artifactId>
      <version>0.8-SNAPSHOT</version>
</dependency>
```

The package 0.8-SNAPSHOT is not available from the repository https://bintray.com/andsel/maven/org.dna.mqtt.moquette-broker/view Can you please distribute 0.8-SNAPSHOT version in to http://dl.bintray.com/andsel/maven/ ?

Thank you!

**Comment by pabloa** [comment]
+1

**Comment by andsel** [comment]
Sorry but BinTray is not intendend to be used for snapshots as cited in (https://bintray.com/docs/usermanual/whatisbintray/whatisbintray_correctandincorrectusage.html) "Material that is uploaded to Bintray should be publishable, working software - releases and not snapshots. Bintray’s operational logic is based on every uploaded file being inside a numbered, stable version"
 BinTray is a CDN for final artifacts not a Binary Repository Manager like Artifactory.

 At the moment the only way you could solve is build by yourself and deploy locally (`mvn clean install`) or install in your own Artifactory, at the moment I haven't an account on any free repository.

 Andrea

**Comment by zambrovski** [comment]
Why don't you publish the snapshot to Maven Central?

**Comment by pabloa** [comment]
Hello,

When version 0.8 will be released?

**Comment by andsel** [comment]
Hi @pabloa
before release 0.8 I would fix issues #130, #132 and #133 just to have the
more stable version, but I can't give you a precise date, I hope by the end
of January.

 Andrea

**Comment by ricardojlrufino** [comment]
You can use sonatype Repository
http://central.sonatype.org/pages/ossrh-guide.html

**Comment by andsel** [comment]
Version 0.8 has been published on JCenter
