### ISSUE TITLE
[FR]Moquette clusters

### ISSUE THREAD

**Issue by pabloa** [moquette-io/moquette#131]
I need to set a moquette cluster for HA 
Does moquette support to work in a cluster environment where several moquette serves share topic, connections and messages?
Regards

**Comment by andsel** [comment]
Hi,
at the moment no..but if you would like that feature open a feature
request,detailing and describing what you need.

Andrea
Il giorno 11/dic/2015 03:35, "pabloa" notifications@github.com ha scritto:

**Comment by pabloa** [comment]
Hi Andsel,

I need HA basically. Clients would connect to one node of the client. If clients disconnect, they should be responsible of reconnecting and subscribing again to topics.

Cluster responsibility would be only to propagate to the nodes message publishing (from broker node to client/s). 

Example:

Nodes A, B, C
Topics /t1, /t2
clients c1, c2, c3

clients c1 and c2 connect to broker A
client c3 connects to broker B

client c1 publishes message m1 to /t1, then:
- m1 arrives to A broker node.
- broker nodes sends (m1, /t1) to B and C
- both brokers publishes m1 on /t1 as expected.
- In general pairs (message, topic) would travel to all the connected broker nodes.
- Message sorting should happen by publishing time

Cluster should have not other responsibility.

let me know your thoughts.

**Comment by diegovisentin** [comment]
What about to use something like Hazelcast for sharing messages on all nodes?

**Comment by andsel** [comment]
That's was my intention.
Crating input queues, one for each node. I was planning to keep also
metadata in distributed cache (like which client is connected on which node)

**Comment by pabloa** [comment]
Yes. I was thinking in Hazelcast too. 
Perhaps I have some time to do this (no sure though). In case I can get time approval from my company, any suggestion about what should start looking to work in this issue?

**Comment by andsel** [comment]
I've some ideas, I would share it on the google group till I'm finishing to fix the bugs for release 0.8

**Comment by 68387097** [comment]
hi,I have some questions.i need cluster,nodes share connections,but channel don't be shared in map.i try to use hazelcat,but i am failure.and i try to use redis to store these connnection channels but i am failure.

Could you plz give me some advice,thanks a lot

**Comment by 68387097** [comment]
hi andsel, i don't know How i can do?

**Comment by andsel** [comment]
Hi
at the moment you can't simply because some stuff owning to the client
session (like the file descriptor of the socket) can't be serialized and
moved to another VM, and like this issue says Moquette is not clusterizable
till some develoment is done.

 Andrea

**Comment by 68387097** [comment]
thanks,i used emqttd cluster,but it developedp by erlang,much difficulty to customized.so i want to find a java mqtt-broker-cluster

**Comment by chuyennm** [comment]
Hi these,

How about this: https://github.com/mrniko/redisson it's also using netty & redis(opensource) , Hazelcast have both license, opensource it havent persistence store.

**Comment by andsel** [comment]
As I understand it's only a Redis' Java client, so you have to install
Redis on a machine while I would like to have simmetric machines with least
install requirements, preferably self contained all in JVM.

**Comment by gembin** [comment]
http://ignite.apache.org/   It's pretty cool!

**Comment by andsel** [comment]
It's the open version of GridGain, that's quite similar to Hazelcast, and
in some ways to RedHat Infinispan.

**Comment by testark** [comment]
Bumping. Any news?

**Comment by kevto** [comment]
I would honestly prefer to create an own solution to detect nodes and connect them with each other like EMQ does. And use Redis for storing subscriptions, session data and more.

**Comment by gembin** [comment]
It would be better to design a cluster SPI to allow multiple providers.

**Comment by diegovisentin** [comment]
Do you already defined the design of Moquette clustering?
Probably you already know it, but I found the cluster design of EMQ simple and clear: http://emqtt.io/docs/v2/cluster.html

**Comment by chxiaowu** [comment]
Bumping. Any news?

**Comment by iiliev2** [comment]
@andsel 

> I've some ideas, I would share it on the google group till I'm finishing to fix the bugs for release 0.8

How do I gain access to the group? I cannot find it. Could you please outline a design based on hazelcast? I could work on it and contribute.

**Comment by andsel** [comment]
@iiliev2 maybe you could open a new discussion in GH: https://github.com/moquette-io/moquette/discussions

**Comment by andsel** [comment]
Related to clustering which is not actually on the task list
