### ISSUE TITLE
do not dosomething directly in NettyMQTTHandler

### ISSUE THREAD

**Issue by Kracexu** [moquette-io/moquette#137]
Hi,@andsel. glad to see you remove the LMAX ringbuffer and use multi threading,I also do this thing in the 0.7-SNAPSHOT. 
two issues:
 1) use ConcurrentHashMap instead of Map in MemoryMessagesStore 
 2) We'd better not process mqtt message directly in NettyMQTTHandler.what about using a         ExecutorService.
  by the way you have not change the nextPacketID method in the MemoryMessagesStore.

**Comment by andsel** [comment]
Hi @Kracexu 
1) by now MemoryMessagesStore is intended only for unit testing that are single threaded.
2) the message processing is done by Netty's threads (EventLoop is the "thread" contained in the EventLoopGroup the "thread pool") so moving the processing in a thread managed by an executor service cost a  penalty of context switch and it's not the intended architecture for Moquette, which uses ExecutorService only for user defined notification handlers
