### ISSUE TITLE
API for retrieving a list of client Ids that are connected

### ISSUE THREAD

**Issue by wns349** [moquette-io/moquette#138]
Hi, 
Is there any API to retrieve a list of client Ids that are currently connected to the broker server? 

I notice `m_clientIDs` holds a list of client Ids in `ProtocolProcessor.java`, but not sure if it's okay to return that value. (Maybe through `SimpleMessaging.java`?)

A reason for this API request is because I am developing a program that runs a broker server and manages a list of client Ids who are currently connected for other uses. 
Of course, client Ids retrieved from the broker server can be of unmodifiable collection.

Thanks,

**Comment by andsel** [comment]
Hi @wns349 
that isn't the correct way. If you are embedding moquette, the best way is to subclass `AbstractInterceptHandler` and use the connect/disconnect notifications.

 Andrea
