### ISSUE TITLE
is type error？

### ISSUE THREAD

**Issue by sinozozo** [moquette-io/moquette#139]
in MapDBMessagesStore class file, the filed "m_inFlightIds" is Map<String, AtomicLong>,but in MapDBSessionsStore ,the filed is ConcurrentMap<String, Map<Integer, String>>  ,is it right?

**Comment by andsel** [comment]
Hi the m_inflighIds map and related methods has been moved from MapDBMessagesStore to MapDBSessionsStore. Beeing provided by MapDB it's already thread safe, the code doesn't use any method from ConcurrentMap so it's correct to keep it simply a Map.
