### ISSUE TITLE
Class Not Found when connect

### ISSUE THREAD

**Issue by PaoloFi** [moquette-io/moquette#14]
Using moquette-bundle with equinox console, When a publisher/subscriber attempts to connect, there is an ClassNotFoundException on class org.eclipse.moquette.proto.messages.AbstractMessage$QOSType.

I'm using 0.7 version on Ubuntu 14.10

I' m trying to use Moquette bundle with equinox console. I didn't have any problems during the compiling phase. These are the bundles that i use:

id  State       Bundle
0   ACTIVE      org.eclipse.osgi_3.10.1.v20140909-1633
1   ACTIVE      org.eclipse.equinox.console_1.1.0.v20140131-1639
2   ACTIVE      org.apache.felix.gogo.command_0.10.0.v201209301215
3   ACTIVE      org.apache.felix.gogo.runtime_0.10.0.v201209301036
4   ACTIVE      org.apache.felix.gogo.shell_0.10.0.v201212101605
5   ACTIVE      io.netty.buffer_4.0.24.Final
6   ACTIVE      io.netty.codec_4.0.24.Final
7   ACTIVE      io.netty.codec-http_4.0.24.Final
8   ACTIVE      io.netty.common_4.0.24.Final
9   ACTIVE      io.netty.handler_4.0.24.Final
10  ACTIVE      io.netty.transport_4.0.24.Final
11  ACTIVE      org.apache.felix.javax.servlet_1.0.0
12  ACTIVE      slf4j.api_1.7.10
                Fragments=13
13  RESOLVED    slf4j.log4j12_1.7.10
                Master=12
14  ACTIVE      log4j_1.2.17
15  ACTIVE      org.mapdb.mapdb_1.1.0.SNAPSHOT
16  ACTIVE      org.eclipse.moquette.bundle_0.7.0.SNAPSHOT

I attach the start up script and the moquette.log.

PS I don't have this problem with main version.
![screen1](https://cloud.githubusercontent.com/assets/10920488/6107623/be705e88-b06c-11e4-8349-12965ccf0f0c.png)
![screen2](https://cloud.githubusercontent.com/assets/10920488/6107638/dca17770-b06c-11e4-960a-283c3186af83.png)
![screen3](https://cloud.githubusercontent.com/assets/10920488/6107656/f13abe3a-b06c-11e4-980d-05492e1a11ea.png)

**Comment by PaoloFi** [comment]
I solved the problem . At compile time I had to add this to the pom:

<repositories>
        <repository>
            <id>sonatype-snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
</repositories>

 because I could not download the jar relative to MapDb .So I haven't downloaded the file org.mapb.mapdb.1.1.0 fixed .

Fix:
add DynamicImport -Package : \* in the manifest file of the jar org.mapb.mapdb.1.1.0

**Comment by andsel** [comment]
I reopen the issue because the fix to MapDB was already proposed to the MapDB team and they replied that's not the correct solution [https://github.com/jankotek/MapDB/pull/377]. I'll fix once I could study better the OSGi

**Comment by maggu2810** [comment]
Any news?

**Comment by maggu2810** [comment]
The ESH project uses mapdb in an OSGi context.
Perhaps this could help you: https://github.com/eclipse/smarthome/blob/master/bundles/storage/org.eclipse.smarthome.storage.mapdb/src/main/java/org/eclipse/smarthome/storage/mapdb/MapDbStorage.java

**Comment by andsel** [comment]
Hi @maggu2810 no news on this, thank you for the link.
I'm truing to embed the MapDB bundle but at moment I'm fighting with strange import error about sun.misc package that can't be importer.

**Comment by maggu2810** [comment]
IMHO add MapDB to the OSGi bundle of moquette is also just a workaround. If we have multiple bundles in our OSGi runtime (the normal use case) I would just include one MapDB bundle. If multiple bundles ship with embedded MapDB classes, this is not the intention of OSGi (but this is just my understanding of the OSGi framework).

**Comment by andsel** [comment]
I've dropped the support for OSGi in version 0.7. Because I think that nobody use it in OSGi environment and I'm not confident with OSGi. I wasn't able to fix the pax-runner configuration and drain dev resources to keep OSGi compatibility that's not usefull to anybody I suppose, at the end Moquette could be embedded by other  OSGi project just wrapping it.

**Comment by kaikreuzer** [comment]
@andsel From my pov, this is an unfortunate decision - as you might remember, I was actually still planning to integrate Moquette into openHAB as I think this is a great fit. Also @maggu2810 uses OSGi with MQTT and many others do as well (see e.g. @andypiper at https://gist.github.com/andypiper/9654252). Since MQTT is very strong at Eclipse and so is OSGi, I think this is a very relevant combination.

**Comment by andsel** [comment]
Hi Kai,
the motivation for the decision is that I'm not a geek in managing OSGi,
and OSGi is not such a simple thing to manage correctly, every bug or error
notification related to the OSGi compatibility in Moquette, taken me a lot
of time end effort, so waiting better times (when I can manage correctly an
OSGi  environment or somebody with better skills on this stuff jump into
project) I decided to concentrate on bugfixes and features, but if you or
somebodyelse with competence in OSGi want to contribute with a patch
regarding that stuff, it really welcome.

 Andrea

**Comment by kaikreuzer** [comment]
@andsel If there is no general problem with having the OSGi bundle built, I would prefer if you could leave it in - if there are bug reports like this, which you cannot easily solve, just leave them open and wait for some one with OSGi knowledge to come up with a PR with a fix. But dropping the bundle from the build does not even give people the chance to fix it.

**Comment by andsel** [comment]
Hi @kaikreuzer @maggu2810  @PaoloFi, to track this feature request I've created a new issue, #122

**Comment by doandzhi** [comment]
Hello! This issue is almost 3 years old and I still don't seem to find a possible solution for it. Can anyone give me an advice and/or possible solution of this ClassNotFoundException of the internal class QOSType.

**Comment by andsel** [comment]
Given the fact that managing OSGi is not trivial, and I dont' want to spend time in fixing OSGi deps, I dropped the support for OSGi in Moquette and closed this issue as not anymore valid.
 Andrea
