### ISSUE TITLE
Do you get away from MapDB ?

### ISSUE THREAD

**Issue by diegovisentin** [moquette-io/moquette#140]
Reading what the author writes about current version (http://www.mapdb.org/blog/mapdb3.html), maybe it's critical for the success of Moquette to think about a new persistent system.

**Comment by andsel** [comment]
You are right!
I should start to think about other btree store embeddable and with minimal
(if possible) footprint.
-jleveldb (one man show not so much supported)
-cassandra (big footprint but could be a huge leap to moving Moquette in a
clustered broker)
-any suggestion?!,it's mandatory that it could be embeddable so it should
be JVM based.

Andrea
Il giorno 14/gen/2016 21:04, "diegovisentin" notifications@github.com ha
scritto:

**Comment by diegovisentin** [comment]
I never done a software selection for this type of db but after googling a bit IMO maybe you can consider these ones:
- Facebook RocksDB: http://rocksdb.org/
- H2 MVStore: http://www.h2database.com/html/mvstore.html
- OrientDB Hash Index: http://orientdb.com/docs/last/Indexes.html 
- OpenHFT Chronicle Map: https://github.com/OpenHFT/Chronicle-Map

However another approach is to use directly a distribuited cache (aka Hazelcast) with a daemon that stores records in asynch fashion on a "slow" db. This could be also a part of a future support for clustering.

PS: all above is just my two cents ;-)

**Comment by tixo** [comment]
try https://github.com/dain/leveldb
it's a rewrite (port) of LevelDB in Java, it goal is to have a feature complete implementation that is within 10% of the performance of the C++ original and produces byte-for-byte exact copies of the C++ code.

**Comment by andsel** [comment]
Onother could be KahaDB used in ActiveMQ. I'll do some comparision of various libs and decide

**Comment by pabloa** [comment]
Hello

OrientDb.
Please do not use cassandra. It is too big!

In fact, perhaps the best thing is to have mapDb like now, but externalized
in other jar. Separated moquete core from the mapDb store with a set of
interfaces. Same as slf4j does. Therefore everybody will be happy: you will
get rid of the problem using mapDb, people needing stronger solutions will
be happy to help/implement donating an orientdb, cassandra or whatever
implementation and moquette will not depend of other jars (mapDb included)
except they are really being used.

Pablo

**Comment by andsel** [comment]
hi @pabloa at the moment the persistence layer it' divided in interface and implementation, now it's for MapDB, I would expect to create submodules for each persistence engine, and defining a default for the broker distro.

**Comment by ricardojlrufino** [comment]
Why not upgrade to the latest version of MapDB (3.0.2)
I need to use the MapDB in my project and it is still a very old version.

**Comment by andsel** [comment]
Last MapDB has Guava deps, and this bring 6Mb or more of jars. I don't want
such a big dependency, I'm thinking to swith to H2 MVStore, which, from
rought tests, has more performance than the MapDB 1 and less impact on Jar
deps.
My desire is to keep Moquette deps as thin as possible, but due to an
important bugfixing I haven't found time to work on this change :-(

 Andrea

On Wed, Oct 12, 2016 at 2:29 PM, Ricardo JL Rufino <notifications@github.com

**Comment by ricardojlrufino** [comment]
I found a bug in HTreeMap that affect my project. 

I sent a PR for MapDB to fix it in branche1.0
https://github.com/jankotek/mapdb/pull/771

If it integrate you can generate a snapshot?

**Comment by dwimberger** [comment]
Xodus from Jetbrains
https://github.com/JetBrains/xodus

**Comment by ricardojlrufino** [comment]
+1 H2 MVStore
I have been using the H2 database in my project, then that would be very useful....

**Comment by andsel** [comment]
H2 store was implemented

**Comment by ricardojlrufino** [comment]
> H2 store was implemented

How i can use ?
