### ISSUE TITLE
moquette When  Sub Topic = Pub Topic time

### ISSUE THREAD

**Issue by LiangCan** [moquette-io/moquette#142]
I use "mqttv3" Clients subscribe to a "topic1" theme and then the next and then the client sends a message to "topic1", the first time can be successful, but later you will be prompted server response timeout, only to restart the server to release the called "topic1" theme. I'm just a beginner, what place does not welcome that to say, thank you.

**Comment by LiangCan** [comment]
1. Create a client requests a connection
2. Subscribe to "A" s theme and the "A" theme post a message
3. Disconnect Clients
   Step 4. Re-operation 1,2, the
4. The server prompts "server response timeout," but does not disconnect the connection

**Comment by andsel** [comment]
Hi @LiangCan I've created an integration test check your issue (8c14efb7d8409d4959d1237cfd8df13a1fac606e) but it's not reproducible. Perhaps there is something wrong with your client code.

**Comment by LiangCan** [comment]
Hi @andsel 
I would like to ask the ordinary "4 g" "4 core" single test reached a maximum number of client connections?

**Comment by LiangCan** [comment]
Hi @andsel
I would like to ask the ordinary "4 g" "4 core" single test reached a maximum number of client connections?
