### ISSUE TITLE
IAuthorizator.canRead not called at SUBSCRIBE but during consumption

### ISSUE THREAD

**Issue by redboy1972** [moquette-io/moquette#144]
It would appear like the check for subscribing to a topic doesn't immediately call IAuthorizator.canRead but rather waits until a message consumption is attempted in ProtocolProcessor.directSend(...).  

What is the rational for this? 

If there are many messages this results in redundant calls.

It seems that the call in ProtocolProcessor.directSend(...) around line 491
        String user = NettyUtils.userName(channel);
        if (!m_authorizator.canRead(topic, user, clientId)) {
            LOG.debug("topic {} doesn't have read credentials", topic);
            return;
        }

should be moved to:
ProtocolProcessor.processSubscribe(...)

**Comment by redboy1972** [comment]
In addition, it is possible to add a call to InterceptHandler on message consumption.  Perhaps added to directSend(...)

void onMessageConsumed(InterceptConsumedMessage pubMessage);

**Comment by andsel** [comment]
Hi @redboy1972 for the first part I've fixed moving the canRead check from publish to subscribe time.
For the second could you please define better what you mean for "consumed message", consumed by who and where, for this part you could open another issue with feature request indication [FR].
Thanks
 Andrea

**Comment by redboy1972** [comment]
Thanks for this.  I see the change reflected in v 0.8.1
