### ISSUE TITLE
Can't find a ConnectionDescriptor for client <"这里是ClientID"> in cache <"这里是ClientID"cleanSession=true>

### ISSUE THREAD

**Issue by andyxm** [moquette-io/moquette#146]
一个客户端给另一个发消息,服务器端的moquette报错Can't find a ConnectionDescriptor for client <"这里是ClientID"> in cache <"这里是ClientID"cleanSession=true>  具体就是发送时 moquetts.bat中报错 发消息时候报错

**Comment by andsel** [comment]
Hi @kailaico 
sorry but I can't understand chinese ideograms, your description of the problem is really poor, you miss the version your are using, eventual logs and the most important, how to reproduce the bug

**Comment by andsel** [comment]
Closed because the user hasn't provided feedback.
