### ISSUE TITLE
will not build bundle

### ISSUE THREAD

**Issue by carljmosca** [moquette-io/moquette#15]
unresolved dependency

Could not find artifact org.mapdb:mapdb:jar:1.1.0-SNAPSHOT in Paho Releases (https://repo.eclipse.org/content/repositories/paho-releases/)

**Comment by andsel** [comment]
Hi, could you check if the you pulled or clones last 0.7-SNAPSHOT version of moquette, because it use the MapDB 2.0.0-SNAPSHOT and should be configured in oss.sonatype.org SNAPSHOT repository (https://oss.sonatype.org/content/repositories/snapshots/org/mapdb/mapdb/)

**Comment by carljmosca** [comment]
I am not sure I follow you.  I just cloned it.  Did I miss a tag/branch?

**Comment by andsel** [comment]
Broker's pom.xml require mapdb 2.0.0-SNAPSHOT and should be downloaded from the snapshot repository. So I've just committed a little change to the pom,xml, could you please do a "git pull" and then another mvn clean package? Just to discover  the origin of the issue

**Comment by andsel** [comment]
Hi Carl you were right, I missed to configure the repositories in the parent pom
