### ISSUE TITLE
WebSocket can't be disabled

### ISSUE THREAD

**Issue by MiloXia** [moquette-io/moquette#150]
Hi, I use moquette in my application and I find the  websocket can't be disabled.
I find the cause maybe in here: 
in `ConfigurationParser`

```
m_properties.put("websocket_port", Integer.toString(8080));
```

websocket_port have be set a default value
so in the `NettyAcceptor` 

```
String webSocketPortProp = props.getProperty("websocket_port"); // always have a value
if(webSocketPortProp == null) {
   LOG.info("WebSocket is disabled");
} else {
...
```

WebSocket can't be disabled

The version is 0.8

**Comment by andsel** [comment]
Fixed by 5029da8763f54fecb979ab063f2857050b804248
