### ISSUE TITLE
About performance pressure moquette performance?

### ISSUE THREAD

**Issue by LiangCan** [moquette-io/moquette#152]
1.Original ecology "moquette" maximum number of connections?
2.Moquette test methods and tools are there?
3.The current "moquette" What place can be optimized?
- Why not set up a discussion group together to express their views on the inside?

**Comment by andsel** [comment]
The discussion group  already exists check out the ML (https://groups.google.com/forum/#!forum/moquette-mqtt) to open sch a discussion. Issues are just to report FR (already discussed in the ML) or bug report.
  Andrea
