### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by tur-ing** [moquette-io/moquette#155]
In the README version `0.9-Snapshot` is used, on bintray only `0.8.1` and `0.7` are available which do not have the AbstractMessage class and PublicMessage class (example from `moquette_embedded`). So how to embed moquette in an existing maven project?

**Comment by andsel** [comment]
Hi @tur-ing 
On the master there is a typo, so README.md should have 0.9-SNAPSHO, but the other version you are citing contains that class.
