### ISSUE TITLE
new InterceptHandler method

### ISSUE THREAD

**Issue by redboy1972** [moquette-io/moquette#156]
This is a follow up to https://github.com/andsel/moquette/issues/144

Is it possible to add a call to InterceptHandler that would get called as soon as a client acknowledges consumption of a message from a topic.  This would get fired off on receipt of a PUBACK for Qos-1 and PUBCOMP for Qos-2.  Such a method would be used by me to notify the back-end service as soon as a message is consumed/read by a client.

To do this I'm envisioning something like:
BrokerInterceptor.java / InterceptHandler.java
     New method.

> ```
>    @Override
>     public void notifyMessageConsumed(InterceptConsumedMessage msg) {
> ```

ProtocolProcessor.java
    In processPubComp() and ProtocolProcessor.processPubAck()

> ```
>     m_interceptor.notifyMessageConsumed(...)
> ```

BrokerInterceptor.java

> ```
> @Override
> public void notifyMessageConsumed(final InterceptConsumedMessage msg) {
>     for (final InterceptHandler handler : this.handlers) {
>         executor.execute(new Runnable() {
>             @Override
>             public void run() {
>                 handler.notifyTopicConsumed(msg);
>             }
>         });
>     }
> }
> ```

**Comment by andsel** [comment]
Already closed with f44283d5f0e3397d05ea0753c6d617e2fe4c71c6
