### ISSUE TITLE
Ability to use the websocket layer with an another mqtt broker 

### ISSUE THREAD

**Issue by sylvek** [moquette-io/moquette#159]
Is there a (simply) to use moquette for his websocket layer and bridge it to an another mqtt broker like rabbitmq? 

In fact the authentication and authorisation layers of moquette is really cool but I need a more "production ready" broker (we work with rabbitmq most of time)

I read the code and it seems to me ok.. But I would just have some help to and your advice.

**Comment by sylvek** [comment]
Hi, 

If someone is interested.. This is my contribution. https://github.com/sylvek/websocket-mqtt-forwarder

**Comment by andsel** [comment]
No there isn't Moquette is intended to be a broker not a proxy. 

 Andrea
