### ISSUE TITLE
Is there any queue behavior?

### ISSUE THREAD

**Issue by redboy1972** [moquette-io/moquette#161]
MQTT is a topic protocol.  I am aware of that.  What I see is that all incoming messages are stored via several calls to m_messagesStore.storePublishForFuture(...).  This is all as expected for topics.  However if a topic has a lot of publishes/sec it will eventually fill up the db with already consumed messages.  The only way I can see the db shrinking is with a clean session flag at connect/disconnect.  If a client sticks around for a while under high load this rate could overwhelm the back end.

Does this broker have any delete on consumption behavior similar to queues?

**Comment by andsel** [comment]
No at the moment the broker has no concepts ab out queue, but I'm
introducing a journaled queue to solve this and limit the number of
enqueued notifications for slow clients.

 Andrea

**Comment by redboy1972** [comment]
Thanks for the response.  It confirms my suspicions.  It would be a useful feature.  My specific setup will have tens of thousands of incoming messages to the same topic per second.  The consumer is expected to be connected 24x7 and at this rate I suspect an OOM / crash without it.
