### ISSUE TITLE
SimpleMessaging not as a singleton

### ISSUE THREAD

**Issue by ferwasy** [moquette-io/moquette#165]
Hello. SimpleMessaging is implemented as a singleton, which makes impossible to create multiple and independent instances of Server class. Could this be modified in only to create a new instance of SimpleMessaging each time server#startServer() is created?

Kind regards
Fernando

**Comment by andsel** [comment]
It's a desired requirements to not create multiple Server, because each
server create a Netty EventLoopGroup (similar to ThreadPool)..
So it can't be changed, because having multiple EventLoopGroup led to
create many unsueful threads,

 Andrea
