### ISSUE TITLE
two broker problem

### ISSUE THREAD

**Issue by SoonyangZhang** [moquette-io/moquette#166]
hello, I just want to ask what the Broker do if it needs to connect to another Broker. Idid not see the broker has this ability from your code.

**Comment by andsel** [comment]
I can't understand your question what does means "what the Broker do if it
needs to connect to another Broker", do you mean a broker that work in
cluster with  another? If this is your question the answer is no, the
broker has not HA or clustering capabilities at the moment.
For question like this please refer to the google group (
https://groups.google.com/forum/#!forum/moquette-mqtt)

 Thanks

```
Andrea
```

**Comment by SoonyangZhang** [comment]
Thanks a lot. Brokers that work in cluster is just what I mean.
