### ISSUE TITLE
QoS and the MQTT specification

### ISSUE THREAD

**Issue by ogdans3** [moquette-io/moquette#167]
In ProtocolProcessor.java I  found this:

``` java
QOSType qos = publishingQos;
if(publishingQos.byteValue() > sub.getRequestedQos().byteValue()) {
    qos = sub.getRequestedQos();
}
```

This will always set the QoS to the lowest value of the published message and the subscription's QoS.

Following the mandatory normative specification found here in appendix B, section [MQTT-3.8.4-6]:
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html

It should not take QoS 1 if for example the QoS of the publish message is 2 and the subscriber QoS is 1.

Is my understanding of the specification correct?

**Comment by gembin** [comment]
I think it's correct, it should be the lowest QoS according to the spec.

**Comment by ogdans3** [comment]
After re-reading the specification I must agree with you and it should choose the lowest QoS.

My apologies
