### ISSUE TITLE
No such static method error with DBMaker.newFileDB()

### ISSUE THREAD

**Issue by marcuslang** [moquette-io/moquette#169]
MapDBPersistentStore line 61:
DBMaker.newFileDB(...) is not a static method and results in a "No such static method" error

Tested with Version 0.8 and 0.8.1

![image](https://cloud.githubusercontent.com/assets/13761213/14680142/77cf0a80-071c-11e6-9f9e-d49574af6108.png)

**Comment by andsel** [comment]
Are you sure? because mvn clean package doesn't say so, it's an IDE glitch?
 Andrea

**Comment by marcuslang** [comment]
I tried to start the embedded broker inside a JUnit Test and it breaks at this point. But maybe you are right. My IDE says there is no static method. I`ll clean the cache and look further into it.

Thanks for the fast reply
