### ISSUE TITLE
remove the ?  in the grid

### ISSUE THREAD

**Issue by windbender** [moquette-io/moquette#172]
on these pages there is a grid of MQTT brokers:

https://github.com/mqtt/mqtt.github.io/wiki/Server%20support

However the Moquette broker is lacking information and therefore has ? in the grid entries.

**Comment by andsel** [comment]
Hi @windbender, I think you could creare a PR on MQTT's github project to
fix the table, so it could be more impartial than if done by the Moquette
committer.

Moquette support QoS 0,1,2 and at the moment hasn't any
clustering/replication mechanism, it's on the features stack;-)

 Andrea

**Comment by windbender** [comment]
I've edited that wiki.  I indicated cluster as being "rm " for roadmap.  I didn't put $SYS on there, though I know there is a issue ticket for it.
