### ISSUE TITLE
NullPointer in  ClasspathConfig  from  master branch.

### ISSUE THREAD

**Issue by windbender** [moquette-io/moquette#175]
The following code calls the super class "assignDefaults()"  prior to creating an "m_properties" object to hold those defaults.  So there is a null pointer exception within the setProperty() method.

```
assignDefaults();
        try {
            confParser.parse(configReader);
        } catch (ParseException pex) {
            LOG.warn("An error occurred in parsing configuration, fallback on default configuration", sex);
        }
        m_properties = confParser.getProperties();

```

**Comment by windbender** [comment]
In general the ConfigurationParse is not setup to be able to take some "default" values as might be assigned by  "assignDefaults()".

So either two Properties need to be merged ( instead of overwritten in "m_properties = confParser.getProperties();")   OR,  the ConfigurationParser should take a default Properties object on it's constructor.

**Comment by windbender** [comment]
So "Properties" objects have a "defaults" sub Properties object.  Perhaps this could be used to implement. 

However, if the value of a property is null, then the default property is used.  I know that setting "PORT" to null is being used to turn off particular listeners.  So if we attempted to use the "defaults" sub Properties object, then we'd need to move away from the null ===  do not listen configuration technique.

This would indicate that perhaps we should NOT use the "defaults"  sub property, and instead do the "merge the properties" way of fixing this.

**Comment by windbender** [comment]
A third approach is to write the three Configuration classes, so that their local properties object is assigned BEFORE the "parse()"  function is called. e.g.

`
        ConfigurationParser confParser = new ConfigurationParser();
        m_properties = confParser.getProperties();
        assignDefaults();
`

This is a bit convoluted, but involves the least code change, and preserves the notion of null being "turn off"  instead of null being "use the default"

**Comment by windbender** [comment]
@andsel  happy to submit a PR on this as soon as you indicate the approach you'd like me to take.

**Comment by andsel** [comment]
The rationale of default properties is "they are properties mandatory to startup". So the flow should be load default properties and then overwrite with the ones rad by the configuration provided by the caller.
 If you intend to create a PR please create a unit test to cover the ClasspathConfig construction. I've to admit that this part isn't well designed so in future should be rethinked.

**Comment by nemecec** [comment]
Here is some inspiration for configuration loading refactoring in Moquette.
https://github.com/nemecec/moquette/commit/f7de45894c214f45cc2a410abfdb5672424b9d97
Sorry, no unit tests.

Basic idea was to separate parsing from resource loading, so I could load also ACL and password config files from classpath. I tried to keep things as backwards-compatible as possible. If backwards compatibility is not much of a concern, it could be even prettier.

**Comment by andsel** [comment]
Included commit from nemecec and that fixes the NPE in ResourceLoaderConfig class
