### ISSUE TITLE
moquette p2p

### ISSUE THREAD

**Issue by henryxie2093** [moquette-io/moquette#181]
is moquette provide p2p features

**Comment by andsel** [comment]
What do you mean by "p2p features", if you intend master-master replicas
with Hazelcast like stuff, the answer is no.
 Andrea

**Comment by mackristof** [comment]
take a look at this : https://github.com/mackristof/moquette/commit/5aaf22930ec9d55b8b4ab31bfa8937c1ad847ddf

it's a first dev iteration this morning but tested on 2 dockerized instances : it works \o/

**Comment by henryxie2093** [comment]
”p2p features “ is peer to peer，in addition to topic

**Comment by andsel** [comment]
Ahh ok, you mean "queue" like feature. No they are not part of MQTT specification, so the broker doesn't implement.
 Andrea
