### ISSUE TITLE
mvn package error

### ISSUE THREAD

**Issue by gaomingyang21** [moquette-io/moquette#182]
moquette/broker/src/test/java/io/moquette/server/ServerIntegrationDBAuthenticatorTest.java:[51,79] cannot find symbol
[ERROR] symbol:   method prepareTestPropeties()
[ERROR] location: class io.moquette.server.IntegrationUtils
[ERROR] -> [Help 1]

affectedy by CRLF.

**Comment by mackristof** [comment]
fix by https://github.com/andsel/moquette/pull/179 but ssl test certificate failed in other test cause it was expired :(
