### ISSUE TITLE
ServerRestartIntegrationTest failling

### ISSUE THREAD

**Issue by Cycycysisisi** [moquette-io/moquette#183]
According to git the build should be ok but I have an error comming out during the tests, this does not seem to be only test related as when I skip the tests I have the error during execution.
Please find attached the files,
- the mvn clean package with debug
- the /broker/target/surefire-reports/io.moquette.server.ServerRestartIntegrationTest.txt
- moquette.doxx from the execution moquette.log

[MvnCleanPackageX.docx](https://github.com/andsel/moquette/files/289404/MvnCleanPackageX.docx)

[io.moquette.server.ServerRestartIntegrationTest.docx](https://github.com/andsel/moquette/files/289405/io.moquette.server.ServerRestartIntegrationTest.docx)

[moquette.docx](https://github.com/andsel/moquette/files/289403/moquette.docx)

**Comment by LakhanRathi92** [comment]
Hi 

I am facing same issue, did you find any way out yet? 

[io.moquette.server.ServerRestartIntegrationTest.txt](https://github.com/andsel/moquette/files/295880/io.moquette.server.ServerRestartIntegrationTest.txt)

**Comment by Cycycysisisi** [comment]
No not yet, I'm not quite sure what is happening, out of curiosity which version of java are you using ?

**Comment by LakhanRathi92** [comment]
I am using java 1.8.. Did you try with 1.7?

**Comment by LakhanRathi92** [comment]
It gave same errors with java 1.7, on windows 10. 

I also tried it with Ubuntu (java version 1.8) got one test failed out of 154. The test name was ServerIntegrationFuseTest.checkWillTestamentIsPublishedOnConnectionKill_noRetain:105 We should get notified with 'Will' Message....

and then tried 0.8 release version on ubuntu and it got stuck after a SERVER REBOOTING and a few lines...

**Comment by LakhanRathi92** [comment]
One more question, what error you got during execution? 

I just wanted to use broker, and I tried MQTT client chrome MQTTlens, the broker is running fine with java 1.7.  I was able to publish and subscribe, though 3 JUnit test (as expected) were still failing. But you can continue to work till someone figures out what is wrong with those ServerRestartIntegrationTest sub-tests...

**Comment by Cycycysisisi** [comment]
A null pointer exception see moquette.doc in the opening of the issue, the only pratical issue I found is when you publish on a certain topic and a client which is offline at the time comes back on line afterwards which sort of destroys the idea of mqtt

**Comment by windbender** [comment]
I'm seeing this problem as well. Actually I"m seeing in my real code.  it doesn't seem to cause obvious problems, but it's not like I'm running an MQTT acceptance test type thing.

the source is that this line:

```
    StoredMessage inflightMsg = m_sessionsStore.getInflightMessage(clientID, messageID);
```

returns with inflightMsg as null.

which then causes a problem later on when the topic is attempted to be extracted:

```
   inflightMsg.getTopic()
```

The exact reason why is less clear to me. I would guess that the clientID/messageID combination doesn't actually HAVE an inflight message (hence the null), but it's not clear why that would happen and then have a PUBACK come back.

(oh and java 8, running both OS X and linux ).

**Comment by andsel** [comment]
Hi @windbender and @Cycycysisisi  I've recently fixed the store/load of inflight messages, could you recheck if this issue is still valid with latest master?

**Comment by windbender** [comment]
I didn't have a 100% guaranteed way to make this happen.  But it was common after operation for a few minutes.  I pulled the latest code into my fork, built it, and I've been running with it for a bit.  So far, that NPE is gone.  

If I don't see it by EOD Monday, I think I'd be willing to declare it definitely gone.  I'll try to get back here to comment again either way.

**Comment by windbender** [comment]
I didn't observe the problem while working on my dev environment all day today.  This would never have previously happened.

**Comment by Cycycysisisi** [comment]
No problems on my side with the test which failled previously,everything is working fine. Your latest update seems to have solved the issue.

**Comment by windbender** [comment]
shall we close this ?

**Comment by andsel** [comment]
I think we can close it
