### ISSUE TITLE
API to send message to single client

### ISSUE THREAD

**Issue by iodb** [moquette-io/moquette#194]
I would like to use MQTT topics as dynamic alternative to REST resources. So instead of doing a HTTP GET-request to "http://myserver/path/to/resource", I connect to the server "mqtt://myserver", and subscribe to the topic "path/to/resource". For every change in the resource's state, a message is sent to this topic, allowing all subscribers to remain in sync.

However, this does not allow for a subscriber to receive the resource's current state at the moment of subscription. 

So what I'm looking for is a way to send a 'welcome to this topic, current state is ...' message to the subscribing client only.
Moquette already allows for an InterceptHandler to be registered for subscribe messages, and here one could implement the lookup of the 'current state of the resource'. But there is no way to return it to the client with the clientID given.

Potentially, ProtocolProcessor.internalPublish() could be extended or overloaded, passing in the clientID.

I'm perfectly willing to help with the implementation of this feature, but like some feedback whether such a feature would be accepted, and what would be the cleanest way to implement it.

**Comment by kevto** [comment]
Can't you resend the latest state of the resource again with a little extra
in the message payload stating its only meant for a specific subscriber and
drop it client side for those subscribers who are not new?

**Comment by iodb** [comment]
As I have potentially many clients, connecting over cellular, on devices with limited resources, I would consider this solution less than ideal. 
More so given that the 'latest state' can be quite large, which is the reason why I wanted to work with delta updates in the first place.

**Comment by andsel** [comment]
To present the client with a "state" on a topuc I would use publish with
retained true,I avoid to modify the semantic of MQTT protocol.
Andrea
Il giorno 09/ago/2016 11:44, "iodb" notifications@github.com ha scritto:

**Comment by iodb** [comment]
Every time my state updates, I can indeed create a new message with the entire state, and set retained to true. Newly subscribing clients will indeed get this message first (and not the previous retained message). After that they get all (non-retained) delta update messages. So far so good.
However, as far as I can tell, clients that were already subscribed wil get every new retained message with the full state as well, which again beats the purpose of having delta updates. 

I tried playing with different QoS types, and giving the retained messages the same messageID, but no success.

**Comment by kevto** [comment]
Just throwing some stuff in this think tank here. What if the client also
subscribes to a personal topic (like used for notifications) and send the
state of the resource topic in there? That way nobody else will receive
that enormous full state except for that one person and receive delta
updates through the resource topic later on.

**Comment by iodb** [comment]
Yep, that was my backup solution. The reason I didn't consider it ideal is because the client code becomes significantly more complex. It's not just subscribing to an additional 'personal' topic, but also when a message arrives on this topic, its messagehandler needs to determine for which resource topic the message was actually meant, and forward the message to the according messagehandler. All very doable, but I guess I was just hoping for something cleaner.

Andsel's remarks about retained messages gave me another idea: 2 topics, one for delta updates and one for full updates. The client subscribes to both, but after receiving the first retained message from the 'full' topic unsubscribes from it. Of course this would make the client no less complex.

**Comment by iodb** [comment]
Closing issue, as no acceptable broker-side solution for this use-case could be determined
