### ISSUE TITLE
m_persistentMessageStore.remove(clientID)

### ISSUE THREAD

**Issue by myqhit** [moquette-io/moquette#198]
m_persistentMessageStore.remove(clientID) in clientSession's method dropMessagesInSession, but I didn't find where you put object in m_persistentMessageStore by the clientId,can you help?

**Comment by andsel** [comment]
Look at the processPublish in the ProtocolProcessor

**Comment by myqhit** [comment]
reading the code ,I only find 
![image](https://cloud.githubusercontent.com/assets/2512795/17615361/5f51657e-60a0-11e6-9615-82b6679a7802.png)
 here put message in  the m_persistentMessageStore by the guid,the key is not clientId,can you indicate the specific code ?
