### ISSUE TITLE
subscribe(Subscription newSubscription)

### ISSUE THREAD

**Issue by myqhit** [moquette-io/moquette#199]
![image](https://cloud.githubusercontent.com/assets/2512795/17611780/b94b0a0e-607c-11e6-98f0-f27f04d4b000.png)

the newSubscription is a new object,you didn't put it in subscriptions before remove it,here maybe to remove existingSub?

**Comment by andsel** [comment]
It's a Set, before open questions please read carefully the code. Thank's a lot
