### ISSUE TITLE
config settings: allow system properties

### ISSUE THREAD

**Issue by maggu2810** [moquette-io/moquette#20]
Do you think it would be ok to use system properties for the values of the properties in the configuration file?
We could extend the parse method of the ConfigurationParser to replace system properties in the value (using: https://commons.apache.org/proper/commons-lang/javadocs/api-2.6/org/apache/commons/lang/text/StrSubstitutor.html).

If someone would configure the the moquette database path in the configuration file and does not want to use absolute path he could use e.g. the value "${moquette.path}/storage/moquette_store.mapdb"

**Comment by maggu2810** [comment]
I would create a pull request if it is okay for you and there are no requirements not using commons-lang of apache.

**Comment by andsel** [comment]
Hi @maggu2810,
personally I don't like to import a library just to do simple string substitution, the library is also old. As stated in the pull request #18 I don't like to have two ways to configure the same thing, having the system property and the config file as options to configure a feature of the broker could lead to troubles,"I've set the value but the broker take another".

**Comment by maggu2810** [comment]
> two ways to configure the same thing, having the system property and the config file as options to configure a feature of the broker could lead to troubles,"I've set the value but the broker take another".

This change does not introduce such a conflict, it allows just to use system properties in config file values.
How would you ship a OSGi based solution that is using your bundle if you do not know at which location the user is execution it.
How could we configure the database storage location in a relative way to the configuration file?

**Comment by andsel** [comment]
At the moment there is no way, but I expect that OSGi provide a way to pass in configuration to bundles or define some Configuration bundles that are essentially "configuration carrier services". OSGi it's a little bit difficult to me at the moment.

**Comment by andsel** [comment]
I've dropped the OSGi support because it's too complicated the guarantee a decent level of integration (pax-runner doesn't fit well) and it's time consuming for me to fix it against other libs, because Moquette bundle isn't simply not used I drop it
