### ISSUE TITLE
Allow port address/reuse within Netty.

### ISSUE THREAD

**Issue by kennywk** [moquette-io/moquette#206]
Perhaps an oversight, but i noticed that by default port reuse does not seem to be working. If you start the server and it crashes or something happens to the connection causing it to stop. When you start it again the port is still bound.

**Comment by ricardojlrufino** [comment]
Try add Shutdown Handler

``` java
            Runtime.getRuntime().addShutdownHook(new Thread() {
                @Override
                public void run() {
                    main.stop();
                }
            });`
```
