### ISSUE TITLE
Access underlying Connection/Channel in InterceptHandler

### ISSUE THREAD

**Issue by markusf** [moquette-io/moquette#211]
I think it would be helpful to provide a connection context in InterceptHandlers, which allows access to the underlying netty channel to get more low level information about the client.

**Comment by andsel** [comment]
This brack the encapsulation..so the answer is to avoud this.
Andrea
Il giorno 16/set/2016 02:00, "markusf" notifications@github.com ha
scritto:

**Comment by markusf** [comment]
Well, it might break the encapsulation, but it is up to the developer on whether and how to use it. An alternative would be providing a wrapper class / channel context, which allows access to only "non-dangerous" methods, which's access does not break the underlying lifecycle. Actually for my use case, I was only interested in the remoteAddress().
