### ISSUE TITLE
how I  statistical data such as linking number

### ISSUE THREAD

**Issue by FengXMGeek** [moquette-io/moquette#216]
give me a  idea?
how I  statistical data such as linking number?
from mapDB? or by aop?

**Comment by ricardojlrufino** [comment]
Looking at the source code, I found some classes that collect metrics.

BytesMetricsHandler
MessageMetricsHandler

But at first glance I did not think to pick them externally

**Comment by ricardojlrufino** [comment]
@andsel how a get this stats ?
