### ISSUE TITLE
[security] Clients connect to server without using user/pass

### ISSUE THREAD

**Issue by ricardojlrufino** [moquette-io/moquette#218]
Why I need to set the property "ALLOW ANONYMOUS PROPERTY_NAME" even by setting the authenticator?

I ended up taking time to identify the problem. This could be set to false when set an authenticator

**Comment by kevto** [comment]
There are certain use cases where you might want to allow anonymous user connections. By default it's been set to `true`. If you wish to disallow anonymous users, set `allow_anonymous` to `false` in your moquette configuration file.

This is well documented in [here](https://github.com/andsel/moquette/blob/master/broker/config/moquette.conf)

---

Edit: it's up to each implementation of MQTT v3.1.1 whether they allow anonymous users or not and whether that setting is set to `true` or `false` by default. 

Only thing that is defined in the MQTT's specification, is that if you set the user flag in the CONNECT packet to 1 (equals to true), then the payload must provide a username. However, that's client side configuration.

**Comment by ricardojlrufino** [comment]
Understand,
I just found it a bit strange this behavior.
Thank you for the explanation.
