### ISSUE TITLE
I think there are some defects

### ISSUE THREAD

**Issue by whipfeng** [moquette-io/moquette#22]
First of all, I English level is not very good, please forgive me!In the process I use the moquette, I think I found several problems.
In the org.eclipse.moquette.spi.impl.ProtocolProcessor class, there is a sentence:
If (m_clientIDs.get (clientId) = = null) {
Throw new RuntimeException (String.format ("Can't find a ConnectionDescriptor for client <%s> in cache <%s>", clientId, m_clientIDs));
}
This will cause the publisher obstruction.

Also, When broker announced the news to client, if client is persistent, suddenly closed the connection or throws an exception, this time is no receipt to broker has been receiving complete. Broker will never again release relevant information to the client.

**Comment by andsel** [comment]
Please, could you provide an unit test or an algorithm that manifest the problem. That exception is safe checkpoint, if the clientID is not present in the cache, it means that something bad happened, so in which case do you exposed this behaviour?

**Comment by whipfeng** [comment]
'could you provide an unit test or an algorithm that manifest the problem': because involve interaction with the client, so it is not easy to provide.
'if the clientID is not present in the cache, it means that something bad happened': clientID is not in the cache, that the subscriber has appeared problem (possibly subscribers process is active kill). This time should be stored subscriber message, but should not throw an exception blocked the publisher, Is it right??

**Comment by whipfeng** [comment]
My second question may not be described clearly. When the subscriber and publisher Qos is 2, and the news is persistent. The first step, the broker process is started, the publisher process starts and released ten messages. The second step, the subscriber process start and begin to receive messages (debug mode). When the receiving end fifth messages, forced the closure of the subscriber process. The third step, the subscriber process to restart and restart the receive message. This time has not received any news. That is to say, broker lost five messages behind the.

**Comment by andsel** [comment]
To test similar conditions, I usually write a groovy script that acts as a client launched against a fresh start of the broker.

**Comment by andsel** [comment]
Not reproducible
