### ISSUE TITLE
change location of moquette.conf in embedded mode

### ISSUE THREAD

**Issue by paulmiu** [moquette-io/moquette#223]
Is it possible to store the `moquette.conf` in another location than `"config/moquette.conf"`?

I'm using this example: [EmbeddedLauncher.java](https://github.com/andsel/moquette/blob/5efad350d8c73071823e839daf56667d5847f935/embedding_moquette/src/main/java/io/moquette/testembedded/EmbeddedLauncher.java)

**Comment by andsel** [comment]
Moquette in its release package uses that file path (it's hardcoded) but
for embedded moquette you could give a look at subsclasses of IConfig
(ClasspathConfig, MemoryConfig and FilesystemConfig)

 Andrea

**Comment by paulmiu** [comment]
Thanks! I'll try that.
