### ISSUE TITLE
Error: Could not find or load main class Server

### ISSUE THREAD

**Issue by GeorgeMatveev** [moquette-io/moquette#226]
Hi,
when I run my custom moquette code from IDE (Eclipse or IDEA) it works fine (after removing mapdb files). But when I try to run _the same code_ from command line (for production server) using _same class path_ and same set of libraries, I got following error:

Error: Could not find or load main class Server

My shell script that runs broker is here:

export mql='../mqtt-libs'
echo 'jars libs in:' $mql/*.jar

java Server -cp $bin -Dfile.encoding=UTF-8 -verbose:class

MQTT/etc libraries are currently removed from the script for debugging.
All compiled class files are in bin/io/... including Server.class.

My CLASSPATH begins with

$ echo $CLASSPATH 
.:/opt/jdk1.7.0_79/db/lib/derby.jar:.:/opt/jdk1.7.0_79/lib/tools.jar:/home/gm/soft/mongodb/mongo-java-driver-2.11.4.jar:/home/gm/soft/mysql/mysql-java-5.1/mysql-connector-java-5.1.39-bin.jar:...

Any idea what is wrong?

Best regards,
GM

**Comment by andsel** [comment]
Hi,
this is not a fail on Moquette, but I can see in your sh file java Server
... you have to put full class name, for example:
java io.moquette.server.Server -cp ...

Take a look at Moquette's distribution launch script (
https://github.com/andsel/moquette/blob/master/distribution/src/main/scripts/moquette.sh
)

 Andrea
