### ISSUE TITLE
how to copy/save message data?

### ISSUE THREAD

**Issue by GeorgeMatveev** [moquette-io/moquette#230]
Hi,
I am trying to save message data for future parsing/analysis using FileChannel (fc) and temp file
and can see that ByteBuffer is allocated ok, but all data in that temp file is ZEROS:

   copyMqtt(mess): mess.len: 20
+ CopyMqtt(mess): fc.pos1()=0
+ CopyMqtt(mess): bytesread=20
+ CopyMqtt(mess): fc.pos2()=20
+ mcopy.length=20
00000000000000000000
+ bacopy: =[B@54ba904b  //byte []
+ copyMqtt(mess): mess.len: 20
+ CopyMqtt(mess): fc.pos1()=0
+ CopyMqtt(mess): bytesread=20
+ CopyMqtt(mess): fc.pos2()=20
+ mcopy.length=20
00000000000000000000
+ bacopy: =[B@11b814b8 //byte [] with data

Tried using new String (byte [], charset) with different char sets but result is still the same: all zeros.
Anyone knows how to save message data in String?

All ideas are appreciated!

Br,
George Matveev

**Comment by andsel** [comment]
Sorry George, but I can't understand your question.You have to copy data
inside Moquette's protocol handling?
Andrea
Il giorno 31/ott/2016 15:06, "George Matveev" notifications@github.com ha
scritto:

**Comment by GeorgeMatveev** [comment]
Hi Andrea, will try to clarify:

I'd like to spare copy of message for future parsing/analysis (e.g. via SQL server).

And I've tried using ByteBuffer->FileChannel->String(byte []) mechanism.
But result is somewhat strange:
- copyMqtt(mess): fc.pos1()=0
- copyMqtt(mess): bytesread=20
  byte[0]=0
  byte[1]=0
  byte[2]=0
  byte[3]=0
  byte[4]=0
  byte[5]=0
  byte[6]=0
  byte[7]=0
  byte[8]=0
  byte[9]=0
  byte[10]=0
  byte[11]=0
  byte[12]=0
  byte[13]=0
  byte[14]=0
  byte[15]=0
  byte[16]=0
  byte[17]=0
  byte[18]=0
  byte[19]=0
- copyMqtt(mess): fc.pos2()=20
- Arrays.toString(bacopy)=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  00000000000000000000
- bacopy: =[B@4d6385fe
- copyMqt: =

ByteArray (bacopy) of message appears to contain only ZEROs after I allocated Direct ByteBuffer
and got (seemingly) all message data into it via this code:

```
      bbcopy = ByteBuffer.allocateDirect(mess.getRemainingLength());
      bbcopy.clear();//clear garbage

      //1 read from FileChannel into ByteBuffer
      int bytesread = fc.read(bbcopy);
      System.out.println("+ copyMqtt(mess): bytesread="+bytesread);//OK

      //2 write all message bytes into ByteBuffer copy/console
      for(int i=0; i<bytesread; i++)
      {
         fc.write(bbcopy);
         byte b = bbcopy.get(i);
         //lets see what's inside???
         System.out.println("byte["+i+"]="+b);//ZEROs
         //Nothing! with getChar(i)/getInt(i)
         //"java.nio.HeapByteBuffer[pos=20 lim=20 cap=20]" with bbcopy
      }
```

But as you see from printout above it contains only ZEROs.
So the question remains: how to read/copy message data into String?

Any help would be very much appreciated.

Best regards,
GM

**Comment by GeorgeMatveev** [comment]
One more thing:

When I send file via broker, contents of the file (e.g. runBroker.sh script)
are _correctly_ displayed on console where I subscribed to the topic (via mosquitto_sub -h localhost),
but in the underlying file used by FileChannel (for read/write) 
and in my program/IDE message content appears as ZEROs. VERY Mysterious!

Any clue?

Br,
GM

**Comment by GeorgeMatveev** [comment]
Actually ALL symbols in that FileChannel underlying file are "^@"!
What could possibly mean?

**Comment by GeorgeMatveev** [comment]
Hi,
actually the problem seems to be even deeper:
When I try to get message payload length I am not getting anything at all!

```
    ByteBuffer payload = mess.getPayload();
    byte [] mba = payload.array();//get message data
    int meslen = mba.length;//data length
    System.out.println("*\n copyMqtt: meslen="+meslen);//Nothing
```

How is this API supposed to work???
Please reply.

/GM

**Comment by andsel** [comment]
Hi George
you are speaking about JDK's api and Netty's, Moquette use that but I can
only provide support on Moquette API's, that's not part of this project.
Your question seems related to use of copy data from Netty's API, you could
give a look at Netty's docs.

 Andrea

**Comment by GeorgeMatveev** [comment]
Here is how it supposed to work:

```
    //This code WORKS fine!
    byte [] ba = new byte [] {'G','e','o','r','g','e'};
    ByteBuffer bb = ByteBuffer.wrap(ba);
    msg.setPayload(bb);
```

Later I write it via FileChannel to disk, and here's correct result:

$ cat mqtmessage.dat 
George

And the whole program (i.e. my own code) works fine!

But code that comes standard with Moquette:

```
    //copyMqt = new String(msg.getPayload().array());//NOP
    //copyMqt = new String(msg.getPayload().array());//NOP
```

does NOT work at all!

The problem is in getPayload() method!

And it seems that was the reason you removed it from original version of Moquette:

https://github.com/andsel/moquette/commit/fedd2965ccf100e8fd8acc3684899593db3fafb8

Who would be the right person to fix this bug? Any ideas/estimations how/what is to be done?
It is MAJOR blocking issue in the whole project, imho.

Br,
GM

**Comment by andsel** [comment]
Sorry @GeorgeMatveev but I continue to don't understand what you  mean.
Are you creating an interceptor inside Moquette to store data on anther storage, and you are telling me that on the interceptor the payload you read is empty or byte[] full of zeros?
It's a little bit difficult to understand which is your test case, in case if you find a discrepancy in Moquette write a unit/integration test to make evident the problem.
Thanks 
   Andrea

**Comment by GeorgeMatveev** [comment]
Hi Andrea,
it is actually hard to understand how else I can clarify the problem
I have with msg.getPayload().array() methods...

Why did you remove those lines with msg.getPayload().array() code from HazelcastInterceptHandler.java ???
-        LOG.info(String.format("%s publish on %s message : %s\n", msg.getClientID(), msg.getTopicName(), new String(msg.getPayload().array())));
-        LOG.info("{} publish on {} message: {}", msg.getClientID(), msg.getTopicName(), new String(msg.getPayload().array()));
       ITopic<HazelcastMsg> topic = hz.getTopic("moquette");
-        HazelcastMsg hazelcastMsg = new HazelcastMsg(msg.getClientID(),msg.getTopicName(), msg.getQos().byteValue(), msg.getPayload().array(), msg.getUsername());
-        HazelcastMsg hazelcastMsg = new HazelcastMsg(msg.getClientID(), msg.getTopicName(), msg.getQos().byteValue(),
-                msg.getPayload().array(), msg.getUsername());

here is the commit YOU made on 22 July: 

https://github.com/andsel/moquette/commit/fedd2965ccf100e8fd8acc3684899593db3fafb8

---

Also if you try to print out results from spi/impl/ProtocolProcessor.java

private static IMessagesStore.StoredMessage asStoredMessage(PublishMessage msg) {
        System.out.println("\n\* GM ProtProc: msg.QoS="+msg.getQos()+ ", topic="+msg.getTopicName());//
        System.out.println("\* GM ProtProc: msg.isRetaineFlag="+msg.isRetainFlag());//NOP
        System.out.println("\* GM ProtProc: msg.payload.array="+msg.getPayload().array());//NOP

You will see nothing on console/IDE.
At least it does NOT work for me.

Can you try it yourself?
This is very simple test/use case!

Cheers,
GM
