### ISSUE TITLE
Fix comment on password_file.conf

### ISSUE THREAD

**Issue by amartens1** [moquette-io/moquette#238]
The password_file.conf file states on line 5
`#NB this password is sha256(passwd)`
However, the hash corresponds to 'passWd' instead (uppercase W)
Thanks

**Comment by andsel** [comment]
Hi,
in which file precisely?
'echo -n "passWd" | sha256sum' is 5219a552abb6f403bbf52d55578f1fbe02d0912af0776162e7517699df3e0138 , and grepping on sources doesn't give me any result.

I find always 0d6be69b264717f2dd33652e212b173104b4a647b7c11ae72e9885f11cd312fb  that's the result of 'echo -n "passwd" | sha256sum'

**Comment by amartens1** [comment]
Hi Andrea,

I read that in a password_file.conf comment.

BR
---
A.Martens (iPhone)

**Comment by andsel** [comment]
Hi
https://github.com/andsel/moquette/blob/master/broker/config/password_file.conf

has this sha 0d6be69b264717f2dd33652e212b173104b4a647b7c11ae72e9885f11cd312fb which is the sha256 of "passwd"

**Comment by amartens1** [comment]
Hello again,

Sorry - you're right for GitHub

However, I found the hash 36767030e79073783c8e9b299d9f8f1d4cd66baa82cd8869caad8dbb55204099 in the password_file.conf inside the distribution-0.9-SNAPSHOT-bundle-tar.tar.gz resulting from the compilation. Is it the same for you?

Cheers,
---
A.Martens (iPhone)

**Comment by amartens1** [comment]
Hi,

https://github.com/andsel/moquette/blob/master/distribution/src/main/resources/password_file.conf

Has sha 3676...4099 which is the sha256 of "passwd\n" I think

This time yes, hope this helps :)

(Thanks for moquette, is a great software)

Yours,
---
A.Martens (iPhone)

**Comment by andsel** [comment]
Good catch @amartens1 , fixed!

 Thanks
    Andrea
