### ISSUE TITLE
Cannot custom the message store

### ISSUE THREAD

**Issue by beihaifeiwu** [moquette-io/moquette#24]
import org.dna.mqtt.moquette.messaging.spi.IMatchingCondition;
import org.dna.mqtt.moquette.messaging.spi.impl.HawtDBPersistentStore.StoredMessage;
import org.dna.mqtt.moquette.messaging.spi.impl.events.PublishEvent;
import org.dna.mqtt.moquette.proto.messages.AbstractMessage.QOSType;

public interface IMessagesStore {
    void initStore();

```
void storeRetained(String var1, ByteBuffer var2, QOSType var3);

Collection<StoredMessage> searchMatching(IMatchingCondition var1);
```

StoredMessage is protected cannot be accessed by others

**Comment by andsel** [comment]
Hi,
probably the version of code you are looking at is outdated, in the current master (https://github.com/andsel/moquette/blob/master/broker/src/main/java/org/eclipse/moquette/spi/IMessagesStore.java) that interface also carries a static public inner  StoredMessage class

**Comment by beihaifeiwu** [comment]
Hi，okay，I have seen the new version interface，but I am using your library as a maven dependency to provide mqtt support for my project, How can I get the newest version ? snapshop is also ok.

**Comment by andsel** [comment]
At the moment there isn't any snapshot repo that hosts Moquette's snapshot. You should download on you pc a do mvn clean install. Then you could use in your project.
