### ISSUE TITLE
Next release / State of latest version

### ISSUE THREAD

**Issue by magnus-lutz** [moquette-io/moquette#241]
Hello, I need the feature to directly send messages to specific clients, or respectively setting the clientId in a PublishMessage. We are using the 0.8.1 version provided by your bintray repository via maven, as its quite hard for us to have all our developers install moquette to their local maven repository by themselves, as we have no central one. Could you please deploy a more recent version of moquette to that repository or is the latest version not ready to be used productively right now?

Regards,
Magnus

**Comment by andsel** [comment]
Hi Magnus

On Tue, Dec 13, 2016 at 10:43 AM, Magnus Lutz <notifications@github.com>
wrote:

> Hello, I need the feature to directly send messages to specific clients,
>
This is not clear to me, I suppose you mean that from an embedded broker
instance you want to publish only to a certain clientid? This is outside of
the MQTT semantics, probably your destination client should be subscribed
to a topic in the form of /<destination_client_id> and the others, who want
to message with him, should publish on that topic (like a sort of inbox).-


> or respectively setting the clientId in a PublishMessage. We are using the
> 0.8.1 version provided by your bintray repository via maven, as its quite
> hard for us to have all our developers install moquette to their local
> maven repository by themselves, as we have no central one.
>
For this it's sufficient that you install a local are repo service, like
Artifactory that could host snapshots and your devs could download from
that, at the moment I don't have a snapshot repo.


> Could you please deploy a more recent version of moquette to that
> repository or is the latest version not ready to be used productively right
> now?
>
Releases are done only when features are developed, at moment I'm trying to
fix a bunch of issue related to  concurrency problems, and then I'll
release the 0.9 or perhaps directly 1.0

> Regards,
> Magnus
>
Bests

 Andrea
