### ISSUE TITLE
moquette store - necessary?

### ISSUE THREAD

**Issue by neilyoung** [moquette-io/moquette#257]
Hi,

I had some trouble deploying the moquette.conf with my package, so I create the configuration in memory 

`            Properties configProps = new Properties();

            configProps.put("port", Integer.toString(1883));
            configProps.put("host", "0.0.0.0");
            configProps.put("allow_anonymous", Boolean.valueOf(true));

            MemoryConfig config = new MemoryConfig(configProps);
            final io.moquette.server.Server mqttBroker = new io.moquette.server.Server();
            final List<? extends InterceptHandler> userHandlers = Arrays.asList(new PublisherListener());
            mqttBroker.startServer(config, userHandlers);
`

After some days I found three growing files on disk:

moquette_store.mapdb
moquette_store.mapdb.p
moquette_store.mapdb.t

I suppose, if I would have used the conf those wouldn't have been created, because the appropriate section is commented in default config. How can I disable the creation of the moquette_store files programmatically?

TIA

**Comment by andsel** [comment]
Are you using version 0.9? In 0.9 if don't specify the path for the store
it use only memory, else it's a bug.
Which version are you using?

 Andrea

**Comment by neilyoung** [comment]
I'm using 0.8

**Comment by andsel** [comment]
To make what you desire you should use 0.9, with 0.8 you can't

 Andrea

**Comment by neilyoung** [comment]
Are there any other dependencies which need to be upgraded?

**Comment by neilyoung** [comment]
Where can I download a binary distribution of 0.9? The BinTray package seems to be 0.8

**Comment by andsel** [comment]
Maven Jcenter:
https://jcenter.bintray.com/io/moquette/

Or the overlall package:
https://bintray.com/artifact/download/andsel/generic/distribution-0.9-bundle-tar.tar.gz

**Comment by neilyoung** [comment]
Oh boy, there are a lot of breaking changes...
