### ISSUE TITLE
directSend-only mode

### ISSUE THREAD

**Issue by magnus-lutz** [moquette-io/moquette#258]
We need to have the ability to intercept all incoming publishes from clients and process the message contents, while still telling the client that the publish succeeded. At the same time, no subscriber shall be notified that a publish on its subscribed channel happened. Only direct messages from server to a specific client (we know all possible clients and their ids) shall be allowed, which is done by setClientId on a PublishMessage, if i am not wrong

Does such a feature for disabling the automatic delivery to subscribers on publish already exist or is it planned?

I know that this is quite contrary to the idea of mqtt or a publish/subscriber pattern, but we have something like groups of clients which must not receive data from topics where a client from another group published to. Having another topic-space/topic-prefix is not an option though and they will also be running on the same server instance.

**Comment by andsel** [comment]
Hi @magnus-lutz this sound me a little strange,having such a feature inside the broker could potentially broke the MQTT protocol specification. Your request sounds like you have to do an integration (in terms of integration-patterns) or I'm wrong?
 We can discuss about it.
