### ISSUE TITLE
Could not resolve dependencies

### ISSUE THREAD

**Issue by lawas2008** [moquette-io/moquette#266]
hi，
Moquette - Parser Commons .......................... SUCCESS [  1.314 s]
[INFO] Moquette - MINA Parser ............................. SUCCESS [  1.377 s]
[INFO] Moquette - Netty Parser ............................ FAILURE [  0.012 s]
[INFO] Moquette - broker .................................. SKIPPED
[INFO] Moquette - Benchmarking tool ....................... SKIPPED
[INFO] Moquette MQTT library .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.799 s
[INFO] Finished at: 2017-02-09T17:07:16+08:00
[INFO] Final Memory: 17M/170M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project moquette-netty-parser: Could not resolve dependencies for project org.dna.mqtt:moquette-netty-parser:jar:0.3: Failure to find org.dna.mqtt:moquette-parser-commons:jar:0.2 in http://maven.aliyun.com/nexus/content/repositories/central/ was cached in the local repository, resolution will not be reattempted until the update interval of alimaven has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:

can you help me? thanks!

**Comment by andsel** [comment]
Do you use the last github version? From your logs seems you are using 0.2 "
org.dna.mqtt:moquette-parser-commons:jar:0.2" i switched from org.dna to
io.moquette more than a year ago.

**Comment by lawas2008** [comment]
OK，I try again,thank you.

**Comment by lawas2008** [comment]
it's ok, but, can I  do maven-built moquette-parent only,and then can I delete other maven modle from project?can I build .jar and add to my project to use.

**Comment by andsel** [comment]
with maven you can install it on your local .m2 repository or use a public version, as described in  in the "Embedding in other projects" paragraph.
