### ISSUE TITLE
Memory issues in android

### ISSUE THREAD

**Issue by Mathris-Ranga** [moquette-io/moquette#272]
Hi,
I have integrated the latest version (0.9) with my android app and i am able to start the server. I ran into memory issues after few messages sent from client. I suspect it could be due to memory db. In my case i would like to store only the client sessions and not the messages(m_persistentMessageStore map). Is there a way that storing of message can be avoided?  Is the broker compatible with android?  I see another repository created for android but the last update was done couple of years ago. Please do confirm. Thanks.
https://github.com/technocreatives/moquette

**Comment by andsel** [comment]
Hi @Mathris-Ranga 
Moquette broker doesn't support officially the Android platform, I know there are some fork of come devs, but I dont' know if they works or not.
You should configure the broker to store on the FS, but I don't know if MapDB (the library used for persistence) is supported by Android
