### ISSUE TITLE
expire old sessions ?

### ISSUE THREAD

**Issue by windbender** [moquette-io/moquette#275]
If I have a client which has connected to a broker, and then that client has subscribed to some number of topics, and then that client is disconnected.   It seems as though the broker must maintain knowledge of those subscriptions.  If that client then NEVER reconnected to the broker,  do we essentially have a memory leak with this the sessions store ?

Does it make sense to provide an optional expiration for sessions such that old sessions would get cleaned up after their expiration ?

Does anyone have a reasonable approach to solving this problem ?

**Comment by andsel** [comment]
On Fri, Feb 24, 2017 at 10:23 PM, windbender <notifications@github.com>
wrote:

> If I have a client which has connected to a broker, and then that client
> has subscribed to some number of topics, and then that client is
> disconnected. It seems as though the broker must maintain knowledge of
> those subscriptions. If that client then NEVER reconnected to the broker,
> do we essentially have a memory leak with this the sessions store ?
>
Yes there is a leak


> Does it make sense to provide an optional expiration for sessions such
> that old sessions would get cleaned up after their expiration ?
>
Yes, I was thinking for provide or a clean utility, or a TTL for sessions.
If I'm correct, MQTT v5 should have a TTL in the sessions


> Does anyone have a reasonable approach to solving this problem ?
>

The TTL read from configuration file seems the more viable.
