### ISSUE TITLE
Max payload size

### ISSUE THREAD

**Issue by arunkpatra** [moquette-io/moquette#276]
Could you please let me know what's the max payload size of the messages that MQTT clients(I'm using Paho) can send to a Moquette broker?

**Comment by andsel** [comment]
The defined by MQTT specs (256Mb)

**Comment by duchengle** [comment]
I uses JMeter Mqtt sampler to test pub/sub, pub sampler's payload is configured with fixed length string, when length of string is larger than 8079, broker throws exception "Unknown packet" in MQTTMessageLogger.
BTW, I'm using release 0.12.
May it be with configuration issue?
And the number 8079 is werid.
