### ISSUE TITLE
testClientSubscribeAfterRetainedQoS0IsSent may be in error

### ISSUE THREAD

**Issue by windbender** [moquette-io/moquette#284]
I believe testClientSubscribeAfterRetainedQoS0IsSent is in error.

a message sent with QOS=0 and retain=true  SHOULD be delivered to a client which subscribes after the publish is sent.

**Comment by windbender** [comment]
From the 3.1.1  spec:

"It SHOULD store the new QoS 0 message as the new retained message for that topic, but MAY choose to discard it at any time - if this happens there will be no retained
message for that topic"

So technically moquette is exercising the "may" option and discarding it ?

Previously I had been publishing QOS=1, and this was saving too many unneeded messages and basically bloating the persistence database.  But after downshifting to QOS=0, I'm finding the messages simply dropped.  I would prefer if these message were stored.  

In the language of the RFC:  https://www.ietf.org/rfc/rfc2119.txt

SHOULD is listed more strongly than MAY.

**Comment by windbender** [comment]
IN looking at the relevant code  (ProtocolProcessor.java ~  530) :

```
    if (!msg.isRetainFlag()) {

       return;
    }
    if (qos == AbstractMessage.QOSType.MOST_ONE || !msg.getPayload().hasRemaining()) {
            //QoS == 0 && retain => clean old retained
            m_messagesStore.cleanRetained(topic);
            return;
        }
        if (guid == null) {
            //before wasn't stored
            guid = m_messagesStore.storePublishForFuture(toStoreMsg);
        }
        m_messagesStore.storeRetained(topic, guid);
```


It seems that the code is indeed not retaining any QOS=0 messages. In addition, it appear that the code is only clearing the retained message in the case of a QOS=0 message and length==0.  Where as the spec doesn't talk of QOS=0 as being a relevant condition in order to clear the retained messages.

I would suggest removing the 
`qos == AbstractMessage.QOSType.MOST_ONE ||
`
As a possible fix to both the QOS=0 not being retained as well as the inability to clear retained messages utilizing a higher QOS message.

**Comment by andsel** [comment]
Hi @windbender the broker clean retained messages because it receives a message of length==0, as expressed by specs:

[MQTT-3.3.1-10] "A PUBLISH Packet with a RETAIN flag set to 1 and a payload containing zero bytes will be processed as normal by the Server and sent to Clients with a subscription matching the topic name. Additionally any existing retained message with the same topic name MUST be removed and any future subscribers for the topic will not receive a retained message."

The broker should store only Q0S1 and QoS2 messages on clean session after disconnection

[MQTT-3.1.2-5]
"After the disconnection of a Session that had CleanSession set to 0, the Server MUST store further QoS 1 and QoS 2 messages that match any subscriptions that the client had at the time of disconnection as part of the Session state."

Do you see any discrepancies between specs and implementation?

**Comment by windbender** [comment]
MQTT-3.3.1-7 says "If the Server receives a QoS 0 message with the RETAIN flag set to 1 it MUST discard any message previously retained for that topic. It SHOULD store the new QoS 0 message as the new retained message for that topic, but MAY choose to discard it at any time - if this happens there will be no retained message for that topic."

The wording using "SHOULD" invokes the following from RFC2119:  "SHOULD   This word, or the adjective "RECOMMENDED", mean that there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications must be understood and carefully weighed before choosing a different course."

It's not clear to me what the "valid reasons in particular circumstances"  might be to ignore this. 

In my particular case, the only way moquette will retain message is if QOS=1 or QOS=2, but these end up storing ALL the messages.  This is not a healthy solution because all messages is a blatant memory leak, where as only the most recent message has a hard upper limit.  I would strong prefer following the "SHOULD"

**Comment by windbender** [comment]
I'd like to add that I found this issue on an older version of moquette (pre-Netty-Codec).  Sorry I didn't realize so much great work had gone on.  That's the risk I have with my own fork!

Believe a similar issue exist in the newer implementation within:  Qos0PublishHandler.receivedPublishQos0()
