### ISSUE TITLE
Bridge support

### ISSUE THREAD

**Issue by huyi0912** [moquette-io/moquette#285]
Hi!
Just new to mqtt. Our requirement is an hierarchical mqtt servers with capability to do bidirectional  message replication reliably.
Lowest part is moquette on mobile device(android,iOS using robovm).
Upper layer be other mqtt server.  Currently there is no bridge support in moquette.
Wondering is there any timeline for this or any drop in component to support this?
Or should I code my own bridge? Using InterceptHandler?

**Comment by andsel** [comment]
Hi @huyi0912 at the moment Moquette has not bridge or HA configuration. I plan to have some form of cluster, mainly for high availability reasons.
But which is reason to install a broker inside a mobile device, I ask because your are not the first person ask for and I would like to understand better. I always supposed that the mobile device shuould use an MQTT client that publish to a broker.

 Thanks
   Andrea

**Comment by huyi0912** [comment]
In fact,the requirement is database replication which is not that available(or costly) in mobile device. Especially when unstable connection is involved. Think about the requirement of POS system which need independent operation capability but from time to time to update(download) products price and report(upload) sales statistic.Using messaging to replicate database have been done by IBM long time ago.
Also,have MQTT server as an smart communication node plus full sql database(like H2)  and libGDX(for UI).
developer can using one skill to develop software run in different environment(android,ios,web).

**Comment by andsel** [comment]
I understand, but instead of a broker is sufficient to have an MQTT client that's connected to a broker (or connect on a timely fashion) to push reports and pull price updates, I think but I've never be in the POS and sales fields.

**Comment by huyi0912** [comment]
Another thought,maybe moquette can be more focused on mobile device which is the area doesn't have much competitors.And extends to two directions,one is upward which is function like bridge to connect to bigger named broker.Another is downward to act as an collector or gateway for lower resourced devices or sensors.

**Comment by andsel** [comment]
Probably you are right but supporting desktop and Android cost a lot of effort, and Moquette is my spare time project. Having officially on Android, could be a great thing, I also share your vision. Moquette as broker able to run on small devices (like a cluster of RPi) and Android, doing some minimal data processing before forward publish to a cloud service.
