### ISSUE TITLE
Cannot embed Moquette into other projects

### ISSUE THREAD

**Issue by Ruckley** [moquette-io/moquette#291]
Following the instructions on the read me leads to the maven error:
[ERROR] Failed to execute goal on project *myProject*: Could not resolve dependencies for project *myProject*: Could not find artifact io.moquette:moquette-broker:jar:0.10-SNAPSHOT in bintray (https://jcenter.bintray.com) -> [Help 1]

**Comment by andsel** [comment]
Moquette 0.10 is the current development master so it's not released in
JCenter. You should install it in your local Maven repo, mv clean install
from master.

 Andrea

**Comment by Ruckley** [comment]
Yes, I ended up using 0.9 as I need a stable build and preferably one on an online repository. It may be worth adding instructions on how to do this on the ReadMe as it took me quite a while to figure out where it was and how to get it working (I'm new to maven). Also, just out of interest, would you mind me asking why you have put the relseases up on JCenter rather than the maven repository? Thank you.

Im sure you know how but just for anyone else who needs it I got it working you place this in your maven settings.xml file:

```
<repositories>
				<repository>
					<id>bintray</id>
					<url>https://jcenter.bintray.com</url>
					<releases>
					  <enabled>true</enabled>
					</releases>
					<snapshots>
					  <enabled>true</enabled>
					</snapshots>
				</repository>
 </repositories>
```

and this in your pom.xml file:

```
<dependency>
              <groupId>io.moquette</groupId>
              <artifactId>moquette-broker</artifactId>
              <version>0.9</version>
</dependency>
```

**Comment by andsel** [comment]
Thanks for the hint, I'm planning to rework all the documentation.
The main page of the project explain hot to integrate maven repo and use embedded moquette:
https://github.com/andsel/moquette#embedding-in-other-projects
I've preferred JCenter because it's more easy to use than central repo, see issue #61
