### ISSUE TITLE
LEAK: ByteBuf.release() was not called before it's garbage-collected

### ISSUE THREAD

**Issue by windbender** [moquette-io/moquette#292]
Just had a concerning thing pop up in my log

Folks, keep your eye out for the following to reproduce.

ERROR  [18:33:49.560] [nioEventLoopGroup-3-2] i.n.u.ResourceLeakDetector -  LEAK: ByteBuf.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-Dio.netty.leakDetection.level=advanced' or call ResourceLeakDetector.setLevel() See http://netty.io/wiki/reference-counted-objects.html for more information.

**Comment by leesangboo** [comment]
My log too.

**Comment by leesangboo** [comment]
An unexpected exception was caught while processing MQTT message. Closing Netty channel. MqttClientId = null, cause = null, errorMessage = failed to allocate 16777216 byte(s) of direct memory (used: 4278190087, max: 4294967296).

**Comment by sawyer7246** [comment]
may be this explains why my application throws a 'out of heap memory exception' after running for several hours?
