### ISSUE TITLE
Session storage grows infinitely  

### ISSUE THREAD

**Issue by jaroslawherod** [moquette-io/moquette#305]
We are using moquette version 0.8.1 and our mapdb session storage files constantly grows. 
As far as I notice it happens only when messages are published with QoS level 1 & 2.

Is this is the source of issue #200 and it was fixed in release 0.9 ?

**Comment by andsel** [comment]
Yes it's the same, try version 0.9

 Andrea

**Comment by jaroslawherod** [comment]
Thanks for quick answer :+1:
