### ISSUE TITLE
performance improvement searching retained messages

### ISSUE THREAD

**Issue by windbender** [moquette-io/moquette#308]
Correct me if I'm wrong, but it seems like there is a solid performance win to moving the condition statement to before the two previous lines since the only input to the conditional comes from the outer loop, and not the output of the two previous lines.  Am I missing something here ?

MapDBMessagesStore.java:64

```
        for (Map.Entry<Topic, MessageGUID> entry : m_retainedStore.entrySet()) {
            final MessageGUID guid = entry.getValue();
            StoredMessage storedMsg = m_persistentMessageStore.get(guid);
            if (condition.match(entry.getKey())) {
                results.add(storedMsg);
            }
        }
```

Could be changed to:

```
        for (Map.Entry<Topic, MessageGUID> entry : m_retainedStore.entrySet()) {
            if (condition.match(entry.getKey())) {
                final MessageGUID guid = entry.getValue();
                StoredMessage storedMsg = m_persistentMessageStore.get(guid);
                results.add(storedMsg);
            }
        }

```

**Comment by andsel** [comment]
You are right! The code outside the if could be moved inside,without nudgin
the store for every topic,but only for the ones that match.
Good catch!!
Il giorno 15/mag/2017 23:20, "windbender" <notifications@github.com> ha
scritto:

**Comment by windbender** [comment]
I think there is the same issue in the new MemoryMessageStore.

**Comment by andsel** [comment]
It's the same. I'm introducing H2 as default storage and I've seen that the
Session Storage is become a little monster. I'll plan to polish it.
