### ISSUE TITLE
Clustering Possibility?

### ISSUE THREAD

**Issue by sjpark9** [moquette-io/moquette#31]
Hi
I'm not sure if it is okay to leave a question in this Issue page, but here it goes.

I am wondering if moquette is available to be clustered. 

Thank you. Apologies if questions weren't appropriate in this board

**Comment by andsel** [comment]
Hi,
probably the best place is the google group. The answer to your question is no at moment. One of future developments is to get Moquette in a HighAvailabilty stage, then should come naturally a develpment on clustering.

**Comment by sjpark9** [comment]
Thank you
