### ISSUE TITLE
SubscriptionsStore.java uses an optimistic concurrency system which performs very poorly under concurrent write load

### ISSUE THREAD

**Issue by windbender** [moquette-io/moquette#317]
I placed the following code with the add() method, and ran the system with high concurrent SUBCRIBE messages.
```
            int redoCount = 0;
            do {
                oldRoot = subscriptions.get();
                couple = recreatePath(newSubscription.topicFilter, oldRoot);
                couple.createdNode.addSubscription(newSubscription); //createdNode could be null?
                couple.root.recalculateSubscriptionsSize();
                //spin lock repeating till we can, swap root, if can't swap just re-do the operation
                redoCount++;
            } while (!subscriptions.compareAndSet(oldRoot, couple.root));
            LOG.debug("A subscription has been added. Root = {}, oldRoot = {}.", couple.root, oldRoot);
            if (redoCount > 2) {
                LOG.warn("we redid the add {} times", redoCount);
            }
```
I found that redoCount would sometimes be as high as 
```
WARN   [01:18:41.769] [nioEventLoopGroup-3-87] i.m.s.i.s.SubscriptionsStore -  we redid the add 129 times
```

So essentially we computed all the stuff within the do{}while 129 times in this case, but threw away 128 of them.  YUCK.

a quick hack fix is to used a synchronized all write operations to prevent concurrent modification. This dropped some of my subscribe times to less than 1/4 of what they had been.

I will see if I can build a more appropriate system based on java.util.concurrent stuff.

**Comment by andsel** [comment]
I used that trick,the swap of root node checking the version to use a lock
free access on writes without suffer of lock queues,this is used usually in
persistent data structures. The assumption is that dropping cpu work cost
less than wait on lock queue. What do you measure?
Il giorno 20/mag/2017 05:07, "windbender" <notifications@github.com> ha
scritto:

**Comment by windbender** [comment]
I have particular use case where I'm doing perhaps 6000 subscriptions over a short period of time into a data structure which already has more than 10000.  Many of those SUBSCRIBE messages are arriving and start computing in SubscriptionsStore at the same time.  What I observed after adding the counter above was that the dropping CPU work was actually very expensive due to the number of times this occurred.    Perhaps my use case is off in a weird corner and not typical, but it seems like Moquette should handle this as well.  I'm working on solving this problem.  Stay tuned.

**Comment by andsel** [comment]
Hi Chris @windbender I think the issue could be solved implementing correctly the CTrie algorithm (http://bravenewgeek.com/breaking-and-entering-lose-the-lock-while-embracing-concurrency/ http://lampwww.epfl.ch/~prokopec/ctries-snapshot.pdf) which uses intermediate nodes on which do CAS operations instead of a global CAS on root node as the Moquette's actual implementation.

**Comment by andsel** [comment]
At the end I introduced on master with d7023ae81b33fb292ecacb7a4be3af3e6032d18a please @windbender could you check out latest and in case report back here your feedback if it solves the issue?

**Comment by mwilliford** [comment]
Under test with 150 simultaneous inbound connections.  Connections are marked clean, so there is a removeSubscription loop on connectACK, which calls into the new CTrie code.  On the remove, I think the tree is corrupt, based on the observation of this exception.

- Tested against HEAD
- Working with @windbender on this as well.  

Do you have any ides on how I can track this bug down? 

```
48935 ! java.lang.IllegalStateException: Can't be invoked on TNode
48936 ! at io.moquette.spi.impl.subscriptions.TNode.containsOnly(TNode.java:42)
48937 ! at io.moquette.spi.impl.subscriptions.CTrieSubscriptionDirectory.remove(CTrieSubscriptionDirectory.java:277)
48938 ! at io.moquette.spi.impl.subscriptions.CTrieSubscriptionDirectory.removeSubscription(CTrieSubscriptionDirectory.java:265)
48939 ! at io.moquette.spi.impl.ProtocolProcessor.sendAck(ProtocolProcessor.java:365)
48940 ! at io.moquette.spi.impl.ProtocolProcessor.processConnect(ProtocolProcessor.java:277)
48941 ! at io.moquette.server.netty.NettyMQTTHandler.channelRead(NettyMQTTHandler.java:47)
48942 ! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
48943 ! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
48944 ! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
48945 ! at io.moquette.server.netty.metrics.MQTTMessageLogger.channelRead(MQTTMessageLogger.java:44)
48946 ! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
48947 ! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
48948 ! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
48949 ! at io.moquette.server.netty.metrics.MessageMetricsHandler.channelRead(MessageMetricsHandler.java:48)
48950 ! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
```

**Comment by andsel** [comment]
No I don't have.
Do you have the complete log file from when you star the broker to the crash? Or any other test case to let me reproduce it?

**Comment by mwilliford** [comment]
I just figured it out but still testing the solution, CTrie needs a little work on the TNode handling.  I will update you when I have unit tests and a fix.

What commit point do you consider the most stable at this point?

**Comment by mwilliford** [comment]
@andsel 

I have the following fork, which i'm consider creating a PR for.   https://github.com/mwilliford/moquette

Let me know if you want to discuss.

@windbender Is doing a code review for me, before I submit a PR to you.

**Comment by mwilliford** [comment]
@andsel is this issue closed now?

**Comment by andsel** [comment]
Yes it's fixed by CTries implementation.
Andrea
Il giorno 29/ott/2017 08:12, "Marcus Williford" <notifications@github.com>
ha scritto:
