### ISSUE TITLE
moquette stores retain messages beyond when it needs to.

### ISSUE THREAD

**Issue by windbender** [moquette-io/moquette#320]
A message sent with retain=true and QOS=0  should be stored only as long as until ANOTHER message is sent on that same topic.  in the MemoryMessageStore  in  storeRetained moquette should delete the previously stored retained message before inserting the new message.

The lack of cleaning the old stored messages, results in a memory leak.

**Comment by sawyer7246** [comment]
May be I have the same problem with version 0.9. I find my 'moquette_store.mapdb.p' and memory keep increasing ,eventually, server throws a OutOfMemory Exception. Anyone can help me?

**Comment by andsel** [comment]
I'm reworking hardly on simplify the storing part, avoiding reference count to messages but moving physically the messages between the persistent maps. This should solve this bug. I'm switching to H2 MvStore, so I've little bit work to do and than I merge on master.

**Comment by andsel** [comment]
This should already be fixed with rel 0.10
