### ISSUE TITLE
vague Custom Authenticator

### ISSUE THREAD

**Issue by BigGitWorld** [moquette-io/moquette#324]
Hi.
I created a java class that implements IAuthenticator interface to do a custom process.
Where do I have to place this class now?Because When I added it to moquette.conf file , it gives me ClassNotFoundException.
thanks a lot...

**Comment by hcjao** [comment]
1. Pack your class as jar
2. Put jar into lib folder. 
3. Use full class name in .conf

I just did it yesterday. :>

**Comment by BigGitWorld** [comment]
can you show me an example for step(3)?
I did these steps too and use the below in the .conf file:
```
authenticator_class mypackageName.myClassName
```
But I will receive ClassNotFoundException error.

**Comment by hcjao** [comment]
It's my setting in .conf, 
```
authenticator_class net.turbidness.mqtt.IAuthenticator
authorizator_class net.turbidness.mqtt.IAuthorizator
```

**Comment by BigGitWorld** [comment]
thank you very much.
I solved it.
My problem was due to miss-typing in the path.
