### ISSUE TITLE
There is not Topic class in BinTray

### ISSUE THREAD

**Issue by BigGitWorld** [moquette-io/moquette#326]
Hi.
When I installed this broker from BinTray, I saw that there is not the Topic class  in the lib folder (io.moquette.spi.impl.subscriptions.Topic).
please correct it.
best regards

**Comment by andsel** [comment]
The Topic class is a new entry in master 0.10 that's not yet on BinTray. As
you can see BinTray has tge latest stable version the 0.9 so there is
nothing to correct,once 0.10 is stable I'll release on BinTray
Il giorno 03/giu/2017 15:25, "BigGitWorld" <notifications@github.com> ha
scritto:

**Comment by BigGitWorld** [comment]
thank you very much @andsel
