### ISSUE TITLE
How to implement clustering

### ISSUE THREAD

**Issue by duanxg** [moquette-io/moquette#330]
What do I need to do to achieve the cluster

**Comment by andsel** [comment]
Moquette has poor clustering support, I plan also to remove the bridging art implemented on top of Hazelcast

**Comment by duanxg** [comment]
Moquette consider clustering in the future?

**Comment by andsel** [comment]
Before clustering the broker has to reach the MQTT protocol v5, moving to
gradle and rewrite some parts in Kotlin for more readability.

 Andrea

**Comment by duanxg** [comment]
OK,Thanks!

**Comment by duanxg** [comment]
OK,Thanks!
