### ISSUE TITLE
Fooooooooo when the session is cleaned

### ISSUE THREAD

**Issue by gotev** [moquette-io/moquette#333]
Using moquette 0.10. When the session is cleaned I get a `Fooooooooo` error log. By looking in the code I found it's here: https://github.com/andsel/moquette/blob/d5a8e3f7b406770933de29888ba863748b677393/broker/src/main/java/io/moquette/persistence/MemorySessionStore.java#L306

Is it intended to be there for some reason or it's just a debug message left while developing?

**Comment by AndreasMager** [comment]
Hi gotev. Your right it's a left debugging message. Sorry my fault.
