### ISSUE TITLE
Offline Messages

### ISSUE THREAD

**Issue by poovarasanvasudevan** [moquette-io/moquette#336]
If My client (Paho) Has cleanSession=False Then Where Moquette stores the offline Message , Whether It stores in Memory Or MapDB Database that used by moquette,

Sorry for my bad english

Thanks
Poovarasan Vasudevan

**Comment by andsel** [comment]
By default moquette uses in memory DB, but in moquette.conf you could select between H2 and MapDB
storage_class io.moquette.persistence.h2.H2PersistentStore
or
storage_class io.moquette.persistence.mapdb.MapDBPersistentStore
