### ISSUE TITLE
netty TCP_NODELAY

### ISSUE THREAD

**Issue by CB-IT** [moquette-io/moquette#339]
I updated from 0.8 to 0.10 and getting following log now:

> Jul 25, 2017 11:22:56 AM io.netty.bootstrap.AbstractBootstrap setChannelOption
WARNUNG: Unknown channel option 'TCP_NODELAY' for channel '[id: 0x8db1ec3d]'
Jul 25, 2017 11:22:56 AM io.netty.bootstrap.AbstractBootstrap setChannelOption
WARNUNG: Unknown channel option 'TCP_NODELAY' for channel '[id: 0xaa52e94e]' <

What does it mean? And how can I set 'TCP_NODELAY'?

**Comment by somejavadev** [comment]
Seems like this project had a similar issue: [lettuce](https://github.com/lettuce-io/lettuce-core/issues/476), although it is just a warning, not sure if there are any side effects.

**Comment by allan-d-c** [comment]
I'm trying to reduce spurious errors and warnings. It'd be nice to get this one quiet.

**Comment by andsel** [comment]
Fixed 513d4d79965c41bd76189afcf57bc056cffcac90
