### ISSUE TITLE
allow_anonymous

### ISSUE THREAD

**Issue by pedrocarvalho** [moquette-io/moquette#34]
Hi,

currently a client can connect without supplying any username and password, even if the configuration is set to use a password file (password_file parameter in moquette.conf). However, if the client specifies a username and password, they will be compared with the ones in password_file. 
Mosquitto solves this with the allow_anonymous configuration parameter, and moquette could have a similar parameter.

Thank you

**Comment by pedrocarvalho** [comment]
Thank you Andrea.

**Comment by andsel** [comment]
You're wellcome, let me know if there are other throubles.
