### ISSUE TITLE
memory leak on MemorySessionStore

### ISSUE THREAD

**Issue by arifainchtein** [moquette-io/moquette#347]
Hello,
I am embedding  Moquette using the following code:

`IResourceLoader classpathLoader = new ClasspathResourceLoader();
 	        final IConfig classPathConfig = new ResourceLoaderConfig(classpathLoader);

 	        final Server mqttBroker = new Server();
 	       
 	        List<? extends InterceptHandler> userHandlers = Collections.singletonList(new PublisherListener());
 	        mqttBroker.startServer(classPathConfig, userHandlers);`

The class PublisherListener is

`public class PublisherListener  extends AbstractInterceptHandler {
	Logger logger;
	
	public PublisherListener() {
		logger = Logger.getLogger(getClass());
		
	}
	public void onConnect(InterceptConnectMessage message) {
		logger.info(" received connection from " +  message.getClientID());
	}
	 
	    public void onDisconnect(InterceptDisconnectMessage msg) {
	    	logger.info(" received onDisconnect from " +  msg.getClientID());
	    } 

	    public void onConnectionLost(InterceptConnectionLostMessage msg) {
	    	logger.info("onConnectionLost from " +  msg.getClientID());
	    }
	    
	public void onPublish(InterceptPublishMessage message) {
		logger.info(" received a message on topic: " + message.getTopicName()
		+ ", from: " + message.getClientID());
				
	}
	@Override
	public String getID() {
		// TODO Auto-generated method stub
		return "Publisher Listener";
	}
}
`
after the program runs for a while, it crashes because of an out of memory error.
I ran the code with the flag to produce and memory dump which generated an hprof file.  When I opened it in eclipse, and ask for the memory leak report, i got the following:

**One instance of "io.moquette.persistence.MemorySessionStore" loaded by "sun.misc.Launcher$AppClassLoader @ 0x6eaae6f8" occupies 125,642,208 (97.21%) bytes. The memory is accumulated in one instance of "java.util.concurrent.ConcurrentHashMap$Node[]" loaded by "<system class loader>".**

Not sure what object is not garbae collected.  Any suggestion would be appreciated.

**Comment by andsel** [comment]
I've reworked a lot the session management with commit 1b272e584933fc0b78919bad767d7e73dbcc01b6 so this should be attenuated
