### ISSUE TITLE
Topic Discovery 

### ISSUE THREAD

**Issue by sjpark9** [moquette-io/moquette#35]
are you planning to support this kind of function?

Thanks

**Comment by andsel** [comment]
Hi @sjpark9  could you explain better?what do you mean for "topic discovery"?

 Andrea

**Comment by sjpark9** [comment]
I mean in a  broker hosting side's view, it would be great if I could know what topics are being used, subbed by which client id.

**Comment by andsel** [comment]
That's not the task of the broker nor it's part of MQTT specification.
To discover all topic you could create a client that subscribe to the topic wildcard "#".
This could be an idea for a plugin or for an management console that lives in pair with a Moquette instance.

**Comment by sjpark9** [comment]
Actually the method you recommend seems great. Thanks
