### ISSUE TITLE
moquette.io not working

### ISSUE THREAD

**Issue by mgbckr** [moquette-io/moquette#353]
Hi, I was trying to check out moquette starting with the docs, but there seems to be an issue with your page moquette.io (also andsel.github.io/moquette).

**Comment by amit-handa** [comment]
+1

**Comment by fofohi** [comment]
+1

**Comment by somejavadev** [comment]
+1 (moquette.io redirected you too many times.)

**Comment by andsel** [comment]
Fixed, was the CNAME file in gh-pages that created clash
