### ISSUE TITLE
Load Handling

### ISSUE THREAD

**Issue by somejavadev** [moquette-io/moquette#354]
Hi, thanks for this library. Do you perhaps have any stats on what load this library would be able to handle (messages / second) ? Looking to use this library in a micro service.

**Comment by andsel** [comment]
Real production load test no, but times ago  (using some groovy scripts you
can find in the tools/benchmark directory) I've proved that in publish
end-to-end, a client subscribing to a topic, and publishing a message (with
send timestamp inside the payload) on the same topic, the broker performed
almost 30K msg/sec as global outbound limit, so using 2 clients flows, I
saw 15K msg/sec per client.

 Andrea

**Comment by somejavadev** [comment]
Thanks for the fast reply. Seems impressive.
