### ISSUE TITLE
Netty Leak Detection

### ISSUE THREAD

**Issue by somejavadev** [moquette-io/moquette#356]
Hi,   
I have setup a simple embedded broker, when I setup multiple clients threads (100) producing a message every second I receive the following error:     
    
[SEVERE: io.netty.util.ResourceLeakDetector](https://gist.github.com/somejavadev/f2ad0a1b850736dfb3b3366e2d484e65)  The broker simply prints out the payload once received.   
Code for printing the message:   
`    @Override   
    public void onPublish(InterceptPublishMessage msg) {   
        super.onPublish(msg);    
        System.out.println("Message: " + msg.getPayload().toString());    
    }`    &nbsp;     

Running the jar in docker openjdk jr8. as well as locally (Ubuntu 16.04 64Bit) results in this issue. Removing the sys out does not prevent the issue.       
     
Here are the files used for testing the load:  
[Runnable](https://gist.github.com/somejavadev/9ed163170ed2a3624a614ce85ff3bd71)   
[Load Runner](https://gist.github.com/somejavadev/abb31c251e6adb3d155188abc4efec40)    
    
Using version 0.10 of moquette.

**Comment by AndreasMager** [comment]
The Problem should be solved with #302
