### ISSUE TITLE
memory leak in org.mapdb.Caches$HashTable

### ISSUE THREAD

**Issue by arifainchtein** [moquette-io/moquette#363]
Hello,
I am using Moquette 0.9 and the broker keeps crashing.  i generated an hprof file and when I see the Leak Suspects, I get the following message:

One instance of "org.mapdb.Caches$HashTable" loaded by "sun.misc.Launcher$AppClassLoader @ 0x6eda0030" occupies 123,633,184 (95.81%) bytes. The memory is accumulated in one instance of "org.mapdb.Caches$HashTable" loaded by "sun.misc.Launcher$AppClassLoader @ 0x6eda0030".

I tried using 0.10 but the problem is that the PAHO client keeps disconnecting so it even worst, because with 0.9 at least i can reboot every so often but with 0.10 the PAHO client does not work at all.

I am including a screen capture of the hprof analysis

Any suggestions on how to fix this problem will be greatly appreciated'

![screen shot 2017-09-18 at 3 05 56 pm](https://user-images.githubusercontent.com/7456552/30529649-eabf9c60-9c82-11e7-9d92-82080ce0e97d.png)

**Comment by sebastianlaag** [comment]
We have exactly the same problem, even if we just use 10 mqtt clients.

After testing some scenarios, i guess it is a problem with the mqtt messages. Moquette has no problem if thousands of mqtt clients connect, but when sending data, the broker consumes more and more memory.

**Comment by dnobel** [comment]
Exactly the same problem for me :( An immediate fix would be appriciated

**Comment by andsel** [comment]
Hi,
I maintain only the latest version and the current master, currently things are changing a lot in session management/storing to fix some leaks, I don't have any time, but I hope I could merge soon

**Comment by sebastianlaag** [comment]
The same problem exists with Moquette 0.10. We used 200 mqtt connections and send messages every second. Attached you find the results when connecting with jvisualvm to the java process.

Even if i stop all mqtt clients and trigger the garbage collection manually it does not free that much memory so that you get to the starting memory consumption.

![200connectionsevery1000ms](https://user-images.githubusercontent.com/720199/31423840-492267c0-ae57-11e7-86da-ef267bc5c8ab.PNG)

**Comment by sebastianlaag** [comment]
I could narrow down the failure. I guess the memory is no actual memory leak. If you configure your mqtt message with retained true, or just do not set the parameter (default seems to be true), every message will be stored in the mentioned org.mapdb.Caches$HashTable.

So the application just works as designed. Nevertheless, is it possible to clear the map of the stored messages?

**Comment by andsel** [comment]
It's responsibilty of MapDB to free the memory that itself use,so this
couldn't be an issue. You could give a try to H2 storage also implemented
in Moquette,if it fixes this behaviour
Il giorno 11/ott/2017 16:31, "Sebastian Laag" <notifications@github.com> ha
scritto:
