### ISSUE TITLE
moquette.bat has an invalid character on line 85 causing it to fail to startup.

### ISSUE THREAD

**Issue by justinmtilley** [moquette-io/moquette#367]
**Description:**

On Windows 10, attempting to run .\moquette.bat causes the following failure message and does not start:

**Console Output:**

F:\Applications\moquette\distribution-0.10-bundle-tar\bin>.\moquette.bat
"                                                                         "
"  ___  ___                       _   _        ___  ________ _____ _____  "
"  |  \/  |                      | | | |       |  \/  |  _  |_   _|_   _| "
"  | .  . | ___   __ _ _   _  ___| |_| |_ ___  | .  . | | | | | |   | |   "
"  | |\/| |/ _ \ / _\ | | | |/ _ \ __| __/ _ \ | |\/| | | | | | |   | |   "
"  | |  | | (_) | (_| | |_| |  __/ |_| ||  __/ | |  | \ \/' / | |   | |   "
"  \_|  |_/\___/ \__, |\__,_|\___|\__|\__\___| \_|  |_/\_/\_\ \_/   \_/   "
"                   | |                                                   "
"                   |_|                                                   "
"                                                                         "
Using JAVA_HOME:       "C:\Program Files\Java\jdk1.8.0_144"
Using MOQUETTE_HOME:   "F:\Applications\moquette\distribution-0.10-bundle-tar"
Improperly specified VM option 'GCLogFileSize=10M -XX:+HeapDumpOnOutOfMemoryError -Djava.awt.headless=true -Dlog4j.configuration=file:F:\Applications\moquette\distribution-0.10-bundle-tar\config\moquette-log.properties -Dmoquette.path=F:\Applications\moquette\distribution-0.10-bundle-tar -cp F:\Applications\moquette\distribution-0.10-bundle-tar\lib\* io.moquette.server.Server'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Version  Info**

Moquette Version: 0.10 
Java Version 1.8.0_144

NOTE: Also incorporated changes committed with the fix for Issue #331 
This fixed the warnings about the invalid '#' chars - but did not fix the underlying issue with the JVM Option being invalid.

**Cause:**
There is a trailing double-quote (") character on line 85 of moquette.bat.
Removing this double-quote from the file allows Moquette to start perfectly.

**Comment by rongwei84n** [comment]
[moquette的副本.txt](https://github.com/andsel/moquette/files/1420533/moquette.txt)


this bat shell should be ok

1. download this file
2. rename to moquette.bat
3. run it on windows os

**Comment by andsel** [comment]
Fixed with b1aa0019b25c3a84de921f34b05318777edaefe7
