### ISSUE TITLE
SomeQuestionsAboutMoquetteSource

### ISSUE THREAD

**Issue by xhyzjiji** [moquette-io/moquette#369]
I need some help to deepen the understanding of the source code.
1. In the CTrieSubscriptionDirectory.java, method insertSubscription use shallow copy cnode.copy (), but attribute subscriptions is using HashSet which is non-thread safe. Will it arise concurrency problems if the multiple threads hold the cnode copied on the same cnode basis and concurrently execute the add operation?
2. I found that DurableSession.InboundFlightZone does not have an inboundFlightMessages.remove call. (memory leak?)
3. Dose moquette have retransmission mechanism for the PUBREL / PUBREC / PUBCOMP message lost during network transmission?
4. Moquette will republish StoredMessage in the queue after sending connack. If the client does not re-subscribe to the topics of those messages at this time, the messages may be discarded.
5. Does moquette have write speed control? Low-speed devices may cause extensive use of kernel write cache.

**Comment by andsel** [comment]
1) no
2) no
3) no
5) no
