### ISSUE TITLE
Cluster question

### ISSUE THREAD

**Issue by mao2080** [moquette-io/moquette#376]
we use the same clientid  connection Moquette Server. In the case of single machine, the frist connection will be offline.But In the case of Cluster, it doesnot work. There are two connections online at the same time.What we expect is in the case of Cluster kill the frist connection and keep the last connection .

**Comment by andsel** [comment]
The cluster support is really poor, in practice it just forward publishes.
I've the plan to re-implement it, but I don't have any timeline.

 Andrea

**Comment by mao2080** [comment]
@andsel   ok, Thanks a lot.
