### ISSUE TITLE
Hello using last code error

### ISSUE THREAD

**Issue by zhoudianyou** [moquette-io/moquette#38]
error option

A connection server  (clear session false)-> subscription  /sys/abc     -> distconnection
B connection server (clear session false )-> publish message (topic /sys/abc   qos =2) 
A connection server   (clear session false)   ...server error

error code 
13223 [pool-1-thread-1] INFO  ProtocolProcessor  - Create persistent session for clientID <AAAAA>
13232 [pool-1-thread-1] INFO  ProtocolProcessor  - Connected client ID <AAAAA> with clean session false
13232 [pool-1-thread-1] INFO  ProtocolProcessor  - No stored messages for client <AAAAA>
34268 [pool-1-thread-1] INFO  ProtocolProcessor  - Create persistent session for clientID <BBBBB>
34274 [pool-1-thread-1] INFO  ProtocolProcessor  - Connected client ID <BBBBB> with clean session false
34274 [pool-1-thread-1] INFO  ProtocolProcessor  - No stored messages for client <BBBBB>
44705 [pool-1-thread-1] INFO  ProtocolProcessor  - <AAAAA> subscribed to topic </sys/abc> with QoS 0 - MOST_ONE
47234 [pool-1-thread-1] INFO  ProtocolProcessor  - DISCONNECT client <AAAAA> with clean session false
60281 [pool-1-thread-1] INFO  ProtocolProcessor  - PUBLISH from clientID <BBBBB> on topic </sys/abc> with QoS EXACTLY_ONCE
64265 [pool-1-thread-1] INFO  ProtocolProcessor  - Create persistent session for clientID <AAAAA>
64269 [pool-1-thread-1] INFO  ProtocolProcessor  - Connected client ID <AAAAA> with clean session false
64270 [pool-1-thread-1] INFO  ProtocolProcessor  - republishing stored messages to client <AAAAA>
64270 [pool-1-thread-1] INFO  ProtocolProcessor  - send publish message to <AAAAA> on topic </sys/abc>
64272 [pool-1-thread-1] ERROR SimpleMessaging  - Serious error processing the message Connect [clientID: AAAAA, prot: MQTT, ver: 04, clean: false] for session [clientID: AAAAA]org.eclipse.moquette.server.netty.NettyChannel@78c36c6f
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at org.eclipse.moquette.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:66)
    at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:167)
    at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:57)
    at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.eclipse.moquette.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:64)
    ... 6 more
Caused by: java.lang.RuntimeException: Internal bad error, trying to forwardPublish a QoS 0 message with PacketIdentifier: 0
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.sendPublish(ProtocolProcessor.java:416)
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.republishStoredInSession(ProtocolProcessor.java:263)
    at org.eclipse.moquette.spi.impl.ProtocolProcessor.processConnect(ProtocolProcessor.java:240)
    ... 11 more

**Comment by bobwenx** [comment]
probably caused by the code:

``` java
// ProtocolProcessor
 private void forward2Subscribers(String topic, AbstractMessage.QOSType qos, ByteBuffer origMessage, boolean retain, Integer messageID) {
   if (qos == AbstractMessage.QOSType.MOST_ONE && sub.isActive()) {
      sendPublish(sub.getClientId(), topic, qos, message, false, null);
   }
   ...
}
```

should change to:

``` java
 private void forward2Subscribers(String topic, AbstractMessage.QOSType qos, ByteBuffer origMessage, boolean retain, Integer messageID) {
   if (qos == AbstractMessage.QOSType.MOST_ONE) {
      if(sub.isActive()){
          sendPublish(sub.getClientId(), topic, qos, message, false, null);
      }
   }
   ...
}
```

**Comment by zhoudianyou** [comment]
ok  Thanks

**Comment by andsel** [comment]
I don't think it solves,because yuo just splitted an and expression with 2
concatenated ifs,the semantic is thd same.

Andrea
Il giorno 04/giu/2015 06:27, "bob" notifications@github.com ha scritto:

**Comment by bobwenx** [comment]
no, it's not the same. the whole code:

``` java
if (qos == AbstractMessage.QOSType.MOST_ONE && sub.isActive()) {
          sendPublish(sub.getClientId(), topic, qos, message, false, null);

}
else{
   // then you code process the qos 1 & qos 2 message. 
}
```

the problem here: if the channel is not active, it should drop qos 0 message rather than process it in `else` block(processing code for qos 1 & qos 2), which will persist qos 0 message with messageID. 
And when client reconnect, The `republishStoredInSession` method will redelivery qos 0 message with messageID. 
Then, your status machine will place in incorrect status. and the code will just throw exceptions.

by change code to:

``` java
private void forward2Subscribers(String topic, AbstractMessage.QOSType qos, ByteBuffer origMessage, boolean retain, Integer messageID) {
   if (qos == AbstractMessage.QOSType.MOST_ONE) {
      if(sub.isActive()){
          sendPublish(sub.getClientId(), topic, qos, message, false, null);
      }
   }
   else{
      // then you code process the qos 1 & qos 2 message. 
   }
}
```

you drops the QOS 0 message if channel is inactive, no need to execute code in `else` block.

**Comment by zhoudianyou** [comment]
this bug Can the fix?

**Comment by andsel** [comment]
It could be, but before I've to write a test to reproduce it and then fix
it (probably with the suggested patch).

 Andrea

**Comment by zhoudianyou** [comment]
code revert to     d271e23f991c14074135f6da7609404a7c149d9c      Will not appear bug   

715937a394a89b7d1a647e3619da88bd2a36f9b3  begin  Will appear bug   

 im sorry My English is very poor

**Comment by andsel** [comment]
The problem was due to the storing of PublishEvent (which had an int messageID) that message ID was optional but using int instead of Integer make it to initialiaze to 0 for QoS 0.
You could try with groovy script https://github.com/andsel/moquette/blob/master/tools_scripts/integration/issue38_pubsubQos2.groovy

**Comment by bobwenx** [comment]
i don't understand why change storage code to handle qos 0 message rather than just drops QOS 0 message.

**Comment by zhoudianyou** [comment]
Thanks

**Comment by andsel** [comment]
When the message arrived from publish was stored (for no clean sessions) it was an instance of PublishEvent which has an int field. When the subscriber reconnected, the stored message was loaded from DB and republished, the message was the one with accidentally stored packetID =0, and that give the error; The reason why that packedID was 0 is that the hosting field was int type insted of Integer (so by default was initialized to 0).
 When the subscriber connected the second time, and loaded the stored message it discover that was trying to publish a QoS0 message with a packetID, and that's an error (thrown by the exception) becasue QoS0 messages mustn't have the packetID

**Comment by bobwenx** [comment]
yes, this is the cause of exception. but if you don't store PublishEvent for QOS 0 message, you don't need to handle wrapper type(Integer) at all. 
At least, when the subscriber connected the second time, we don't need to forward QOS 0 message to it.

**Comment by andsel** [comment]
That's a design decision to forward messages to QoS0 subscribed listeners, it's not specified by the specification. At the moment Moquette store and forwards messages at QoS0 subscribers

**Comment by bobwenx** [comment]
OK, that's fine.
please see issue: https://github.com/andsel/moquette/issues/49 and https://github.com/andsel/moquette/issues/50
