### ISSUE TITLE
InterceptHandlers are not working on internal publish

### ISSUE THREAD

**Issue by newbeewan** [moquette-io/moquette#383]
### Expected behavior
According to the main in https://github.com/andsel/moquette/blob/master/embedding_moquette/src/main/java/io/moquette/testembedded/EmbeddedLauncher.java
I was expecting InterceptHandler should be called for every publish message...

### Actual behavior
I reproduced the EmbeddedLauncher and runnig it locally with Moquette version 0.10...

My InterceptHandler is never called.

### Steps to reproduce
Run the EmbeddedLauncher

### Moquette MQTT version
0.10

### JVM version (e.g. `java -version`)
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)

### OS version (e.g. `uname -a`)
Ms Windows 7

**Comment by andsel** [comment]
This is the expected behaviour, the internal publish doesn't fire the events, because if it's internal I expect that the embedder already knows what's in happing so it doesn't need any notification of the publish happened.

**Comment by theborakompanioni** [comment]
I kind of assumed this behaviour too and currently use a workaround to enable this "feature" (using a decorator + event bus). Having this possibility would be great! Would you be willing to accept a pull request that adds a new `onInternalPublish` to the `InterceptHandler`?

**Comment by andsel** [comment]
@theborakompanioni do you mean a PR to self publish from internalPublish, so that an embedder applicationthat call internalPublish and is subscribed to the topic it's publishing get notified of the self lauched publishing? I mean it's a bit counterintuitive, because is like asking myself a thing that I already know

**Comment by theborakompanioni** [comment]
Hey @andsel, thanks for your response. I hope I can help by simply explaining my use case. I am quite sure there are better solutions, but this one has been an option that comes to mind time and time again.
For me, it is all about separation of concerns.

Suppose a library starts a broker and let users implement own agents that can hook into all messages sent. One of these agents may publish internal messages (Agent A) another one may persist all messages to a data store (Agent B). In order for the these agents to interact, one would currently need to do something that feels like a "workaround" to the original problem:
- Agent A and Agent B "know" of each other directly
- Agent B connect as client to subscribe to all topics
- Agent A connects as client to publish messages (not using `internalPublish`)
- Agent A and Agent B communicate through a mediator (event bus, etc.)

I have ordered these by liking - starting with the one I dislike the most (does not scale - e.g. "add another Agent C"). All of these of course have their benefits or drawbacks. The last option just adds a layer on top of the functionality that already exists in the library (with `InterceptorHandler`). 

I currently do something like the following (just exemplary):
```java
public interface InterceptHandlerWithInternalMessageSupport extends InterceptHandler {
    default void onInternalPublish(InterceptInternalPublishedMessage msg) {
        // empty on purpose
    }
}
```
```java
public class ServerWithInternalPublish extends Server {

    private final EventBus eventBus;

    public ServerWithInternalPublish(EventBus eventBus) {
        super();

        this.eventBus = requireNonNull(eventBus);
    }

    public void internalPublish(MqttPublishMessage msg, String clientId) {
        super.internalPublish(msg, clientId);

        this.eventBus.post(InterceptInternalPublishedMessage.builder()
                .clientId(clientId)
                .msg(msg)
                .build());
    }
}
```
```java
public static class MoquettePublishInternalBridge {
    private final List<InterceptHandlerWithInternalMessageSupport> handler;

    public MoquettePublishInternalBridge(EventBus eventBus, List<InterceptHandlerWithInternalMessageSupport> handler) {
        this.handler = handler;

        eventBus.register(this);
    }

    @Subscribe
    public void onInternalPublishEvent(InterceptInternalPublishedMessage msg) {
        handler.forEach(h -> h.onInternalPublish(msg));
    }
}
```
Currently it seems this problem would be better solved when `InterceptorHandler` had an `onInternalPublishEvent` directly. With a default noop implementation like in the example above it would not even break backward compatibility and users would have another feature in their toolset when using your library.

I`d be great if there is a better solution without modifing the core library of course!
Maybe you can guide me in the right direction. What do you think? 

Thank you!

**Comment by theborakompanioni** [comment]
Any further thoughts on this, @andsel ?
I thought it through again and again and could not come up with a better solution than to implement it directly into the library - all other solutions smell like workarounds.

Suppose the provider of a package cannot know in advance which InterceptHandler will be registered by a user or which messages will get published internally. Given someone wants to handle all messages, then currently the only solution to get these external events is to subscribe as a regular client.
