### ISSUE TITLE
error when start moquette by persistent store

### ISSUE THREAD

**Issue by BigGitWorld** [moquette-io/moquette#384]
Hi.
I'm going to use H2 persistent store.but when I started moquette, give me this error : 
```
//SessionRepository class / getAllSessions() method : 
Exception in thread "main" java.lang.AbstractMethodError: io.moquette.persistence.h2.H2SessionsStore.listAllSessions()Ljava/util/Collection; 
at io.moquette.spi.impl.subscriptions.CTrieSubscriptionDirectory.init(CTrieSubscriptionDirectory.java:111)
at
io.moquette.spi.impl.ProtocolProcessorBootstrapper.init(ProtocolProcessorBootstrapper.java:124)
```
I checked more and found that the problem occur in "createNewSession" method where "createNewDurableSession" method must be called.
why?

my moquette.conf file : 
#persistent_store config/moquette_store.db
#storage_class io.moquette.persistence.mapdb.MapDBPersistentStore
storage_class io.moquette.persistence.h2.H2PersistentStore

**Comment by andsel** [comment]
This seems like a mismatching version of jars between the moquette-broker and the h2 persistence implementation. Which version are you using? Could you try with a fresh installation from bintray (https://bintray.com/andsel/generic/download_file?file_path=distribution-0.10-bundle-tar.tar.gz)?

**Comment by andsel** [comment]
No reproducible and no response from the reporter
