### ISSUE TITLE
Netty Leak Detection 

### ISSUE THREAD

**Issue by wurangbo** [moquette-io/moquette#385]
Netty Leak Detection  has been found  when I run it as embedded broker(0.10 version).
How can I get the Last version? 
pom info:
          <groupId>io.moquette</groupId>
            <artifactId>moquette-broker</artifactId>
            <version>0.10</version>

**Comment by andsel** [comment]
Clone the project and mvn install, so you get locally the master snapshot.
 Andrea

Il 20 gen 2018 7:51 AM, "wurangbo" <notifications@github.com> ha scritto:

**Comment by davidgraeff** [comment]
Would you mind to release a 0.11 with all the latest fixes? :)

**Comment by andsel** [comment]
I've still other bugfixes to do, I wnat to lower the number of bug issues and than I plan for 0.11. After that I'll start work on MQTTv5 upgrade

**Comment by andsel** [comment]
It's a question
