### ISSUE TITLE
java.lang.NullPointerException.

### ISSUE THREAD

**Issue by wushiyuanyumei** [moquette-io/moquette#386]
###Android pad 发出去的版本,经常崩溃,后台统计的日志如下:那位大神给指点一下

TIME=1487153070000
FINGERPRINT=alps/RH71XJ/RH71XJ:4.4.2/KOT49H/1487152954:user/test-keys
HARDWARE=mt8121
UNKNOWN=unknown
RADIO=unknown
BOARD=MT8121V
versionCode=2600
PRODUCT=RH71XJ
versionName=2.6.0
DISPLAY=RH71XJ.v1.1.5
USER=songxia
HOST=sxv2
DEVICE=RH71XJ
TAGS=test-keys
MODEL=RH71XJ
BOOTLOADER=unknown
CPU_ABI=armeabi-v7a
CPU_ABI2=armeabi
IS_DEBUGGABLE=false
ID=KOT49H
SERIAL=SDRH711J63900517
MANUFACTURER=alps
BRAND=alps
TYPE=user
java.lang.NullPointerException
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:310)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:608)
	at java.lang.Thread.run(Thread.java:841)

**Comment by andsel** [comment]
Bad reported issue, no OS, no reproducibility and seems related to Paho
