### ISSUE TITLE
Target session %s is connected but doesn't anymore subscribed to %s

### ISSUE THREAD

**Issue by mao2080** [moquette-io/moquette#387]
What kind of scene will produce such a exception？

![image](https://user-images.githubusercontent.com/26266425/35792135-8b88e536-0a86-11e8-8406-66ec6762deec.png)

**Comment by andsel** [comment]
It happens if during the publish processing, the client unsubscribe from
the subscription (or closes with clean=true)

 Andrea

**Comment by andsel** [comment]
closed as question
