### ISSUE TITLE
Link to setup doc is wrong

### ISSUE THREAD

**Issue by cforce** [moquette-io/moquette#391]
The github projects links to http://andsel.github.io/moquette/ for setup doc and then links back to the source. Where is the doc around broker usage? How can I realize embedded broker to cloud broker gateway for some topics?

**Comment by andsel** [comment]
No it works, click on documentation section in the  page you posted, and it will move you to http://andsel.github.io/moquette/documentation.html

**Comment by cforce** [comment]
Tx
