### ISSUE TITLE
Using H2 persistence example

### ISSUE THREAD

**Issue by arifainchtein** [moquette-io/moquette#393]
Hello,
I need to move away from MapDB because the file grows out of control.  I would like to try using H2 instead.  Would love to see how to initialize and configure the broker to use H2.

thanks

**Comment by andsel** [comment]
Which version of Moquette are you using? 0.9 and 0.10 should ship with H2 predefined, I remember correctly.
Take a a loot ak https://github.com/andsel/moquette/blob/master/distribution/src/main/resources/moquette.conf

as example you simply have to uncomment storage_class for H2 and comment the one for MapDB. It's not provided any migration tool to import in H2 the data stored in your MapDB file

**Comment by arifainchtein** [comment]
Thanks so much for your response.  I am using 0.9

I did do what you suggested and set the persistence to h2.  Unfortunately i am having the same problem again.  the file just grows exponentially, eventually filling up the hard drive.  what i do now is run a process and when the file grows above a certain value i have to stop the broker, remove the file and start the broker again.  

I really would like to not have to do that.  What am I doing wrong? Is there a way for this not to happen?  i set the QoS to 1 and i do have retention because i want the new clients to get the last message.  But that is it.I dont need to search for all messages.  
How can i configure moquette so I can have QoS =1, with last message retention but not fill up the hard drive?

Thanks

**Comment by andsel** [comment]
Which is your use case, because this consumption sounds like you have clients with clean session =false that subscribed to a topic where other clients are pushing a lot of stuff.
How works your publishers and subscribers? Have you got some log? There is a way I can reproduce it ?

**Comment by arifainchtein** [comment]
here is my set up:

everything runs on a raspberry pi.  I have one application that produces a json string, which can be as big as 1mb every minute or so.  
The subscribers are web clients using Paho over websockets.  Note that the every expanding file happens even if there is no client subscribed.  I have done that test as well.

Here are two pieces of code, the first one show the publishing of the json string, the second one is the paho client.  I am not including the Publisherlistener because is pretty long and all it does it parse the message received, but if you want to see it, let me know and I will paste it or share the file.


this is published using the following code 

(I apologize for the formating but  i tried 10 times to format it as code but using the markuo of github just produces one line):
```java
public synchronized void publishToHeart(String topic, String messageText) {	
		byte[] messageBytes = messageText.getBytes();
		MqttMessage message = new MqttMessage(messageBytes);
		 message.setQos(1);
	        message.setRetained(true);
	        try {
			do {
				if(!anMqttClient.isConnected()) {
					logger.warn("Reconnecting to heart");
					anMqttClient.reconnect();
					try {
						Thread.sleep(10000);
					} catch (InterruptedException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
				}	
			}while(!anMqttClient.isConnected());
			anMqttClient.publish(topic, message);
		} catch (MqttException e) {
			logger.warn("Exception publishing to heart:" + Utils.getStringException(e);	
		}
	}
```


here is my javascript code for the Paho Client:

```javascript
function HeartConnect() {
	console.log('invoking mqttconnect');
	host="DamnWatcher.local";
	port=9999; 
	mqtt = new Paho.MQTT.Client( host, port, "web_" + parseInt(Math.random() * 100));
	mqtt.onConnect = onConnect;
	mqtt.onMessageArrived = onMessageArrived;
	mqtt.onConnectionLost = onConnectionLost;
	mqtt.connect({onSuccess: onConnect, onFailure: onFailure});
	console.log("Host="+ host + ", port=" + port );
	console.log("connected...");
}
function onConnect() {
	console.log('in onconnect');
	// $('#pulse').html('Connected to ' + host + ':' + port + path);
	// Connection succeeded; subscribe to our topic
	mqtt.subscribe("Hello", {"onSuccess":subscribeSucessFcn,"onFailure":subscribeFailureFcn,qos:2});
	console.log('after firstsub');
	mqtt.subscribe(HEART_TOPIC_PULSE_STATUS_INFO, {"onSuccess":subscribeSucessFcn,"onFailure":subscribeFailureFcn,qos:2});
	mqtt.subscribe(HEART_TOPIC_PULSE_STATUS_INFO_SECUNDARY, {"onSuccess":subscribeSucessFcn,"onFailure":subscribeFailureFcn,qos:2});
	mqtt.subscribe(HEART_TOPIC_ORGANISM_STATUS, {"onSuccess":subscribeSucessFcn,"onFailure":subscribeFailureFcn,qos:2});
	mqtt.subscribe(HEART_TOPIC_UPDATE_FORM_STATUS, {"onSuccess":subscribeSucessFcn,"onFailure":subscribeFailureFcn,qos:2});
	mqtt.subscribe(HEART_TOPIC_STATUS, {"onSuccess":subscribeSucessFcn,"onFailure":subscribeFailureFcn,qos:2});
	mqtt.subscribe(HEART_TOPIC_ASYNC_CYCLE_UPDATE, {"onSuccess":subscribeSucessFcn,"onFailure":subscribeFailureFcn,qos:2});

}
```

Does anything look wrong to you?

Thanks for the help :)

**Comment by andsel** [comment]
The retained flag set to true in publishing phase could be the reason if
every message is published on different topic. As specs state, the broker
has to save the last retained message (if the publish happens with retained
true) for the topics. How are yours topics are formed, which strings?
Andrea

Il sab 17 mar 2018, 23:31 arifainchtein <notifications@github.com> ha
scritto:

**Comment by arifainchtein** [comment]
All my topics are fixed, ie i dont have any random characters.  I have the main topic which is when i publish the big json string, t he definition is;

`public static String HEART_TOPIC_STATUS="Status";`

the other topics are progress status on the creation of the json string and also have fixed values:

`
public static String HEART_TOPIC_PULSE_STATUS_INFO="PulseStatusInfo";

	public static String HEART_TOPIC_PULSE_STATUS_INFO_SECUNDARY="PulseStatusInfoSecundary";

	public static String HEART_TOPIC_UPDATE_FORM_STATUS="UpdateFormStatus";

	public static String HEART_TOPIC_UPDATE_FORM_REQUEST="UpdateFormRequest";

	public static String HEART_TOPIC_ASYNC_CYCLE_UPDATE="AsyncCycleUpdate";

`

**Comment by andsel** [comment]
Could you try to write a publisher application to make it reproducible? Or
can I do it, but in this period I'm little busy

 Andrea

**Comment by arifainchtein** [comment]
absolutely.  Let me put something together and I will share it in the next few days.  Thanks for the help.

**Comment by arifainchtein** [comment]
Hello,
Sorry about the long delay.  Here is a zip a file with a publisher and a broker. if you run them in the same machine you will see the mapdb.p file just keeps on growing.

Thanks for the help.  


[DemoMQTTBrokerBug.zip](https://github.com/andsel/moquette/files/1870075/DemoMQTTBrokerBug.zip)

**Comment by andsel** [comment]
Thanks @arifainchtein in next free time slot I'll take care of this, and examine the bug. I'll report on this issue any findings or doubts, thank's a lot for your effort in create a reproducible test bed.
 Andrea

**Comment by andsel** [comment]
Hi @arifainchtein I've tried your Publisher project against your Broker project (which use Moquette 0.9) and it happened what you described, the storage file keep growing on every publish, seems like the retained management append the  messages instead of replace the last one on the topic
Then I've tried your Publisher against a freshly broker dist build (0.11-SNAPSHOT) with both MapDB and H2 persistence, but the file keeps a constant size. 
I've rework a lot the Moquette code from 0.9 to 0.11, probably I fixed this bug, so I close it because not reproducibile with current master.

**Comment by arifainchtein** [comment]
Hey, 
Great news.  How can I try this distribution? I tried using 0.11 instead of 0.9 but the person m file gives me an error.  I also tried 0.11-SNAPHOT but got “missing Artifact”.

Thanks a lot
