### ISSUE TITLE
what time will appear this situation in processDisconnect

### ISSUE THREAD

**Issue by githubxingyuntian** [moquette-io/moquette#394]

**Comment by githubxingyuntian** [comment]
hi ,andsel
 when i was view moquette source ,i am comfused about below lines. could you give me  some times to explain when will apear  this situation in processDisconnect .Thanks very much.
I have mark the places overstriking

    public void processDisconnect(Channel channel) throws InterruptedException {
        final String clientID = NettyUtils.clientID(channel);
        LOG.info("Processing DISCONNECT message. CId={}", clientID);
        channel.flush();
        final ConnectionDescriptor existingDescriptor = this.connectionDescriptors.getConnection(clientID);
        if (existingDescriptor == null) {
            // another client with same ID removed the descriptor, we must exit
            channel.close();
            return;
        }

        /**
         * confused one 
         *  what time will happen this situation，why not equal?
         */

        if (existingDescriptor.doesNotUseChannel(channel)) {
            // another client saved it's descriptor, exit
            LOG.warn("Another client is using the connection descriptor. Closing connection. CId={}", clientID);
            existingDescriptor.abort();
            return;
        }

        if (!removeSubscriptions(existingDescriptor, clientID)) {
            LOG.warn("Unable to remove subscriptions. Closing connection. CId={}", clientID);
            existingDescriptor.abort();
            return;
        }

        if (!dropStoredMessages(existingDescriptor, clientID)) {
            LOG.warn("Unable to drop stored messages. Closing connection. CId={}", clientID);
            existingDescriptor.abort();
            return;
        }

        if (!cleanWillMessageAndNotifyInterceptor(existingDescriptor, clientID)) {
            LOG.warn("Unable to drop will message. Closing connection. CId={}", clientID);
            existingDescriptor.abort();
            return;
        }
        
        if (!existingDescriptor.close()) {
            LOG.info("The connection has been closed. CId={}", clientID);
            return;
        }

        /**
         * confused two 
         *  what time will happen this situation,why is still present
         */
        boolean stillPresent = this.connectionDescriptors.removeConnection(existingDescriptor);
        if (!stillPresent) {
            // another descriptor was inserted
            LOG.warn("Another descriptor has been inserted. CId={}", clientID);
            return;
        }

        LOG.info("The DISCONNECT message has been processed. CId={}", clientID);
    }

**Comment by andsel** [comment]
The connect and disconnect processing are essentially concurrent finite state machines, and could happen that when you have clients that connects and disconnects with same clientID and in tight cycle, while the first are disconnecting the second is already in connected state.

**Comment by githubxingyuntian** [comment]
Thanks，understand，help very much
