### ISSUE TITLE
Possibility to create IAuthorizator with a getInstance() method.

### ISSUE THREAD

**Issue by wuwer** [moquette-io/moquette#396]
As stated here https://andsel.github.io/moquette/documentation.html#_customize_authorizator the IAuthorizator implementations should either implement a default constructor or a static getInstance() method. I think the second option was removed here:  https://github.com/andsel/moquette/commit/16a9a0ccd07d1d09a36e2bc48cb20d9da5c1d239#diff-9744fd41383c757be25fa08fb7a8804dL181 .

Steps to reproduce:
Provide an implementation without a default constructor and with a getInstance() method. It will fail with a message similar to this one:
`[main] ERROR ProtocolProcessorBootstrapper  - Unable to invoke default constructor. ClassName=<AuthorizatorClass>, interfaceName=io.moquette.spi.security.IAuthorizator, cause=java.lang.NoSuchMethodException:`

**Comment by andsel** [comment]
Thanks, fixed the documentation
