### ISSUE TITLE
Broker does not start from Java application on Linux...

### ISSUE THREAD

**Issue by aviscaerulea** [moquette-io/moquette#397]
I am running with Maven + JUnit.
It works normally on Windows 10.
The following code does not listen on the specified port.

It seems that error logs such as exceptions are not being output.
What are the possible causes?

### Minimal yet complete reproducer code (or URL to code) or complete log file
```
AccessController.doPrivileged((PrivilegedAction<Server>) () -> {
	try {
		Server srv = new Server();
		Properties prop = new Properties();
		prop.setProperty("host", "0.0.0.0");
		prop.setProperty("port", String.valueOf(_port));
		prop.setProperty("allow_anonymous", "true");
		srv.startServer(prop);
		server.set(srv);
		return srv;
	}
	catch (IOException e) {
		throw new SampleException(e);
	}
});
```

### Moquette MQTT version
```
<groupId>io.moquette</groupId>
<artifactId>moquette-broker</artifactId>
<version>0.9</version>
```

### JVM version (e.g. `java -version`)
Oracle Server JRE 8u51
### OS version (e.g. `uname -a`)
AWS EC2 Amazon Linux
4.9.20-10.30.amzn1.x86_64 #1 SMP Thu Apr 6 18:22:38 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by andsel** [comment]
Hi @aviscaerulea the version supported at the moment is 0.10.
Why you run the server in privileged section? perhaps is that the reason, because in Moquette tests cases, there is parts that star the broker from unit tests, and it works without requesteing priviledges to the JVM.

**Comment by aviscaerulea** [comment]
Thanks for the response.
AccessController.doPrivileged certainly seemed unnecessary.
However, even if it was removed, the result was the same...
I also set Version to 0.10.

**Comment by andsel** [comment]
@aviscaerulea 
In moquette project there is a module (named embedding_moquette) that runs an embedded broker and it works. But also the following code works well:

```java
package org.dna.testmoquette;

import io.moquette.server.Server;

import java.io.IOException;
import java.util.Properties;

public class Main {
    public static void main(String[] args) throws IOException {
        Server srv = new Server();
        Properties prop = new Properties();
        prop.setProperty("host", "0.0.0.0");
        prop.setProperty("port", String.valueOf("1883"));
        prop.setProperty("allow_anonymous", "true");
        srv.startServer(prop);
    }
}
```

with a pom like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.dna</groupId>
    <artifactId>testmoquette</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>io.moquette</groupId>
            <artifactId>moquette-broker</artifactId>
            <version>0.10</version>
        </dependency>
    </dependencies>
```
