### ISSUE TITLE
Support Bridging

### ISSUE THREAD

**Issue by cforce** [moquette-io/moquette#399]
Support bridging of moquette broker topics to any remote broker. This is a useful pattern for  IOT Device or gateway that runs moquette as broker in the field that decides to process some  topics local but other s to be forwarded to a remote bridge based on (runtime) configuration

https://mosquitto.org/man/mosquitto-conf-5.html Configuring Brudges
http://akeil.de/posts/mqtt-bridge-with-mosquitto-and-nginx.html

**Comment by andsel** [comment]
Instead of bridging I was thinking about high availability with master - master replication.
