### ISSUE TITLE
Potential memory leak in moquette's usage of LMAX ringbuffer.

### ISSUE THREAD

**Issue by bobwenx** [moquette-io/moquette#40]
moquette use ringbuffer to publish/batch event to `ProtocolProcessor`, and the `ProtocolProcessor` using another ringbuffer to dispatch output event to netty.

By default, the ringbuffer will pre-allocate an array of event object(`ValueEvent`), and every event object will be referenced to this array until disruptor get closed.

The problems of here are moquette(`SimpleMessaging.disruptorPublish` and `ProtocolProcessor.disruptorPublish`) try to associated netty's channel(ServerChannel) with event object, which means, the ringbuffer always contain references of netty's channel until buffer overwrite. 

Every established netty channel contains quite a lot data(such as pooled byte buffer, channel pipelines...). so if user's JVM memory low than `netty's channel size * buffer size`, OOM Exception will be thrown.

it may be a good idea to clean event object(it contains a reference to netty's channel) after event object get processed, for example, in `ProtocolProcessor`, we may use:

``` java
  /**
     * Called when a publisher has published an event to the {@link RingBuffer}
     *
     * @param event published to the {@link RingBuffer}
     * @param sequence of the event being processed
     * @param endOfBatch flag to indicate if this is the last event in a batch from the {@link RingBuffer}
     * @throws Exception if the EventHandler would like the exception handled further up the chain.
     */
    @Override
    public void onEvent(ValueEvent event, long sequence, boolean endOfBatch) throws Exception {
        //It's always of type OutputMessagingEvent
        OutputMessagingEvent outEvent = (OutputMessagingEvent) event.getEvent();
        try {
            final ServerChannel serverChannel = outEvent.getChannel();
            final AbstractMessage outputEvent = outEvent.getMessage();
            if(LOG.isDebugEnabled()){
                LOG.debug("Output event, sending {}", outputEvent);
            }
            serverChannel.write(outputEvent);
        }
        finally {
            // free event resource
            event.setEvent(null);
        }
    }
```

same code should apply to `SimpleMessaging` as well.

**Comment by andsel** [comment]
Thanks good catch, it has been used to solve the issue
