### ISSUE TITLE
ERROR ...  MemorySessionStore - Can't find the session for client ...

### ISSUE THREAD

**Issue by allan-d-c** [moquette-io/moquette#400]
### Expected behavior
I'm using Moquette to support a production client based on Eclipse Paho.
I run integration tests as part of the build and would like to not have errors
in the build log.

### Actual behavior
In my log file, I am seeing a lot of "ERROR ... Can't find the session for client ..." 
Things seem to be working but the error messages are a bit disconcerting to see in 
my build output.

### Steps to reproduce

My test code looks like this...

class VirtualDevice ...
       VirtualDevice(Map parms) {
            this.parameters = parms
            this.server = new Server()
            String tmpDir = System.getProperty("java.io.tmpdir")
            this.dataStore = new MqttDefaultFilePersistence(tmpDir)
        }

        void start() {
            Properties cfg = new Properties()
            cfg.put(PORT_PROPERTY_NAME, parameters['port'])

            MemoryConfig mcfg = new MemoryConfig(cfg)
            server.startServer(mcfg)
        }
       ...
}

My client code looks like this...
import org.eclipse.paho.client.mqttv3.*;
...
MqttPersistenceStrategy strategy = new MqttPersistenceStrategy(persistence);
MqttAsyncClient client = new MqttAsyncClient(serverUrl, clientId, strategy.create());
...
        try {
            thisClient.connect(options, thisClient.getClientId()+" Connection", mylistener);
        }
        catch (MqttException e) {
            ...
        }

### Minimal yet complete reproducer code (or URL to code) or complete log file

2018-04-25_13:54:11.609 - INFO messageLogger - C->B CONNECT <null>
2018-04-25_13:54:11.611 - INFO messageLogger - C->B CONNECT <null>
2018-04-25_13:54:11.614 - ERROR io.moquette.persistence.MemorySessionStore - Can't find the session for client <Mqtt-Agent-paho104149710463\
181>
2018-04-25_13:54:11.615 - ERROR io.moquette.persistence.MemorySessionStore - Can't find the session for client <Mqtt-Agent-paho104149519831\
452>
2018-04-25_13:54:11.618 - INFO messageLogger - C<-B CONNACK <Mqtt-Agent-paho104149710463181>
2018-04-25_13:54:11.618 - INFO messageLogger - C<-B CONNACK <Mqtt-Agent-paho104149519831452>

### Moquette MQTT version
0.10

### JVM version (e.g. `java -version`)
1.8.0_144-b01

### OS version (e.g. `uname -a`)
OSX (Darwin Kernel Version 17.5.0)
This happens on other platforms as well.

**Comment by allan-d-c** [comment]
BTW thanks for Moquette. It has been very helpful to my team.

**Comment by andsel** [comment]
Fixed in 0.11-SNAPSHOT with 5456431dd4c625e3be126ba423244a375efab65f
the problem was to due to a transient session (clean session = true) that tried to retrieve a session from the store, which is a no sense, because in the store goes only durable sessions
