### ISSUE TITLE
ERROR NettyMQTTHandler exceptionCaught 108

### ISSUE THREAD

**Issue by CB-IT** [moquette-io/moquette#404]
After a while a wanted to upgrade from 0.8 (is working fine) to 0.11

But i do not get it runnig with 0.11 under win10. I also tryed the EmbeddedLauncher Example. 

0.8:
`final IConfig classPathConfig = new ClasspathConfig();
classPathConfig.setProperty("host", mqttBrokerConfiguration.getBrokerIp());
classPathConfig.setProperty("port", String.valueOf(mqttBrokerConfiguration.getBrokerPort()));
classPathConfig.setProperty("websocket_port", String.valueOf(mqttBrokerConfiguration.getBrokerWebsocketPort()));
classPathConfig.setProperty("allow_anonymous", "true");`

0.11
`Properties properties = new Properties();
properties.setProperty("host", mqttBrokerConfiguration.getBrokerIp());
properties.setProperty("port", String.valueOf(mqttBrokerConfiguration.getBrokerPort()));
properties.setProperty("websocket_port", String.valueOf(mqttBrokerConfiguration.getBrokerWebsocketPort()));
properties.setProperty("allow_anonymous", "true");
IConfig classPathConfig = new MemoryConfig(properties);`

both start with:
`moquetteBroker = new Server();
final List<? extends InterceptHandler> userHandlers = Arrays.asList(new EventListener());
moquetteBroker.startServer(classPathConfig, userHandlers);`

Logging in 0.11 gives me: 

`ERROR NettyMQTTHandler exceptionCaught 108  - Unexpected exception while processing MQTT message. Closing Netty channel. CId=null`

**Comment by andsel** [comment]
You should explain better, because CId = null means client without id. When open an issue specify how to reproduce, do you have a client that connects?

**Comment by CB-IT** [comment]
I did a further test und realized, that the error is related to MQTTLens (a chrome extension). Excuse the report. For me it is workng now.
