### ISSUE TITLE
How to use ssl created by open-ssl?

### ISSUE THREAD

**Issue by BigGitWorld** [moquette-io/moquette#407]
I'm going to use SSL for Moquette.
My clients are not in JAVA. So I couldn't use .jks file.
I have a .pem file in clients.
how can I use this .pem file while mqtt broker is written by java (Moquette)?

**Comment by andsel** [comment]
@BigGitWorld I don't have tried, but stackoverflow suggests:

```
openssl x509 -outform der -in certificate.pem -out certificate.der
keytool -import -alias your-alias -keystore cacerts -file certificate.der
```

https://stackoverflow.com/questions/2138940/import-pem-into-java-key-store
