### ISSUE TITLE
Why is repeating  "Flushing idle Netty channel..." for a clientId

### ISSUE THREAD

**Issue by BigGitWorld** [moquette-io/moquette#409]
Hi.
I'm using moquette and it's working perfectly.
But I have a question.
why the following log is repeating for a client?
```
[nioEventLoopGroup-3-8] DEBUG AutoFlushHandler  - Flushing idle Netty channel. MqttClientId = ...
```

**Comment by andsel** [comment]
Hi @BigGitWorld Moquette has an AutoFlushHandler, that has the meaning to flush (invoking the syscall, so slows down the entire pipeline) data once the channel go in idle state (meaning that no writes or reads are done), this is necessary when the broker writes something and it's not sufficient to fill channel buffers to get flushed automatically, so we need to grant that every write doesn't stale date. 
This is probably a too verbose log

**Comment by davidgraeff** [comment]
Is it fixed or can the log be disabled in recent versions?

**Comment by andsel** [comment]
Hi @davidgraeff  here is nothing to fix, probably I should lower the log level for AutoFlushHandler to TRACE. In the meanwhile you can configure you log4j.properties to put AutoFlushHandler at INFO level
