### ISSUE TITLE
Protocol Violation UNSUBACK

### ISSUE THREAD

**Issue by ckrey** [moquette-io/moquette#410]
### Expected behavior

UNSUBACK is hex `B0xxxx`

### Actual behavior
UNSUBACK is hex `B2xxxx`

### Steps to reproduce

send any UNSUBSCRIBE to moquette

### Moquette MQTT version
0.11

### OS version (e.g. `uname -a`)

see http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.pdf pp 17-18

**Comment by andsel** [comment]
Fixed with ea0ad14374856ef93a9a6ed52f7817fee0170568
