### ISSUE TITLE
Protocol Violation PUBLISH accepts zero length topic

### ISSUE THREAD

**Issue by ckrey** [moquette-io/moquette#412]
### Expected behavior
Connection close

### Actual behavior
accept and publish to subscribers with '#' topicfilter

### Steps to reproduce

publish a message with zero length topic

### Moquette MQTT version
0.11

### OS version (e.g. `uname -a`)

> All Topic Names and Topic Filters MUST be at least one character long [MQTT-4.7.3-1]
see All Topic Names and Topic Filters MUST be at least one character long [MQTT-4.7.3-1] p 58

**Comment by andsel** [comment]
Fixed with 4dff5b51ebef14f091e20bfdb9c0d0fbc31f7173

**Comment by ckrey** [comment]
I re-tested and found the new check is performed only in QoS1, not for QoS0 or QoS2
