### ISSUE TITLE
H2 and MapDB persistance classes in 0.11

### ISSUE THREAD

**Issue by hylkevds** [moquette-io/moquette#420]
I'm using moquette-broker embedded in a project, but it seems the jar file (https://jcenter.bintray.com/io/moquette/moquette-broker/0.11/:moquette-broker-0.11.jar) does not contain the H2 or MapDB persistence classes. Are those available as a separate dependency? I've not found them on bintray.

**Comment by andsel** [comment]
As described in [docs](http://andsel.github.io/moquette/documentation.html) you should include the bintray jcenter repos in your maven pom.xml

`<repositories>
  <repository>
    <id>bintray</id>
    <url>https://jcenter.bintray.com</url>
    <releases>
      <enabled>true</enabled>
    </releases>
    <snapshots>
      <enabled>false</enabled>
    </snapshots>
  </repository>
</repositories>`

And then you have to include the H2  https://dl.bintray.com/andsel/maven/io/moquette/moquette-h2-storage/0.11/
OR the MapDB https://dl.bintray.com/andsel/maven/io/moquette/moquette-mapdb-storage/0.11/

**Comment by hylkevds** [comment]
That's the problem.
`https://dl.bintray.com/andsel/maven`
is not 
`https://jcenter.bintray.com`
So adding the jcenter repository, as documented, just gives me a "Could not resolve dependencies", since these two are not in the jcenter repository. You probably should update the docs to point to your personal bintray repository, or get these two jars added to the jcenter repository.

**Comment by andsel** [comment]
Mmm oks, you spotted my fault I haven't published it sorry.
