### ISSUE TITLE
cluster will not be supported

### ISSUE THREAD

**Issue by Xwiam** [moquette-io/moquette#424]
"Dropper Hazelcast because Moquette is not designed to be clusterizable" 
does that mean moquette will not support cluster

**Comment by andsel** [comment]
No, means that the current implementation was just a publish forwarder not
a real distributed version. Now the main objective is to be mqtt5 compliant
and clean the internal modeling of the broker, then comes HA and there I'll
see if clustering is simple enough to implement.
Andrea

Il mer 25 lug 2018, 10:42 Xwiam <notifications@github.com> ha scritto:
