### ISSUE TITLE
Disable topic scanning ?!

### ISSUE THREAD

**Issue by ricardojlrufino** [moquette-io/moquette#426]
How to disable topic scanning ?

Using MQTTfx this will can scan active connections...

**Comment by ricardojlrufino** [comment]
![image](https://user-images.githubusercontent.com/515675/43436446-ed4436d2-945a-11e8-88d2-b1225238334b.png)

**Comment by andsel** [comment]
How is this related to Moquette if it's a functionality offered by MQTT.fx?
 Andrea

Il mar 31 lug 2018, 05:44 Ricardo JL Rufino <notifications@github.com> ha
scritto:

**Comment by ricardojlrufino** [comment]
I would like to know if I can block

I think I figured out how to block ... I'm going to take the test

**Comment by andsel** [comment]
On the sever side is not possible, because the broker hasn't any mechanism
to understand this scanning, but what scanning means? The client subscribe
to # topic, or try to subscribe in brute forcing?

Il gio 2 ago 2018, 02:51 Ricardo JL Rufino <notifications@github.com> ha
scritto:

**Comment by ricardojlrufino** [comment]
I think that the client subscribe to # topic .

**Comment by andsel** [comment]
Oks, this could be a configuration variable to prohibit clients can
subscribe to # topic
 Andrea

**Comment by ricardojlrufino** [comment]
For now I have blocked using: IAuthorizator
