### ISSUE TITLE
start with spring boot

### ISSUE THREAD

**Issue by Tinet-wangll** [moquette-io/moquette#429]
I like moquette and when it can start wiht spring boot

**Comment by andsel** [comment]
What do you mean with "when it can start with spring boot"? If you need to
embed it, include as library in your pom and then wrap it in a service and
provide destroy and init methods.
 Andrea

Il lun 3 set 2018, 15:33 王立力 <notifications@github.com> ha scritto:

**Comment by rpahli** [comment]
include 
`compile(group: 'io.moquette', name: 'moquette-broker', version: '0.11')`

and for example as CommandLineRunner:
```
	@Bean
	CommandLineRunner commandLineRunner() {
		return args -> {
			Properties properties = new Properties();
			MemoryConfig config = new MemoryConfig(properties);
			Server mqttBroker = new Server();
			mqttBroker.startServer(config);
			Runtime.getRuntime().addShutdownHook(new Thread(mqttBroker::stopServer));
		};
	}
```
