### ISSUE TITLE
Fail to handle invalid subscription.

### ISSUE THREAD

**Issue by bobwenx** [moquette-io/moquette#43]
If MQTT client simply send a SUBSCRIBE request with invalid topic string(like this one: `#MQTTClient`). 
Then the `moquette` server will just throw a exception on console/log, without close client's connection and rollback internal status.

Note: we cannot assume client will validate topic string before send to server. if client don't do it, the server's internal status will be incorrect.

**Comment by andsel** [comment]
Good catch, fixed with 867d78b65019ca9e0275b16c0d650ec77746ead5
