### ISSUE TITLE
MQTTMessageLogger: Wrong logger class

### ISSUE THREAD

**Issue by davidgraeff** [moquette-io/moquette#437]
https://github.com/andsel/moquette/blob/1ba9eb3613bc79d28c5d45d9c0984033d36d83af/broker/src/main/java/io/moquette/broker/metrics/MQTTMessageLogger.java#L41

**Comment by davidgraeff** [comment]
My PR #432 is unfortunately invalid now after the refactoring

**Comment by andsel** [comment]
Thanks, you are right  checked in with 2416347beadf1c571a621a950f7bfb1406d928b1
