### ISSUE TITLE
notifyClientConnected and notifyClientDisconnected not called ?

### ISSUE THREAD

**Issue by starofys** [moquette-io/moquette#439]
https://github.com/andsel/moquette/blob/b4418c040c8498aa56db26ae047796f54da390f8/broker/src/main/java/io/moquette/broker/MQTTConnection.java#L244

how to know the client is disconnect?

**Comment by andsel** [comment]
Sorry @microxdd but which the precise question? This method ins called by the NewNettyMQTTHandler when the channel becomes inactive.

**Comment by starofys** [comment]
sorry about my bad english. 
I upgrade from 0.11 to 0.12 but i found the InterceptHandler onConnect and onConnectionLost not called.
I searched all the source code  and found the BrokerInterceptor notifyClientConnected and  notifyClientDisconnected never be used.

**Comment by hylkevds** [comment]
I just ran into the same issue.
`BrokerInterceptor.notifyClientConnected` and `BrokerInterceptor.notifyClientDisconnected` are only called in the Test `BrokerInterceptorTest`, never by the server.

`BrokerInterceptor.notifyClientConnectionLost` and `BrokerInterceptor.notifyMessageAcknowledged` are never called at all, not even by tests.

**Comment by andsel** [comment]
Solved by PR #445  (commit ea06315 )

**Comment by hackbar** [comment]
Can you do release? I don't see the fixed version on maven central yet.

**Comment by andsel** [comment]
The release is not yet ready
