### ISSUE TITLE
Check whether client is valid before close old channel with same clientID.

### ISSUE THREAD

**Issue by bobwenx** [moquette-io/moquette#44]
The CONNECT message process code: `ProtocolProcessor.processConnect` will first try to close presented connection if it has same clientID with current requester:

```
void processConnect(ServerChannel session, ConnectMessage msg) {

    // it should check requester first before close old connection
    if( m_clientIDs.contains(requester.clientID)){
      //  close old connection here
    }

    if (authenticator != null && !authenticator.checkValid(msg.isUserFlag() ? msg.getUsername() : null, msg.isPasswordFlag() ? msg.getPassword().toCharArray() : null))
    { 
            // ...
    }
}
```

 it probably more reasonable to first check whether current requester is valid. because this can prevent evil client(without get authorized) to break exist connection.

**Comment by andsel** [comment]
Fixed with commit 5416a8714955b163e6bdb31add1edfec6f2e7055
