### ISSUE TITLE
PermitAllAuthorizatorPolicy is same as DenyAllAuthorizatorPolicy, their methods all return true. In the fact, methods in DenyAllAuthorizatorPolicy should return false.

### ISSUE THREAD

**Issue by zhangliangbo** [moquette-io/moquette#443]

**Comment by mtsoleimani** [comment]
Hi,
Moquette  is great Java QMTT Broker :) 
I've forked it and start a new project called [Cassandana](https://github.com/mtsoleimani/cassandana)
features  are including:
- MQTT compliant broker.
- Supports QoS 0, QoS 1 and QoS 2
- TLS (SSL) Encryption
- PostgreSQL, MySQL and MongoDB Authentication and Authorization
- Supports Cassandra for Authentication, Authorization and Message Archiving
- Supports HTTP REST API for Authentication and Authorization
- Supports Redis for Authentication
- Supports Inmemory caching mechanism to reduce I/O operations
- MQTT message archiver (Silo ported to Cassandana)
- Easy configurable (YAML based)
- Supports WebSocket

**Comment by andsel** [comment]
@mtsoleimani write in maiing list or write me directly is not polite to post things not related to this issue

**Comment by andsel** [comment]
@zhangliangbo the issue misses the mandatory requested attributes:
- Expected behavior
- Actual behavior
- Steps to reproduce
- Minimal yet complete reproducer code (or URL to code) or complete log file
- Moquette MQTT version

**Comment by andsel** [comment]
Closed with PR #445
