### ISSUE TITLE
How to modified log messages in mqtt broker server

### ISSUE THREAD

**Issue by bhaskar-516** [moquette-io/moquette#447]

**Comment by bhaskar-516** [comment]
Please any one help me out how to change log messages in MQTT broker server
Ex:  Client mosqpub/5324-cntdev-HP- received CONNACK
How can i modified CONNACK message to something else?

**Comment by andsel** [comment]
I can't understand what you need. That string is on the code and says
simply that the broker received a connect acknowledgment.

Il giorno mer 23 gen 2019, 06:09 bhaskar-516 <notifications@github.com> ha
scritto:

**Comment by bhaskar-516** [comment]
In Which file that code is available because i need add my custom message there

**Comment by andsel** [comment]
Grep it?

Il giorno mer 23 gen 2019, 07:41 bhaskar-516 <notifications@github.com> ha
scritto:

**Comment by bhaskar-516** [comment]
I didn't understand
I need one thing in which file that code is available for change the response messages

**Comment by andsel** [comment]
Clone the repo on your local machine and grep/search the code base for that
string, it simple!

Il giorno mer 23 gen 2019, 07:53 bhaskar-516 <notifications@github.com> ha
scritto:

**Comment by andsel** [comment]
Usually moquette.log file contains line in the format:
```
21:54:33,057 [main] INFO  CTrieSubscriptionDirectory 33  - Initializing CTrie
21:54:33,057 [main] INFO  CTrieSubscriptionDirectory 36  - Initializing subscriptions store...
```
where you can find the class and line of the log lines, there is where you should make your change

**Comment by bhaskar-516** [comment]
Yeah i understand this one ,but my doubt is if i subscribe a topic after getting response how can i customize that response like below one:
mosquitto_pub -m "message from mosquitto_pub client" -t /sensors/anemometer  -u "testuser" -P "password" -d
Client mosqpub/5653-cntdev-HP- sending CONNECT
Client mosqpub/5653-cntdev-HP- received CONNACK
Client mosqpub/5653-cntdev-HP- sending PUBLISH (d0, q0, r0, m1, '/sensors/anemometer', ... (33 bytes))
Client mosqpub/5653-cntdev-HP- sending DISCONNECT

In above one i need to change the log message from CONNACK to CONNECT
how can i solve this problem

**Comment by andsel** [comment]
But are you sure that this log come from Moquette and instead is the output
of Mosquito pub client application?

Il giorno gio 24 gen 2019, 07:06 bhaskar-516 <notifications@github.com> ha
scritto:

**Comment by bhaskar-516** [comment]
yeah sure because in your code that messages are not available
in Mosquitto server only those messages are coming

**Comment by andsel** [comment]
Close it because not Moquette related
