### ISSUE TITLE
Check connection status of client endpoint from broker

### ISSUE THREAD

**Issue by artiaj** [moquette-io/moquette#448]
### Expected behavior
The older version(v 0.11) of the Server class had a method getConnectionsManager() to the connection manager of broker and through it we could get the list of connected clients in the broker at a stage. This method is no more present in version 0.12. How this has been changed in new version?
### Actual behavior
There is no method found get the list of connected clients
### Minimal yet complete reproducer code (or URL to code) or complete log file
Earlier the code snippet was:
Collection<String> listOfConnectedEPs= server.getConnectionsManager().getConnectedClients();
### Moquette MQTT version
v 0.12
### JVM version (e.g. `java -version`)
Java 8
### OS version (e.g. `uname -a`)
Windows 7

**Comment by andsel** [comment]
Fixed in version 0.12.1
b827ad446d4f6f17d5240f0c4756861dbc795619
