### ISSUE TITLE
EADDRNOTAVAIL (Cannot assign requested address)

### ISSUE THREAD

**Issue by gnuhel** [moquette-io/moquette#45]
Hi,

I tried to setup MQTT Broker on an android devices. But I always get this error
java.net.BindException: bind failed: EADDRNOTAVAIL (Cannot assign requested address)

Should I change HOST "0.0.0.0" to a new local ip like "192.168.178.111"?

**Comment by andsel** [comment]
At the Moquette doesn't support Android but someone tried to port it, check https://github.com/interaktionsbyran/moquette.

Binding to the local IP is not a good solution, probably because every time you connect to wireless connection it changes.

**Comment by gnuhel** [comment]
thank for the reply.
so what should set for host? or should it be the device ip?

**Comment by gnuhel** [comment]
I know about the library https://github.com/interaktionsbyran/moquette
but it have the same problem about the host. What kind of value should I put it there?

**Comment by gnuhel** [comment]
ok i tried it with the device IP and it works. Thanks for your help.

**Comment by LiangCan** [comment]
I also found the type of problem, but I solved the problem by modifying the port of  ，
It may be 1883 or 8080 is occupied
