### ISSUE TITLE
Does moquette verify the common name(CN) and the client id during the connection process

### ISSUE THREAD

**Issue by artiaj** [moquette-io/moquette#457]
I had a query which I wanted to clarify . Does moquette verify that common name(CN) and the client id match during the connection process (when a 2 way SSL is set up X.509 certificate). We tried it but it doesn't seem to check. Could you please confirm. Is there a way we can add this check?

### Moquette MQTT version
V 0.11

**Comment by andsel** [comment]
Moquette doesn't check CN during SSL connection. Should it do?

**Comment by artiaj** [comment]
Hi,

Yes , actually most of the broker (eg. hivemq) , do provide this functionality where it checks the common name of the device certificate to match with the client identifier and SSL context should actually be checking this.
