### ISSUE TITLE
1 minute seup - BinTray - Unavailable

### ISSUE THREAD

**Issue by ghost** [moquette-io/moquette#460]
Hi,

### Expected behavior
I need to install Moquette on my already running Raspberry Pi image

### Actual behavior
Bin Tray unavailable for installation

### Steps to reproduce
Try to click on your Github Bin Tray hyperlink : https://github.com/moquette-io/moquette

### Minimal yet complete reproducer code (or URL to code) or complete log file
Page 404 at https://bintray.com/artifact/download/andsel/generic/moquette-0.12.1.tar.gz
### Moquette MQTT version
Last one expected

### OS version (e.g. `uname -a`)
(Raspbian based on Raspberry Pi)
Linux kalliope 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux

**Comment by andsel** [comment]
Thanks for notice now it's ok
