### ISSUE TITLE
Deploy -javadoc and -source jars

### ISSUE THREAD

**Issue by joker1** [moquette-io/moquette#465]
### Expected behavior
Build script deploys -javadoc and -source jar files to maven repository

### Actual behavior
No -javadoc or -source jars are deployed

Deploying these jar files would make it easier to use the code in eclipse or any other ide that supports automatically downloading sources and javadoc from maven repository.

**Comment by hylkevds** [comment]
Since Moquette moved to maven central, javadoc and sources are now automatically published properly.
