### ISSUE TITLE
doesn't work with apache Httpd2.4?

### ISSUE THREAD

**Issue by cleverpig** [moquette-io/moquette#471]
It support for apache Httpd2.4's websocket proxy module?

I try it use as this, but failed:
ProxyPass /mqtt ws://IP:18083/mqtt
ProxyPassReverse /mqtt ws://IP:18083/mqtt

My moquette MQTT version is 0.12.

**Comment by andsel** [comment]
Sorry, could you explain better the setup?
You have an Apache that proxies websocket connections to Moquette right?
Is your Moquette listening on port 18083?
If you connect directly to your moquette with websocket client what you get?

**Comment by cleverpig** [comment]
Thank @andsel 
I'd find way!

It's use contextPath parameter when paho.js was initialized.

`client = new Paho.Client(BROKER_HOST, BROKER_PORT, "/mqtt",CLI_ID);`

And set apache httpd with websocket tunnel to meet above:

<VirtualHost *:80>
	...
	ProxyPass /mqtt ws://127.0.0.1:18083/mqtt
	ProxyPassReverse /mqtt ws://127.0.0.1:18083/mqtt
        ...
</VirtualHost>
