### ISSUE TITLE
Subscribe to topics with wildcards

### ISSUE THREAD

**Issue by BigGitWorld** [moquette-io/moquette#476]
### Moquette MQTT version
v 0.12
### JVM version (e.g. `java -version`)
java 1.8
### OS version (e.g. `uname -a`)
Ubuntu 16.04
**Question :** 
How can I subscribe to a general topic that contains wildcards?
for example I want to subscribe to : /sensor/+/temperature
so that  any string with 8 character length can be replaced by +.

**Comment by andsel** [comment]
Use the wildcard, Moquette in compliant with + and # wildcards
# must be used  as latest in the tpic filter
+ could be used at any level

Il mar 7 mag 2019, 15:04 unknown <notifications@github.com> ha scritto:

**Comment by BigGitWorld** [comment]
@andsel 
Thank you.
