### ISSUE TITLE
Plans to support MQTT 5?

### ISSUE THREAD

**Issue by mpe85** [moquette-io/moquette#490]
Are there any plans to support the latest specification version 5?

**Comment by andsel** [comment]
Yes
I'm working on it, in my spare time.

 Andrea

**Comment by mpe85** [comment]
Thats great to hear :-)
Thanks for the quick answer.

**Comment by andsel** [comment]
Your're welcome,
but the implementation will take time;-)

 Andrea

**Comment by MuhammadMattiullah** [comment]
Hello Andsel, is it supporting mqtt v5 ?

**Comment by andsel** [comment]
Hi  Muhammad
not at the moment, it's still work in progress.

 Andrea

**Comment by MuhammadMattiullah** [comment]
Thanks for the quick response. 
Regards

**Comment by keshavck** [comment]
Any update on this? looking for MQTT 5 asap.

**Comment by andsel** [comment]
@keshavck not yet

**Comment by keshavck** [comment]
Any other workaround? like any adapters to mqtt 3 to mqtt 5?

**Comment by andsel** [comment]
> Any other workaround?

Nothing I'm aware off, simply use MQTT 3.1.1  client to connect to Moquette

> like any adapters to mqtt 3 to mqtt 5?

There could be something, but never tried. It's out of the project's scope

**Comment by andsel** [comment]
I close this because created #695 to shape the work to be done to support MQTT v5
