### ISSUE TITLE
[Q] Embeded server. How to subscribe internal consumer

### ISSUE THREAD

**Issue by bademux** [moquette-io/moquette#493]
Hello,

I found io.moquette.broker.Server#internalPublish for publishing messages, but can't find callback for subscription to the topics.
I use moquette entirely embedded server + a little logic outside and it will be a overkill to use mqtt client internally.

Thanks for the great project!

**Comment by andsel** [comment]
Give a look at AbstractInterceptHandler class and also to this github
sample module project that embed Moquette (
https://github.com/moquette-io/moquette/tree/master/embedding_moquette)

You have to use the Intercpetor classes, implement them and add to moquette
in init

Thanks :-)
 Andrea

**Comment by bademux** [comment]
Thanks for fast answer.
Looks like I misunderstand comment "The events can act only as observers." for class ```io.moquette.interception.InterceptHandler```.

Will ```InterceptHandler#onPublish ``` act like normal (external) consumer that is subscribed to a topic?

Sorry if I mess with a question.

**Comment by andsel** [comment]
No it's not a consumer like a client subscribed to  the topic, but should
be intended only as a callback mechanism that in my original intent can't
do active decision logic to determine if a message should or shouldn't
published or manipulated in any way.

**Comment by bademux** [comment]
Is there an API (or maybe some internals) to inject subscriber code along with acknowledgements? My intent is to omit network communication as well as auth (it also be nice to omit serialization) while trigger proper message deletion from the queue after message received by internal subscriber.

**Comment by bademux** [comment]
Looks like the best way is to use MQTT client.

Thanks again!

PS. Can you please recommend tiny mqtt netty-based client?
