### ISSUE TITLE
Question : Persistent session in Moquette

### ISSUE THREAD

**Issue by BigGitWorld** [moquette-io/moquette#494]
### Expected behavior
When a subscriber connects to a MQTT broker, it needs to create subscriptions for all topics that it is interested in, in order to receive messages from the broker. Also on the reconnect, these topics are lost and the client needs to subscribe again. This is the normal behavior with no persistent session. 
But for constrained clients with limited resources it would be a burden to subscribe again each time they lose the connection. So a persistent session saves all information relevant for the client on the broker. 

### Actual behavior
Do the Moquette broker supports this concept?

**Comment by andsel** [comment]
Use clean session false when you connect. It's standard piece of MQTT
protocol and Moquette support it.

Il sab 3 ago 2019, 07:28 unknown <notifications@github.com> ha scritto:
