### ISSUE TITLE
Broker not working for Android API greater than 26

### ISSUE THREAD

**Issue by salmanshkt** [moquette-io/moquette#514]
### Actual behavior
I am getting following exception when trying to start broker on android device >  API 26. Otherwise the broker is working fine on older android versions.

    java.lang.RuntimeException: Could not instantiate class    at org.mapdb.SerializerPojo.deserializeUnknownHeader(SerializerPojo.java:483)
### Minimal yet complete reproducer code (or URL to code) or complete log file
    public void startMqttBroker() {
        moquetteMqttBroker = new io.moquette.server.Server();
        try {
            MemoryConfig memoryConfig = new MemoryConfig(new Properties());
            memoryConfig.setProperty(BrokerConstants.PERSISTENT_STORE_PROPERTY_NAME, Environment.getExternalStorageDirectory().getAbsolutePath()+ File.separator + BrokerConstants.DEFAULT_MOQUETTE_STORE_MAP_DB_FILENAME);
            moquetteMqttBroker.startServer(memoryConfig);
     
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

### Moquette MQTT version
0.8.1

### OS version (e.g. `uname -a`)
Android API 28

**Comment by andsel** [comment]
Moquette support only JDK not Android

**Comment by mikebertiean** [comment]
Any luck with getting this going on Android?
