### ISSUE TITLE
Publish message takes 1 second to arrive on consumer

### ISSUE THREAD

**Issue by janssk1** [moquette-io/moquette#515]
### Expected behavior
Once a message is published, it should appear a quickly as possible at the consumer. Since i'm using moquette in unit tests, latency matters.
### Actual behavior
When publishing a small message, it takes about 1 second before it arrives at the consumer
After digging through the code, flushing seems to be the culprit. There is a hardcoded AutoFlushHandler that flushes every second. Fix might be to make this timeout configurable, or provide a way to flush on each publish

### Minimal yet complete reproducer code (or URL to code) or complete log file
        IResourceLoader classpathLoader = new ClasspathResourceLoader();
        final IConfig classPathConfig = new ResourceLoaderConfig(classpathLoader);

        new Server().startServer(classPathConfig);

        IMqttClient client1 = new MqttClient("tcp://localhost", "client", new MemoryPersistence());

        IMqttClient server = new MqttClient("tcp://localhost", "server", new MemoryPersistence());

        MqttConnectOptions options = new MqttConnectOptions();
        options.setCleanSession(true);
        client1.connect(options);
        server.connect();
        server.subscribe("#");

        BlockingQueue<String> messages = new LinkedBlockingQueue<>();
        server.setCallback(new MqttCallback() {
            @Override
            public void connectionLost(Throwable cause) {

            }

            @Override
            public void messageArrived(String topic, MqttMessage message) throws Exception {
                messages.add(topic);
            }

            @Override
            public void deliveryComplete(IMqttDeliveryToken token) {

            }
        });

        for (int i = 0; i  <100;i++) {
            String aTopic = "aTopic";
            long l = System.currentTimeMillis();
            MqttMessage message = new MqttMessage("".getBytes());
            message.setQos(0);
            client1.publish(aTopic, message);
            String poll = messages.poll(5, TimeUnit.SECONDS);
            Assert.assertThat(poll, CoreMatchers.equalTo(aTopic));
            long latency = System.currentTimeMillis() - l;
            System.out.println("latency = " + latency);
        }
### Moquette MQTT version
0.12.1

**Comment by janssk1** [comment]
Just noticed this is already fixed by https://github.com/moquette-io/moquette/pull/454 
Would be nice get this fix released though..

**Comment by vesense** [comment]
@andsel Do we have a plan to release a new version(maybe 0.13) to include this  #454 ?

**Comment by andsel** [comment]
@vesense nice to see using Moquette in a such an interesting project, I'll try my best to do it, and report here when done

**Comment by vesense** [comment]
Thanks @andsel I'm looking forward to your reply.

**Comment by vesense** [comment]
@andsel It would be even better if you release it to the maven central repo. Thanks.

**Comment by andsel** [comment]
I don't release to maven, only in jcentet.


Il mer 8 apr 2020, 04:06 Xin Wang <notifications@github.com> ha scritto:

**Comment by vesense** [comment]
@andsel Got it, thanks for your reply.

**Comment by andsel** [comment]
Closed with release `0.13`
