### ISSUE TITLE
I tried to build a broker server with my own authentication of users,but it doesn't work

### ISSUE THREAD

**Issue by abcdef123ghi** [moquette-io/moquette#526]
### Expected behavior
validate the username and password when tried to connect to broker

### Actual behavior
didn't validate the username and password
even I set a breakpoint in the validation method,it doen't work any way,it never hit that breakpoint very unfortuantely
### Steps to reproduce
here is my code Main.Java

    public class Main {
	static class PublisherListener extends AbstractInterceptHandler {

		
		 
        @Override
        public String getID() {
            return "EmbeddedLauncherPublishListener";
        }

        @Override
        public void onPublish(InterceptPublishMessage msg) {
        	 final Logger log = Logger.getLogger(PublisherListener.class);
            final String decodedPayload = new String(msg.getPayload().array(), UTF_8);
            System.out.println("Received on topic: " + msg.getTopicName() + " content: " + decodedPayload);
            log.info("Received on topic: " + msg.getTopicName() + " content: " + decodedPayload);
        }
    }

       public static void main(String[] args) throws InterruptedException, IOException {
      
    	org.apache.log4j.BasicConfigurator.configure();
    	 final Logger log = Logger.getLogger(PublisherListener.class);
    	IResourceLoader classpathLoader = new ClasspathResourceLoader();
        final IConfig classPathConfig = new ResourceLoaderConfig(classpathLoader);

        final Server mqttBroker = new Server();
        List<? extends InterceptHandler> userHandlers = Collections.singletonList(new PublisherListener());
        mqttBroker.startServer(classPathConfig, userHandlers);

        System.out.println("Broker started press [CTRL+C] to stop");
        log.info("Broker started press [CTRL+C] to stop");
        //Bind  a shutdown hook
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            System.out.println("Stopping broker");
            log.info("Stopping broker");
            mqttBroker.stopServer();
            System.out.println("Broker stopped");
            log.info("Broker stopped");
        }));

        Thread.sleep(20000);
        System.out.println("Before self publish");
        log.info("Before self publish");
        MqttPublishMessage message = MqttMessageBuilders.publish()
            .topicName("/exit")
            .retained(true)
 
            .qos(MqttQoS.EXACTLY_ONCE)
            .payload(Unpooled.copiedBuffer("Hello World!!".getBytes(UTF_8)))
            .build();

        mqttBroker.internalPublish(message, "INTRLPUB");
        System.out.println("After self publish");
        log.info("After self publish");
    }

    private Main() {
    }
	
	
     }

here is my validation code

      public class DBAuthenticator implements IAuthenticator {

	@Override
	public boolean checkValid(String clientId, String username, byte[] password) {
        // Check Username / Password in DB using sqlQuery
		
		  SqlSession sqlSession=null;
          try
          {
       	   sqlSession=SqlSessionFactoryUtil.openSqlSession();
       	   RoleMapper roleMapper=sqlSession.getMapper(RoleMapper.class);
        
       	    Cliword cliword=new Cliword();
       	    cliword.setClino(username);
       	    String passstring=password.toString();
       	    cliword.setClipass(passstring);
       		   
       		 int result=roleMapper.checkUserValidate(cliword);
       	     
       		 if (result>0)
       		 {
       			Loginlog loginlog=new Loginlog();
       			loginlog.setClino(username);
       			roleMapper.insertLoginlog(loginlog);
       		    roleMapper.insertLoginlog(loginlog);
       		    sqlSession.commit();
       		    return true;
       		 }
       		 else
       		 {
       			 Sysexplog sysexplog=new Sysexplog();
       			 String expmsgstr=username+"validate failed";
       			 sysexplog.setExpmsg(expmsgstr);
       			 roleMapper.insertSysexplog(sysexplog);
       		     sqlSession.commit();
       			 return false;
       		 }
       	   
        
          }
          catch(Exception ex)
          {
        	  Additionalog addtionlog=new Additionalog();
        	  try
        	  {
        		 
        		  String expstr="username"+username+"has exception ,reason:"+ex.toString();
        		  addtionlog.logtofile(expstr);
        		  String topic="username:"+username+" was not able to log file";
        		  addtionlog.sendmyemail(topic, expstr);
       	       
        	  }
        	  catch (Exception e)
        	  {
        		  String expstr="username"+username+"has exception:"+ex.toString()+"，reason was "+e.toString();
        		  addtionlog.logtofile(expstr);
        		  
        	  }
        	  sqlSession.rollback();
       	      return false;
          }
          finally{
       	   if (sqlSession!=null)
       		   sqlSession.close();
       			   
          }  
       
      }
     }

### OS version (e.g. `uname -a`) 

any idea?any helps would be apperciated

**Comment by hylkevds** [comment]
You don't seem to be passing your DBAuthenticator to the broken when you start it. So the broker doesn't know of your authentication code.

You need to use the method:
```
mqttBroker.startServer(
    IConfig config,
    List<? extends InterceptHandler> handlers,
    ISslContextCreator sslCtxCreator,
    IAuthenticator authenticator,
    IAuthorizatorPolicy authorizatorPolicy)
```
to start the broker

**Comment by abcdef123ghi** [comment]
> You don't seem to be passing your DBAuthenticator to the broken when you start it. So the broker doesn't know of your authentication code.
> 
> You need to use the method:
> 
> ```
> mqttBroker.startServer(
>     IConfig config,
>     List<? extends InterceptHandler> handlers,
>     ISslContextCreator sslCtxCreator,
>     IAuthenticator authenticator,
>     IAuthorizatorPolicy authorizatorPolicy)
> ```
> 
> to start the broker

thank you so much

**Comment by abcdef123ghi** [comment]
I have googled a bunch of web pages,I didn't find any useful information,I really appericated your helps
