### ISSUE TITLE
Publish javadoc & sources of 0.13

### ISSUE THREAD

**Issue by hylkevds** [moquette-io/moquette#528]
It seems something went wrong during the publication of 0.13 to the bintray repository. The sources jar is missing:
https://jcenter.bintray.com/io/moquette/moquette-broker/0.13/

Though I just noticed they are also missing for 0.12.
0.11 does have sources.

**Comment by andsel** [comment]
Fixed with commit https://github.com/moquette-io/moquette/commit/3f54b59688d237896145ddfd00b1aaf3afbf0489
