### ISSUE TITLE
No heartbeat support 

### ISSUE THREAD

**Issue by RafficMaleo** [moquette-io/moquette#53]
No heartbeat support , i tried with this mqtt android library https://github.com/chinesejie/paho-for-android and it keeps breaking the code.

**Comment by andsel** [comment]
It's not clear what this issue point to. What do you mean for "no heartbeat
support" the ping messages? Do you have tried with the official Paho client
from Eclipse?
Il giorno 21/giu/2015 20:09, "Raffic Maleo" notifications@github.com ha
scritto:

**Comment by RafficMaleo** [comment]
Hello Andrea,

Moquette works well with Paho client from Eclipse.

but the issue with Paho client from Eclipse is that it loses the connection
to the mqtt broker when android is in sleep mode. so the paho-for-android
https://github.com/chinesejie/paho-for-android
library is a modified version on Paho client that send ping request at
specific intervals to the broker so that the broker will not close the
connection when android is in sleep mode.

so far paho-for-android https://github.com/chinesejie/paho-for-android
works well with mosquitto .

When i tried the paho-for-android library on moquette. the intial
'handshake' is fine , but the subsequent ping request from the
paho-for-android is terminated , thus closing the connection.

https://github.com/chinesejie/paho-for-android

**Comment by andsel** [comment]
Hi Raffic,
Have you got the moquette log to post here so i could check what's happened on Moquette side, or pcap dump of the session between the client and the broker?

**Comment by andsel** [comment]
Hi Raffic,
Have you got the moquette log to post here so i could check what's happened on Moquette side, or pcap dump of the session between the client and the broker?

**Comment by andsel** [comment]
Can't reproduce and the issue signaler didn't provided the requested information, issue closed.
