### ISSUE TITLE
Mqtt websocket http

### ISSUE THREAD

**Issue by strautins** [moquette-io/moquette#538]
Hello,
Trying to understand http api for moquette broker.

Can somebody give me documentation info of how to post on http mqtt messages to moquette?
With client id, login, password etc.

`WEB_SOCKET_PORT_PROPERTY_NAME = "websocket_port";`
` WEB_SOCKET_PATH_PROPERTY_NAME = "websocket_path";`
so far I get
`ERROR NewNettyMQTTHandler - Unexpected exception while processing MQTT message. Closing Netty channel. CId=null
java.lang.ClassCastException: io.netty.handler.codec.http.HttpObjectAggregator$AggregatedFullHttpRequest cannot be cast to io.netty.handler.codec.mqtt.MqttMessage`

Can't get good info from google,
Thanks

**Comment by strautins** [comment]
Correcting, there is no default http post for mqtt, false info I have got. AWS created their own support. So info how to implement websockets?

**Comment by andsel** [comment]
@strautins Moquette support MQTT over Websocket, this means that it doesn't exposes an ReST API to send data, but once you have opened a websocket channel to Moquette, you have to send MQTT control packets. This configuration is usually used with Javascript clients

**Comment by andsel** [comment]
close this because no interaction from user
