### ISSUE TITLE
Unable to replace existed topic with different cleanSession

### ISSUE THREAD

**Issue by bobwenx** [moquette-io/moquette#55]
The Subscription tree using following code to check whether client are subscribe to same topic with different QOS:

``` java
 // org.eclipse.moquette.spi.impl.subscriptions.TreeNode.java

    void addSubscription(Subscription s) {
        //avoid double registering for same clientID, topic and QoS
        if (m_subscriptions.contains(s)) {
            return;
        }
        //remove existing subscription for same client and topic but different QoS
        ...
    }
```

the problem here: if client send SUBSCRIBE with same clientID, topic and QoS, but different cleanSession Flag(`Subscription.m_cleanSession`). the code will ignore changed cleanSession  flag.

**Comment by andsel** [comment]
Fixed with commit b8af814940a7c29735b337221fa083fe990c963b
