### ISSUE TITLE
subscription matchs performence issues

### ISSUE THREAD

**Issue by tixo** [moquette-io/moquette#59]
hi andsel,
 when I hava more than 10k subscriptions ,  subscriptions match can be a bottleneck on processPublish

**Comment by andsel** [comment]
Do you have a test case where it exposes performance penalties?
 Andrea

**Comment by andsel** [comment]
What do you  mean 10k subscription to the same topic or have 10K differernt topics?

**Comment by andsel** [comment]
The @tixo doesn't answer to my question, without more details I close the issue
