### ISSUE TITLE
 	Support $SYS$ monitoring

### ISSUE THREAD

**Issue by andsel** [moquette-io/moquette#6]
Support $SYS$ monitoring as defined in https://github.com/mqtt/mqtt.github.io/wiki/SYS-Topics

**Comment by halfcoder** [comment]
@andsel This issue was posted almost a year ago. Is this feature still not implemented? And no mechanism preventing clients exchanging messages using $topics?

**Comment by andsel** [comment]
Yes, you are right, it's still not implemented

 Andrea

**Comment by andsel** [comment]
Expired or too old
