### ISSUE TITLE
Using two brokers on One application

### ISSUE THREAD

**Issue by sjpark9** [moquette-io/moquette#60]
Hi 
I've created two brokers with two different port and using different Broker path.

However, it seems it is sharing the same subscription tree. is there anyway to separate this?

Thank you

**Comment by andsel** [comment]
You can use the configuration property "persistent_store" in moquette.conf to use 2 different directories.

**Comment by sjpark9** [comment]
My settings are like below.
Broker 1.
IP : 0.0.0.0
Port : 40000
WEBPORT : 48888
persistent Path : C:/test.mapdb
MQTT_PASS_FILE : null

Broker 2.
IP : 0.0.0.0
Port : 13579
WebPort : 48889
persistent Path C:/one.mapdb
mqtt_pass_file : null

I can see that each mapdb file is made successfully.

However, I can still see that subscription tree is being shared.

Also I connected to each broker and subscribed to same topic. and when I publish to one of the brokers, each client receives the published data.(EX. client 1 is subscribing at broker 1, client 2 is subscribing at broker 2. when I publish to broker 1, i get the message in client 2 as well)

My Moquette version is 0.7 SNAPSHOT

Thank you

**Comment by andsel** [comment]
Could you post here your moquette.conf files, because the path shouldn't have also the indication of file, it should be only a directory

**Comment by sjpark9** [comment]
I am not using config file. I am using Property class to hand over the parameters.
and the parameters that I've put in the Property file is listed above.

Thank you

**Comment by andsel** [comment]
Ok
could you post here the command line with properties definition so I could
try to reproduce it?
Please

**Comment by sjpark9** [comment]
I've done with java.
server = new Server();
        if ( port != null )
            m_properties.put(PORT_PROPERTY_NAME, port);
        else
            throw new Exception("port number error"+port, ModuleType.NET, "ERROR");  
        if ( ip != null)
            m_properties.put(HOST_PROPERTY_NAME, ip);
        else
            m_properties.put(HOST_PROPERTY_NAME, HOST);
        if ( websockport != null && !websockport.equals(port))
            m_properties.put(WEB_SOCKET_PORT_PROPERTY_NAME, websockport);
        if ( passFilePath != null )
            m_properties.put(PASSWORD_FILE_PROPERTY_NAME, passFilePath);
        else
            m_properties.put(PASSWORD_FILE_PROPERTY_NAME, "");
        if ( persistentPath != null)
            m_properties.put(PERSISTENT_STORE_PROPERTY_NAME, persistentPath);
        else
            m_properties.put(PERSISTENT_STORE_PROPERTY_NAME, DEFAULT_PERSISTENT_PATH);
        server.startServer(m_properties);
