### ISSUE TITLE
Why is there no development documentation for this project

### ISSUE THREAD

**Issue by willianfu** [moquette-io/moquette#625]
Where is the documentation for this item that I don't know how to use in my project😥

**Comment by andsel** [comment]
For an example how to embed please check https://github.com/moquette-io/moquette/blob/master/embedding_moquette/src/main/java/io/moquette/testembedded/EmbeddedLauncher.java.

Then you have something at https://moquette-io.github.io/moquette/documentation.html, but no real dev friendly documentation. Definitely  a point to improve.

**Comment by hylkevds** [comment]
FROST-Server is also embedding Moquette. The code for that can be found at: https://github.com/FraunhoferIOSB/FROST-Server/blob/master/FROST-Server.MQTT.Moquette/src/main/java/de/fraunhofer/iosb/ilt/frostserver/mqtt/moquette/MoquetteMqttServer.java

**Comment by andsel** [comment]
No feedback on from issuer
