### ISSUE TITLE
Moquette broker kills parent application if embedded and broker port already used

### ISSUE THREAD

**Issue by mkokoszka-ms** [moquette-io/moquette#641]
### Expected behavior
When moquette is embedded into  other application and defined broker port (e.g. 1833) is already used, server should not start and log message should be generated.
### Actual behavior
When port is already used by something else, moquette broker generates log message "io.moquette.broker.NewNettyAcceptor initFactory Cannot bind to port: 1883". Parent application which uses moquetted is killed by System.exit(1);
Problematic System.exit(1) is here: io.moquette.broker.NewNettyAcceptor.initFactory()
### Steps to reproduce
Start any MQTT Broker on port 1833 and then start moquette broker on the same port.

### Moquette MQTT version
moquette-broker-0.15
### JVM version (e.g. `java -version`)
not relevant
### OS version (e.g. `uname -a`)
not relevant

**Comment by sbaranov-iqmessenger** [comment]
yeah, I encountered the same issue. It would be better to remove `System.exit()` from `NewNettyAcceptor`
