### ISSUE TITLE
Reaction ro incorrect protocol name

### ISSUE THREAD

**Issue by ckrey** [moquette-io/moquette#65]
If moquette receives a connect package with incorrect protocol name, it does "nothing".
While this is in line with the spec, I would expect the server to disconnect.

> [MQTT-3.1.2-1]
> If the protocol name is incorrect the Server MAY disconnect the Client, or it MAY continue processing the CONNECT packet in accordance with some other specification. In the latter case, the Server MUST NOT continue to process the CONNECT packet in line with this specification.

**Comment by andsel** [comment]
Hi Christoph,
I managed to solve the issue, the problem was in the a missed exception catch in that last filter in broker pipeline. So the same origin could be the source also for issue #66.
I wrote a unit test, could you re-test both issues please?
How do you discovered all the 4 issues you opened, do you have an automated conformance test tool?

 Andrea

**Comment by andsel** [comment]
Found by myself I suppose, it's https://eclipse.org/paho/clients/testing/ and then python3 client_test.py?
 Andrea

**Comment by ckrey** [comment]
@andsel I am the creator and maintainer of https://github.com/ckrey/MQTT-Client-Framework, a native Objective-C MQTT client framework for iOS.
I once intended to participate in the MQTT interoperability tests which Eclipse did to ensure protocol conformance between all kind of servers and clients.
The tests I ran are part of the git repo.
The eclipse tests you found are a good start, but test mainly positive test cases, no error conditions or edge cases.

**Comment by ckrey** [comment]
@andsel can you provide me with a new binary, please? I don't know / cannot build from source

**Comment by andsel** [comment]
Hi Christoph,
sure! Bintray is not suited for sharing snapshot versions, how can I share it? Dropbox?

 Andrea

**Comment by ckrey** [comment]
Dropbox for `krey.christoph@gmail.com` would be fine

**Comment by andsel** [comment]
I've shared with you a Dropbox folder named Moquette which contains a snapshot version of the moquette distribution.

**Comment by ckrey** [comment]
retested and fix confirmed
