### ISSUE TITLE
wrong way to get a string out of ByteBuf in src/main/java/io/moquette/testembedded/EmbeddedLauncher.java

### ISSUE THREAD

**Issue by BorisDaich** [moquette-io/moquette#659]
### Expected behavior
in the file 
https://github.com/moquette-io/moquette/blob/main/embedding_moquette/src/main/java/io/moquette/testembedded/EmbeddedLauncher.java

should be 

	/**
		 * has some issue with the dependency on netty
		 * keep throwing java.lang.UnsupportedOperationException: direct buffer
		 */
		@Override
		public synchronized void onPublish(InterceptPublishMessage msg) {
			// this is the correct way to do it from here
			// https://stackoverflow.com/questions/52658774/netty-io-netty-buffer-bytebuf-array-throws-exception-direct-buffer/52659401
			ByteBuf buf = msg.getPayload();
			final String decodedPayload = buf.toString(StandardCharsets.UTF_8);

			System.out.println("Received on topic: " + msg.getTopicName() + " content: " + decodedPayload);
		}
	}

### Actual behavior

 @Override
        public void onPublish(InterceptPublishMessage msg) {
            final String decodedPayload = new String(msg.getPayload().array(), UTF_8);
            System.out.println("Received on topic: " + msg.getTopicName() + " content: " + decodedPayload);
        }
### Steps to reproduce

when running with a message generator that fires a message every second you get 
java.lang.UnsupportedOperationException: direct buffer
 from time to time and than after 10-15 sec constantly

### Moquette MQTT version
0.15 

### JVM version (e.g. `java -version`)
11

### OS version (e.g. `uname -a`)
windows 10

**Comment by hylkevds** [comment]
Indeed, good catch.
There is another spot that can also be simplified by directly using toString(Charset).
