### ISSUE TITLE
 23-character limit for client ID

### ISSUE THREAD

**Issue by ecpandrew** [moquette-io/moquette#668]
I just have a question, 

is there a way to remove the  23-character limit for client ID?

thx

**Comment by hylkevds** [comment]
Currently not. It would need to be be made configurable, and passed as a second parameter to the Netty MqttDecoder:
https://github.com/moquette-io/moquette/blob/2454a8cfc83c0992284a1a0c71df025f7763e5af/broker/src/main/java/io/moquette/broker/NewNettyAcceptor.java#L273

**Comment by hylkevds** [comment]
Actually, I suspect you are using MQTT3.1 and not MQTT 3.1.1.
Simply use MQTT 3.1.1 and you have no ClientId-length issues.

Elaboration: The client-id length is only checked by Netty for MQTT3.1 clients, not for 3.1.1 clients. Moquette itself does not have any client-id length limitations.

**Comment by ecpandrew** [comment]
Thanks for this answer. I'll try to use MQTT3.1 clients, i guess this should solve my problem!

**Comment by ecpandrew** [comment]
Indeed i was using MQTT3.1 , just changed mqtt version on then client and there was no client-id length limitations. Thx
