### ISSUE TITLE
Very small issue: ISessionsStore.wipeSubscriptions() is called twice

### ISSUE THREAD

**Issue by wagnerluis1982** [moquette-io/moquette#69]
I noted that `ISessionsStore.wipeSubscriptions` is called twice unnecessarily. The private method [`ProtocolProcessor.cleanSession`](https://github.com/andsel/moquette/blob/f0a8346ef4b8cfb39c6344dbbf1f3076e33fd759/broker/src/main/java/org/eclipse/moquette/spi/impl/ProtocolProcessor.java#L283), whose definition is written below, calls the first time using `m_sessionsStore.wipeSubscriptions(clientID)` to remove subscriptions from persistence:

``` java
private void cleanSession(String clientID) {
    LOG.info("cleaning old saved subscriptions for client <{}>", clientID);
    //remove from log all subscriptions
    m_sessionsStore.wipeSubscriptions(clientID);
    subscriptions.removeForClient(clientID);

    //remove also the messages stored of type QoS1/2
    m_messagesStore.dropMessagesInSession(clientID);
}
```

In the next line `subscriptions.removeForClient(clientID)` is called for remove subscriptions from volatile memory. However the definition of [`SubscriptionsStore.removeForClient`](https://github.com/andsel/moquette/blob/f0a8346ef4b8cfb39c6344dbbf1f3076e33fd759/broker/src/main/java/org/eclipse/moquette/spi/impl/subscriptions/SubscriptionsStore.java#L193) is:

``` java
public void removeForClient(String clientID) {
    subscriptions.removeClientSubscriptions(clientID);
    //persist the update
    m_sessionsStore.wipeSubscriptions(clientID);
}
```

Note the instruction `m_sessionsStore.wipeSubscriptions(clientID)`. As I could track, the attribute `m_sessionsStore` of `ProtocolProcessor` is the same object of `SubscriptionsStore`, so I can say that the method is called twice.

As the title states, this is not a big issue. It's obvious the broker semantics is not affected for this.

**Comment by andsel** [comment]
Fixed, thanks Luis
