### ISSUE TITLE
Small issue: cleanSession(String clientID)  is not called in processConnectionLost()

### ISSUE THREAD

**Issue by shaman2009** [moquette-io/moquette#70]
I noted that the method [ProtocolProcessor.cleanSession](https://github.com/andsel/moquette/blob/f0a8346ef4b8cfb39c6344dbbf1f3076e33fd759/broker/src/main/java/org/eclipse/moquette/spi/impl/ProtocolProcessor.java#L283) is not called , when [processConnectionLost](https://github.com/andsel/moquette/blob/f0a8346ef4b8cfb39c6344dbbf1f3076e33fd759/broker/src/main/java/org/eclipse/moquette/spi/impl/ProtocolProcessor.java#L562). 

I think it should be called .

Thanks .

**Comment by andsel** [comment]
I don't think so, processing a DISCONNECT message is different from processing an accidental connection lost.
In the first case the will messages hasn't to be fired while in second they must.
In the first you have to manage the clean session flag correctly in the second not, just deactivate the subscriptions.
