### ISSUE TITLE
about remove root

### ISSUE THREAD

**Issue by BEWINDOWEB** [moquette-io/moquette#712]
confused about `version: 0.16` -> `CTrie` -> `remove` method, which goes:
```java
if (cnode.containsOnly(clientId) && topic.isEmpty() && cnode.allChildren().isEmpty()) {
      // last client to leave this node, AND there are no downstream children, remove via TNode tomb
      if (inode == this.root) {
          return inode.compareAndSet(cnode, inode.mainNode().copy()) ? Action.OK : Action.REPEAT;
      }
      TNode tnode = new TNode();
      return inode.compareAndSet(cnode, tnode) ? cleanTomb(inode, iParent) : Action.REPEAT;
 }
```
1. when will `inode == this.root`? topic can't be empty at the beginning
2. why if `inode == this.root`, then do the meaningless CAS ` inode.compareAndSet(cnode, inode.mainNode().copy())` ?

please help on this, thanks :)

**Comment by BEWINDOWEB** [comment]
@andsel 🙏🙏

**Comment by andsel** [comment]
Hi @BEWINDOWEB this change come into play with PR #365 and honestly I don't recall what was the exact reason for the code.

Originally the code was simpler:
```java
if (cnode.containsOnly(clientId)) {
    TNode tnode = new TNode();
    return inode.compareAndSet(cnode, tnode) ? Action.OK : Action.REPEAT;
} else if (cnode.contains(clientId)) {
    CNode updatedCnode = cnode.copy();  
```

that stated as "if a cnode contains only the clientId we I'm removing then replace it with a tombstone".

**Comment by BEWINDOWEB** [comment]
ok, thanks anyway :)
