### ISSUE TITLE
Failed stress test

### ISSUE THREAD

**Issue by diegovisentin** [moquette-io/moquette#79]
Hi,
our simple stress test for MQTT brokers is failed with Moquette. Running with few hundreds clients, many messages are not delivered to the subscribers and some publishers are not able to get a connections. 
Are there some configuration parameters that must be set to handle many devices?
NB:
it runs well using Mosquitto and seems to run without problems with Vertx-mqtt-broker.

**copy this text in a file named "readme.txt"**

```
*** DUMMY STRESS TEST ***

This is a simulation of n devices that subscribe topics to a broker and n*m devices that 
publish messages in the same time.
Devices are simulated by running two PowerShell scripts that use mosquitto utility programs.

From a Windows command line shell, run first the sub script and then the pub script:

    start powershell multisub2.ps1
    start powershell multipub2.ps1

To close all subscriber programs run this utility script:

    start powershell killsub.ps1

```

**copy this text in a file named "multisub2.ps1"**

```
$n = 100

$subcmd = "mosquitto_sub.exe"
$hostname = "localhost"

1..$n | ForEach-Object {
    $supid = $_
    $topic = "s" + $supid
    $id = "m" + $supid + "zspia"
    Start-Process -FilePath $subcmd -ArgumentList "-i $id -h $hostname -t $topic -d"
}
```

**copy this text in a file named "multipub2.ps1"**

```
$n = 100
$m = 5

$datafile = "plzdata.txt"
$data = Get-Content -Path $datafile
$pubcmd = "mosquitto_pub.exe"
$hostname = "localhost"

1..$n | ForEach-Object {
    $supid = $_

    $topic = "s" + $supid
    1..$m | ForEach-Object { 
        $id = "m" + $supid + "z" + $_
        $logfile = $id + ".log"
        $errfile = $id + "_err.log"
        Start-Process -FilePath $pubcmd -ArgumentList "-i $id -h $hostname -f `"$datafile`" -t $topic -d" -RedirectStandardOutput $logfile -RedirectStandardError $errfile
    }
} 
```

**copy this text in a file named "plzdata.txt"**

```
{
        'Info': {
                'RSP': 'OK',
                'TS': '2015-08-05 09:15:58'
        },
        'All Data': {
                'MBTYPE':        0,
                'MAC':           '69:25:44:7E:DC:1B',
                'MOD':         202,
                'VER':         231,
                'FWDATE':        '2015-14-23',
                'XXXXX_DATETIME':'2015-08-05 10:31:24',
                'XXXXX_WDAY':    3,
                'STATUS':        0,
                'SETP':         19.0,
                'PUMP_RATE':     0,
                'YYYYYY_QTUSED': 0,
                'ZZZ_ZZZ1V':     0,
                'ZZZ_ZZZ1RPM':   0,
                'ZZZ_ZZZ2LEVEL': 0,
                'ZZZ_ZZZ2V':     0,
                'POWER':         3,
                'FEEDER':        0.0,
                'DP_TARGET':     0,
                'DP_PRESS':      5,
                'IN_I01':        1,
                'IN_I02':        0,
                'IN_I03':        1,
                'IN_I04':        1,
                'OUT_O01':       0,
                'OUT_O02':       0,
                'OUT_O03':       0,
                'OUT_O04':       0,
                'OUT_O05':       0,
                'OUT_O06':       0,
                'TMP_001':      16.2,
                'TMP_002':      17.2,
                'TMP_003':      21.0,
                'TMP_004':       0.0,
                'TMP_005':       0.0
        }
} 
```

**copy this text in a file named "killsub.ps1"**

```
ps mosquitto_sub | kill
```

**Comment by andsel** [comment]
Hi Diego,
there isn't any specific configuration to set, I've to reproduce the
condition and debug.

 Andrea

**Comment by andsel** [comment]
Hi @diegovisentin  I've created a basic groovy test that do what you suggested (tools_scripts/integration/issue79_stress_multisub.groovy and tools_scripts/integration/issue79_stress_multipub.groovy) and revealed the problem. The issue was due to the fact that every operation on MapDB was followed by a commit,and every commit takes almost 120 ms. This for each connect message (that touched the DB 3 times) introduced a delay of ~360 ms for each connect processing, push some messages really late in the time, and the client resend a connect flooding the server and augmenting the delays. I've solved making commits every 20 seconds, by now it's hardcoded, soon I'll make it configurable.
 Thank you a lot for your signalling, very appreciated.

  Andrea

**Comment by diegovisentin** [comment]
Hi Andrea, 
first of all thanks for your time. 
In many IoT scenario a lost of messages is not an option,  so by using a "commit-task" what happen if the server crashes? 

Ciao, Diego

**Comment by andsel** [comment]
Hi @diegovisentin the server should always cleanly shutdown, so pass always on the shutdown hook that close the storage, flushing to filesystem, at the end it's an fsync that is costly. You find the same behaviour is used also in mosquitto as I know, you cold configure the `autosave_interval` that 0 means flush on exit while the default time is 30 minutes.
 So if the server crash or it's brutally killed last 30 seconds of changes are lost.
