### ISSUE TITLE
java.lang.NoSuchMethodError: No static method encodeHexString([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Hex; or its super classes (declaration of 'org.apache.commons.codec.binary.Hex' appears in /system/framework/org.apache.http.legacy.boot.jar)

### ISSUE THREAD

**Issue by morarafrank** [moquette-io/moquette#812]
### Expected behavior.
I want to encode a string to generate a signature key for authentication header in my android app but it generates this error when this line is called: return Hex.encodeHexString(bytes);

### JVM version (e.g. `java -version`)
Kotlin version 1.7.10

### OS version (e.g. `uname -a`)
Windows 11

**Comment by andsel** [comment]
Hi @morarafrank , the issue is not conform to the required fields, in particular if this is a bug, the section about the reproducible steps is totally missed.
Where this commons codec comes from, it's not part of Moquette libraries.

**Comment by andsel** [comment]
Close this because the issue opener never come back with details.
