### ISSUE TITLE
publish2Subscribers(payload, topic, qos);   catch  Exception    java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by Yunustt** [moquette-io/moquette#820]
According to log tracking, after running for a period of time, it cannot be repeated. When pushing messages, it appears in publish2Subscribers(payload, topic, qos);
Method, can capture the broker will be Java. Lang. NullPointerException: null, but there is no stack information, and the MQTT client connection is not connect

    public void internalPublish(MqttPublishMessage msg) {
        final MqttQoS qos = msg.fixedHeader().qosLevel();
        final Topic topic = new Topic(msg.variableHeader().topicName());
        final ByteBuf payload = msg.payload();
        LOG.info("Sending internal PUBLISH message Topic={}, qos={}", topic, qos);

        publish2Subscribers(payload, topic, qos);
        LOG.info("publish2Subscribers internal PUBLISH message Topic={}, qos={}", topic, qos);
        if (!msg.fixedHeader().isRetain()) {
            return;
        }
        if (qos == AT_MOST_ONCE || msg.payload().readableBytes() == 0) {
            // QoS == 0 && retain => clean old retained
            retainedRepository.cleanRetained(topic);
            return;
        }
        retainedRepository.retain(topic, msg);
    }

**Comment by andsel** [comment]
Hi @Tong-07 thank's for reporting this. Without a stack trace or a debug log it's impossible to understand where the NPE is triggered.

**Comment by Yunustt** [comment]
publish2Subscribers(payload, topic, qos); NPE thrown out in this method, but there is no stack information, so I did not analyze the specific where, through the log, you can know is captured in a function

**Comment by Yunustt** [comment]
Capture the information is a Java. Lang. NullPointerException: null
