### ISSUE TITLE
Request / Response: Formalize the request/response pattern within MQTT 

### ISSUE THREAD

**Issue by andsel** [moquette-io/moquette#829]
Formalize the request/response pattern within MQTT  and provide the Response Topic and Correlation Data properties to allow response messages to be routed back to the publisher of a request. Also, add the ability for the Client to get configuration information from the Server about how to construct the response topics.

## Implementation
Implement the management of `response information` header in CONNACK. When a client send a CONNECT with `request response information` property set, the server reserve a subtree of the subscription topic so that client can receive response publishes for request-response flow.
The server reserve a subtree specific for the connecting (requester) client, for example `/reqresp/reponse/<client id>` and configure read access for the client, and write access for the rest (*). This is needed to automatically provide a response topic configured with correct access rights.

**Comment by hylkevds** [comment]
Great!
I'm looking forward to trying out the request/response implementation soon.
We're currently working on version 2.0 of the OGC SensorThings API, and one of the things we plan on doing is defining how to use the full REST API over the MQTT5 reqest/response mechanism. That would give OData over MQTT. I've always wondered why OASIS didn't to that themselves, given that both are OASIS standards...

**Comment by andsel** [comment]
That's really interesting @hylkevds , please if you find any bug or have suggestion to improve this open an issue.
