### ISSUE TITLE
The shared subscription was not successful.

### ISSUE THREAD

**Issue by jinyuttt** [moquette-io/moquette#839]
### Expected behavior
The shared subscription was not successful. Is there a usage example?

### Actual behavior
Topic: $share/group1/temperature
Introduction:
<dependency>
<groupId>io. moquette</groupId>
<artifactId>moquette broker</artifactId>
<version>0.17</version>
</dependency>
<dependency>
<groupId>org. eclipse. paho</groupId>
<artifactId>org. eclipse. paho. client. mqttv3</artifactId>
<version>1.2.5</versio
### Moquette MQTT version
0.17
### JVM version (e.g. `java -version`)
jdk17
### OS version (e.g. `uname -a`)

windows11

**Comment by andsel** [comment]
Hi @jinyuttt shared subscription is a feature of MQTT5 and Moquette 0.18 is going to support it, which is under active development to be compliant with MQTT5.
