### ISSUE TITLE
 heartbeat detection these do not exist in memory in redis

### ISSUE THREAD

**Issue by Yunustt** [moquette-io/moquette#851]
How to make multiple services, heartbeat detection these do not exist in memory in redis or database can be achieved

**Comment by andsel** [comment]
Hi @Tong-07 could you describe better what you mean for heartbeat detection? Something to check the status of Moquette when it's configured as a (init.d?) service?

**Comment by Yunustt** [comment]
That is to say, when the client times out, it can not use memory detection, and can use other databases to quickly process the detection. The information subscribed to the channel does not exist in the local memory but is placed in the database for easy viewing.

**Comment by andsel** [comment]
So specifically from the broker perspective, once a connection timeout, because it doesn't transmit any data or ping in the keepAlive *1.5 time window, that do you expect from the broker? Should it notify a callback, and in the callback you implement what you need?
Please, state a clear requirement from the broker point of view, so that I can understand better what's needed and if it fits MQTT protocol and broker design.

**Comment by Yunustt** [comment]
For example, if I forward the external port 1883 Layer 4 protocol to multiple brokers, how can the server ensure that the online status of the client is valid, because the network may be delayed, the server will close the session with a heartbeat timeout, but another broker may be connected in the wrong order, resulting in the online status of the client connection is not accurate

**Comment by Yunustt** [comment]
Or is it possible to use the cached database redis or some other way to share the connection data with multiple brokers

**Comment by andsel** [comment]
>For example, if I forward the external port 1883 Layer 4 protocol to multiple brokers, how can the server ensure that the online status of the client is valid, because the network may be delayed, the server will close the session with a heartbeat timeout, but another broker may be connected in the wrong order, resulting in the online status of the client connection is not accurate

Every broker instance has it's own state, is not shared nor spread across multiple instances. You can't create an ensemble of Moquette instances and direct some traffic to one instance and then route to other and pretend that the second broker instance has all the connection statuses that the first instance had.

By the definition of the protocol, MQTT is a session oriented protocol, so at the best you can aim for a sticky session management, if the broker permit to work in cluster, but that's not the case for Moquette.

**Comment by Yunustt** [comment]
The state of each broker instance can not be shared. Can the online state of the session be synchronized?

**Comment by andsel** [comment]
> Can the online state of the session be synchronized?

Moquette is not intended as a distributed broker, so it doesn't have any hook to synchronize or export his internal state. It's not just matter of storing the state in a distributed or central storage, the nodes has to co-operate to provide a single system image, and as of today it's not implemented neither is a goal for the project.

**Comment by Yunustt** [comment]
session_queue_size 
What does this sessionQueueSize do

**Comment by andsel** [comment]
@Tong-07 how this relates to the original question contained in this issue?

**Comment by Yunustt** [comment]
No correlation I just saw that this has a default 1024 size and I wonder what this does

**Comment by andsel** [comment]
Please, don't use same issue to ask multiple unrelated things, open a different issue for each unrelated question.
However, as you can see with a  search https://github.com/search?q=repo%3Amoquette-io%2Fmoquette%20sessionQueueSize&type=code is the size used by `SessionEventLoopGroup` to allocate command queues for each `SessionEventLoop`: https://github.com/moquette-io/moquette/blob/0d22c0dbd897e82e186f328bc60785af6eeaa6b0/broker/src/main/java/io/moquette/broker/SessionEventLoopGroup.java#L27
