### ISSUE TITLE
Documentation Guide

### ISSUE THREAD

**Issue by Jamie98-ie** [moquette-io/moquette#854]
I can't find the documentation guide to set it up and use it. Can anyone help me?

**Comment by andsel** [comment]
Hi @Jamie98-ie starting from https://moquette-io.github.io/moquette/ -> `Documentation` you got to the documentation. It's little bit old, now Moquette is at version 0.18-SNAPSHOT and latest stable is 0.17, but that could be a good starting point.
If you find misses, please write here, I hope to provide more explanations.
