### ISSUE TITLE
onConnectionLost

### ISSUE THREAD

**Issue by Yunustt** [moquette-io/moquette#868]
I have a question. netty detects inactivity and logs out.Why do I need to trigger onConnectionLost after broker onDisconnect

**Comment by andsel** [comment]
@Tong-07 do you mean that after the broker processes a DISCONNECT message your code gets notified of connection lost?

**Comment by Yunustt** [comment]
yes

**Comment by andsel** [comment]
It's because after DISCONNECT the client or the broker closes the connection, and Netty notifies the lost connection.

**Comment by Yunustt** [comment]
I think if the client actively disconnects, is it better for the broker to use a callback listening, netty's notification I understand
