### ISSUE TITLE
Subscription match: Single level wildcard token should not matching parent

### ISSUE THREAD

**Issue by bobwenx** [moquette-io/moquette#87]
According to latest [3.1.1 specification](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/csprd01/mqtt-v3.1.1-csprd01.html#_Toc376954418), section `4.7.1.3 Single level wildcard`: 

```
The plus sign (‘+’ U+002B) is a wildcard character that matches only one topic level. 
For example,  “sport/+” does not match “sport”  but it does match "sport/".
```

However, Current subscription matching code:
`org.eclipse.moquette.spi.impl.subscriptions.TreeNode.matches()` will matching parent even it's a Single level wildcard token:

``` java
void matches(Queue<Token> tokens, List<Subscription> matchingSubs) {
        Token t = tokens.poll();

        //check if t is null <=> tokens finished
        if (t == null) {
            matchingSubs.addAll(m_subscriptions);
            //check if it has got a MULTI child and add its subscriptions
            for (TreeNode n : m_children) {
                if (n.getToken() == Token.MULTI || n.getToken() == Token.SINGLE) {
                    matchingSubs.addAll(n.subscriptions());
                }
            }

            return;
        }
    // others....
}
```

it probably should change to:

``` java
    //check if it has got a MULTI child and add its subscriptions
    for (TreeNode n : m_children) {
          if (n.getToken() == Token.MULTI) {
              matchingSubs.addAll(n.subscriptions());
          }
    }
```

**Comment by bobwenx** [comment]
BTW: what's purpose of The field `m_inflightStore` in MemoryStorageService/MapDBPersistentStore?
it's a unused field and can be safely removed.

**Comment by bobwenx** [comment]
And, what's purpose of adding an empty subscription to client during client connect?

`org.eclipse.moquette.spi.impl.ProtocolProcessor.processConnect`, Line `253`:

```java
 LOG.info("Create persistent session for clientID <{}>", msg.getClientID());
 m_sessionsStore.addNewSubscription(Subscription.createEmptySubscription(msg.getClientID(), true)); //null means EmptySubscription
```

For me, this empty subscription seems meaningless.

**Comment by andsel** [comment]
For the first question I've added a unit test ti validate it, and it work as it's with out any change (look at this https://github.com/andsel/moquette/blob/master/broker/src/test/java/org/eclipse/moquette/spi/impl/subscriptions/SubscriptionsStoreTest.java#L316)
For the second, it's related to issue #86 and essentially the "in flight" at the moment is poorly implemented.
