### ISSUE TITLE
User properties implementation

### ISSUE THREAD

**Issue by andsel** [moquette-io/moquette#876]
## Abstract
Most packets has User Properties. User properties on PUBLISH are included with the message and are defined by the Client applications. The user properties on PUBLISH and Will Properties are forwarded by the Server to the receiver of the message. User properties on the CONNECT, SUBSCRIBE, and UNSUBSCRIBE packets are defined by the Server implementation. The user properties on CONNACK PUBACK, PUBREC, PUBREL, PUBCOMP, SUBACK, UNSUBACK and AUTH packets are defined by the sender, and are unique to the sender implementation. The meaning of user properties is not defined by MQTT.

## Implementation
This implementation focus on implementing user properties for just the PUBLISH and Will message. These properties will be forwarded to the subscribers.
All other user properties are not considered because at the moment the server implementation doesn't define any specification for these. If in a future a use case came up, will be considered.

**Comment by hrjAtLC** [comment]
Can the user properties be queried when intercepting messages? It looks like InterceptPublishMessage doesn't have the implementation yet to do that.
