### ISSUE TITLE
Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received

### ISSUE THREAD

**Issue by erhwenkuo** [moquette-io/moquette#90]
Hi Andsel
I try to use paho javascript library to connect moquette and the browser keep response [WebSocket connection to 'ws://localhost:8080/mqtt' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received].
Then I try to debug what's the root-cause and I found the the second arguments to create WebSocketServerProtocolHandler cause the issue.

``` java
pipeline.addLast("webSocketHandler", new WebSocketServerProtocolHandler("/mqtt"/*"/mqtt"*/, "mqttv3.1, mqttv3.1.1"));
```

According to V3.1.1 spec under [6.1 IANA Considerations], it indicateds the Subprotocol Identifier should be "**mqtt**", so if I modify the source to below:

``` java
pipeline.addLast("webSocketHandler", new WebSocketServerProtocolHandler("/mqtt"/*"/mqtt"*/, "mqtt, mqttv3.1, mqttv3.1.1"));
```

Then netty WebSocketServerProtocolHandler will reponse the acceptance of the SubProtocol back to browser websocket session.

**Comment by andsel** [comment]
Hi @erhwenkuo  if you test with https://github.com/andsel/moquette/blob/master/tools_scripts/integration/web_socket_test.html in your browser, you get the same error?
 I still use Paho.js  and don't get the error, but I've included you suggestion
