### ISSUE TITLE
SubscriptionsStore Initialization problem

### ISSUE THREAD

**Issue by Kracexu** [moquette-io/moquette#92]
I find a problem that all the persistent Subscriptions are rebuilt into the memory with active state true after the broker was restarted.In fact,we should force all the Subscriptions active state false when the broker  was restarted.
I want to publish a message to the subscriber who was not online but has aleardy subscribed the topic after the broker was restarted .the exception is shown as follows
![qq 20150828134036](https://cloud.githubusercontent.com/assets/14014260/9572557/9c442a58-4fe3-11e5-90dd-fd3a5776b2ab.png)

I think we should add this sentence to the class  of org.eclipse.moquette.spi.impl.subscriptions.SubscriptionsStore at the method of init .

-------->subscription.setActive(false)<----------------

```
public void init(ISessionsStore sessionsStore) {
    LOG.debug("init invoked");
    m_sessionsStore = sessionsStore;
    List<Subscription> subscriptions = sessionsStore.listAllSubscriptions();
    // reload any subscriptions persisted
    if (LOG.isDebugEnabled()) {
        LOG.debug("Reloading all stored subscriptions...subscription tree before {}",
                dumpTree());
    }

    for (Subscription subscription : subscriptions) {
        LOG.debug("Re-subscribing {} to topic {}", subscription.getClientId(),
                subscription.getTopicFilter());

        subscription.setActive(false);

        addDirect(subscription);
    }
    if (LOG.isDebugEnabled()) {
        LOG.debug("Finished loading. Subscription tree after {}", dumpTree());
    }
}
```

**Comment by Kracexu** [comment]
I thought this was due to I stop the server directly instead of using the stop method.so the broker can not process the lostconnection event and  the subscription was left in the mapDB with active state true. 
I notice that  you have  already push the active state false after the connection was lost.
code  was shown as follows :
at the class :org.eclipse.moquette.spi.impl.subscriptions.SubscriptionsStore

public void deactivate(String clientID) {
        subscriptions.deactivate(clientID);
        // persist the update
        Set<Subscription> subs = subscriptions.findAllByClientID(clientID);
        m_sessionsStore.updateSubscriptions(clientID, subs);
    }

**Comment by andsel** [comment]
Hi @Kracexu  so was your fault in not cleanly close the broker I can close the issue as not applicable?

**Comment by Kracexu** [comment]
it is due to I close the broker with the eclispe stop button directly.
like this:
![20150908162456](https://cloud.githubusercontent.com/assets/14014260/9730084/945eab24-5646-11e5-9af6-253415b56030.png)
yes,it is not the broker`s bug.
But  if we use the MapDBPersistentStore class,we`d better add the   subscription.setActive(false) sentence to the init method of 
org.eclipse.moquette.spi.impl.subscriptions.SubscriptionsStore  class .

**Comment by andsel** [comment]
Closed as not applicable due to reporter misuse
