### ISSUE TITLE
QOS1 publish NullPointerException [MemoryStorageService]

### ISSUE THREAD

**Issue by Kracexu** [moquette-io/moquette#93]
hi, @andsel .I find that if we use the MemoryStorageService,when  we publish a message with qos1 to the server,a NullPointerException occured.I think we should add this sentence to the removeMessageInSession method of the org.eclipse.moquette.spi.impl.MemoryStorageService class.

![213](https://cloud.githubusercontent.com/assets/14014260/9730398/d634eef8-5648-11e5-83fb-a10191dc0894.png)

it is a Business logic in the MQTT, when we publish a  qos1 message to the subscriber who is active,no PublishEvent will be writen to the  Map<String, List<PublishEvent>> m_persistentMessageStore [MemoryStorageService].And once a pubAck message arrived,the removeMessageInSession method will be called,and the  List<PublishEvent> events = m_persistentMessageStore.get(clientID) will be null;

**Comment by andsel** [comment]
Fixed with 33bc23b4e100ff26b5fd2a8fdb35b228f584423e as MapDBPersistentStore already done.
