### ISSUE TITLE
do not call  m_sessionsStore.wipeSubscriptions(clientID) twice

### ISSUE THREAD

**Issue by Kracexu** [moquette-io/moquette#96]
hi;@andsel,in the cleanSession method  of org.eclipse.moquette.spi.impl.ProtocolProcessor class,
we call the two sentences:
![20150909165453](https://cloud.githubusercontent.com/assets/14014260/9757573/137e78ee-5714-11e5-9fca-687415cf044a.png)
and the subscriptions.removeForClient(clientID) is
   public void removeForClient(String clientID) {
        subscriptions.removeClientSubscriptions(clientID);
        //persist the update
        m_sessionsStore.wipeSubscriptions(clientID);
    }
so that means we call   m_sessionsStore.wipeSubscriptions(clientID) twice;

**Comment by andsel** [comment]
Duplicated of issue #69 as already fix, the line `java m_sessionsStore.wipeSubscriptions(clientID);`  ad line 298 is not more present in ProtocolProcessr
