### ISSUE TITLE
Limit message receiving by permissions from auth

### ISSUE THREAD

**Issue by dant3** [moquette-io/moquette#98]
Hi. I want to restrict my broker in a way that publish will only happen to those people who have specific permission to receive messages from given topics. I know I can't restrict subscriptions due to the way mqtt designed, but I could just make broker don't send messages to those who don't have permissions to read from specified topics. Is this doable with moquette at all and valid in terms of mqtt?
I found that where is a interception api in 0.8-SNAPSHOT but there are no examples of how it could be use so I'm not sure if it fits my goal. Any examples would be welcome.

**Comment by andsel** [comment]
Hi @dant3 the read permissions in ACL file (http://andsel.github.io/moquette/#_user_specific_acl) doesn't fit your need?

 Andrea

**Comment by dant3** [comment]
It looks like that I was needed but using ACL file doesn't seems to be scale for my needs. I would have dozens of static rules this way, in fact it will be square of users count or more and I'll have many users. It would be much easier to define them programmatically via some sort of predicate. Moreover I want to restrict reading of some topics, so that every user has his private topic not accessible to others.

----- Reply message -----
От: "Andrea Selva" notifications@github.com
Кому: "andsel/moquette" moquette@noreply.github.com
Копия: "Viacheslav Blinov" vblinov@unison.com
Тема: [moquette] Limit message receiving by permissions from auth (#98)
Дата: чт, сент. 17, 2015 00:36

Hi @dant3 the read permissions in ACL file (http://andsel.github.io/moquette/#_user_specific_acl) doesn't fit your need?

Andrea

**Comment by dant3** [comment]
Ok, so I see I can just add custom implementation of `IAuthorizator` and hook it in via `AUTHORIZATOR_CLASS_NAME` property and it should support no-args ctor from what I see. I'll try to hack on it this way.

**Comment by andsel** [comment]
Yes it's the only viable way and it's quite straightforward. Keep in mind
that all the code inside there is executed by the main event thread so if
you want to keep performance decent, avoid long tasks (expecially DB IO).
Happy hacking!!

 Andrea

On Thu, Sep 17, 2015 at 3:00 PM, Viacheslav Blinov <notifications@github.com
